# Notebook 03 – Goal 3: Unified Evaluation Framework

**Authors:** Ivo Rambaldi & Tommaso Petrelli  
**Course:** Ethics for Artificial Intelligence, University of Bologna, a.y. 2025–2026

---

## Goal 3 — Utility and Fairness Measurement Framework

This notebook implements Goal 3 of the project:

> Implement a unified evaluation module computing all utility and fairness metrics for any (train-data, test-data, classifier) triple. Validate metric implementations on the real-data baseline.

### Structure

1. **Setup** — imports, config, constants  
2. **Data loading** — reconstruct `DataSplit` from Goal 1 outputs; binarise protected attributes; encode features  
3. **Synthetic data loading** — load Goal 2 outputs; align feature schema  
4. **Real-data baseline validation** — run `Evaluator.baseline()` for all three classifiers  
5. **TSTR evaluation loop** — full `(generator × classifier)` matrix  
6. **Utility analysis** — tables and bar charts of BA / F1 / AUC and MMD  
7. **Fairness analysis** — DPD / EOD / DI tables, per-attribute plots, delta heatmaps  
8. **Fairness mitigation** — equalized-odds and prejudice-remover training, one protected attribute at a time, still under TSTR  
9. **Summary**

## 1 · Setup

In [1]:
from __future__ import annotations

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure the project root is on sys.path so 'src' imports resolve correctly
PROJECT_ROOT = Path().resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
warnings.filterwarnings("ignore")

from src.utils import get_logger, load_config, check_prerequisites
check_prerequisites()
from src.data.preprocessor import DataSplit, save_split
from src.models.classifiers import build_classifier, CLASSIFIER_DISPLAY_NAMES
from src.evaluation.evaluator import Evaluator, MitigatedEvaluator
from src.evaluation.delta import compute_delta_matrix, get_fairness_delta_columns
from src.utils import (
    plot_utility_bar,
    plot_fairness_bar,
    plot_mmd_bar,
    plot_delta_heatmap,
    plot_utility_fairness_scatter,
    plot_per_attribute_fairness,
    plot_class_balance,
)

logger = get_logger("notebook_03")

Prerequisites check (requirements.txt): 16 OK, 0 missing, 0 version-mismatched.

In [2]:
cfg = load_config(PROJECT_ROOT / 'config' / 'config.yaml')

# Route every saved figure/CSV to a dedicated mitigation/task sub-directory so
# G3 (mitigation) and G4 (no_mitigation), and their LowPerf/high-perf pairs, never
# overwrite each other's outputs (previously all four wrote summary figures to the
# same results/figures/ path with the same filenames).
cfg["paths"]["results_dir"] = cfg["paths"]["results_dir"] / "mitigation" / "high_perf"
cfg["paths"]["figures_dir"] = cfg["paths"]["figures_dir"] / "mitigation" / "high_perf"

TARGET_COL  = cfg["target"]["column_name"]            # "target_high_perf"
SEED        = cfg["seed"]
CLASSIFIERS = list(CLASSIFIER_DISPLAY_NAMES.keys())

METHODS     = [m for m in cfg["generation"]["output_subdirs"].keys() if m != "smote_low_perf"]  # [ctgan, tvae, gaussian_copula, smote]

BASELINE    = cfg["experiments"]["baseline_label"]

# Protected attributes for fairness evaluation — single source of truth in config.yaml
PROTECTED_ATTRS = cfg["dataset"]["protected_attributes"]

print(f"Target       : {TARGET_COL}")
print(f"Classifiers  : {CLASSIFIERS}")
print(f"Gen. methods : {METHODS}")
print(f"Protected    : {PROTECTED_ATTRS}")
print(f"Seed         : {SEED}")

Target       : target_high_perf
Classifiers  : ['logistic_regression', 'xgboost', 'mlp']
Gen. methods : ['ctgan', 'tvae', 'gaussian_copula', 'smote']
Protected    : ['s_gender', 's_birth_country', 'f_mother_education_level', 'f_father_education_level', 'f_mother_occupation', 'f_father_occupation', 'f_extent_of_books_at_home', 'f_frequency_of_see_adult_read', 'p_public_or_private', 'p_island', 'p_percentage_of_teachers_changed_school_last_year', 'f_ESCS']
Seed         : 42

## 2 · Data Loading & DataSplit Construction

We load the train / test CSVs produced by Notebook 01, slice out the protected
attribute columns configured in `config.yaml` (`dataset.protected_attributes`),
and apply a consistent OrdinalEncoder + StandardScaler (fit on the real
training set only) to build the `DataSplit` that the `Evaluator` expects.

### Protected attributes

We pass the **raw, un-binarised** protected-attribute columns straight through.
`src/evaluation/fairness.py` already auto-binarises any attribute at evaluation
time (`_binarise_attribute`: direct mapping for already-binary columns, median
split for ordinal/continuous ones such as `f_ESCS`), so no manual binarisation
step is needed here.

In [3]:
train_df = pd.read_csv(cfg["paths"]["train_data"])
test_df  = pd.read_csv(cfg["paths"]["test_data"])

print(f"Train : {train_df.shape}   Test : {test_df.shape}")
print(f"\nClass balance (train):\n{train_df[TARGET_COL].value_counts(normalize=True).round(3)}")
print(f"\nClass balance (test):\n{test_df[TARGET_COL].value_counts(normalize=True).round(3)}")

Train : (58128, 48)   Test : (14533, 48)

Class balance (train):
target_high_perf
0    0.75
1    0.25
Name: proportion, dtype: float64

Class balance (test):
target_high_perf
0    0.756
1    0.244
Name: proportion, dtype: float64

In [4]:
present_attrs = [a for a in PROTECTED_ATTRS if a in train_df.columns]
missing_attrs = [a for a in PROTECTED_ATTRS if a not in train_df.columns]
if missing_attrs:
    print(f"  WARNING: {len(missing_attrs)} configured protected attributes "
          f"not present in the data — skipping: {missing_attrs}")

protected_train = train_df[present_attrs].copy()
protected_test  = test_df[present_attrs].copy()

for attr in protected_train.columns:
    print(f"\n{attr}:")
    print(f"  Train: {protected_train[attr].value_counts(dropna=False).to_dict()}")
    print(f"  Test : {protected_test[attr].value_counts(dropna=False).to_dict()}")

s_gender:
  Train: {'MALE': 29356, 'FEMALE': 28772}
  Test : {'MALE': 7482, 'FEMALE': 7051}

s_birth_country:
  Train: {nan: 45564, 'ESP': 11517, 'VEN': 175, 'ITA': 104, 'CUB': 92, 'CHN': 77, 'COL': 65, 'ARG': 51, 'MAR': 49, 'URY': 31, 'BOL': 31, 'GBR': 29, 'ECU': 23, 'PER': 22, 'RUS': 21, 'DEU': 19, 'DOM': 18, 'ROU': 18, 'BRA': 15, 'USA': 15, 'BGR': 12, 'PHL': 12, 'FRA': 10, 'POL': 9, 'PRT': 9, 'BEL': 8, 'IRL': 8, 'SWE': 8, 'CHL': 7, 'NLD': 7, 'IND': 6, 'MEX': 6, 'PRY': 6, 'NGA': 5, 'SEN': 5, 'HND': 5, 'UKR': 5, 'CZE': 4, 'BGD': 4, 'MLI': 4, 'GTM': 4, 'HUN': 4, 'SVN': 3, 'DZA': 3, 'NPL': 3, 'SLV': 2, 'FIN': 2, 'PAN': 2, 'MRT': 2, 'LTU': 2, 'GNQ': 2, 'ISL': 2, 'LVA': 2, 'CHE': 2, 'COG': 2, 'PAK': 1, 'GEO': 1, 'GMB': 1, 'AUT': 1, 'SVK': 1, 'SYR': 1, 'GIN': 1, 'ETH': 1, 'BLR': 1, 'PRI': 1, 'CPV': 1, 'CMR': 1, 'ESH': 1, 'CAN': 1, 'DNK': 1}
  Test : {nan: 11318, 'ESP': 2941, 'VEN': 51, 'CUB': 27, 'ITA': 24, 'COL': 18, 'CHN': 17, 'ARG': 11, 'URY': 9, 'BOL': 8, 'ROU': 8, 'MAR': 7, 'DEU': 7, 'PRY': 6, 'POL': 5, 'GBR': 5, 'ECU': 5, 'RUS': 4, 'DOM': 4, 'IRL': 3, 'PRT': 3, 'USA': 3, 'MRT': 3, 'SEN': 3, 'CHL': 3, 'HUN': 3, 'PHL': 2, 'HND': 2, 'FRA': 2, 'BGR': 2, 'PAK': 2, 'BRA': 2, 'NGA': 2, 'BEL': 2, 'PER': 2, 'ISL': 2, 'CZE': 2, 'MEX': 1, 'AUT': 1, 'LVA': 1, 'BIH': 1, 'IRN': 1, 'BGD': 1, 'SWE': 1, 'NPL': 1, 'CRI': 1, 'SVK': 1, 'CHE': 1, 'IND': 1, 'GIN': 1, 'UKR': 1, 'GMB': 1}

f_mother_education_level:
  Train: {nan: 16166, 4.0: 10973, 3.0: 9504, 5.0: 5578, 7.0: 4987, 2.0: 4753, 6.0: 4399, 8.0: 1084, 9.0: 422, 1.0: 262}
  Test : {nan: 4163, 4.0: 2658, 3.0: 2322, 5.0: 1438, 7.0: 1240, 2.0: 1195, 6.0: 1048, 8.0: 296, 9.0: 117, 1.0: 56}

f_father_education_level:
  Train: {nan: 19027, 4.0: 9950, 3.0: 9948, 2.0: 6409, 5.0: 4350, 7.0: 3687, 6.0: 2953, 8.0: 896, 9.0: 478, 1.0: 430}
  Test : {nan: 4926, 4.0: 2481, 3.0: 2395, 2.0: 1584, 5.0: 1116, 7.0: 900, 6.0: 738, 8.0: 192, 9.0: 114, 1.0: 87}

f_mother_occupation:
  Train: {3.0: 23110, nan: 17842, 4.0: 8923, 2.0: 6887, 1.0: 1366}
  Test : {3.0: 5844, nan: 4587, 4.0: 2105, 2.0: 1661, 1.0: 336}

f_father_occupation:
  Train: {3.0: 22155, nan: 20193, 4.0: 9817, 2.0: 5654, 1.0: 309}
  Test : {3.0: 5495, nan: 5223, 4.0: 2314, 2.0: 1412, 1.0: 89}

f_extent_of_books_at_home:
  Train: {0.25: 17033, nan: 15018, 0.5: 9761, 0.0: 7046, 0.75: 4859, 1.0: 4411}
  Test : {0.25: 4320, nan: 3883, 0.5: 2410, 0.0: 1674, 0.75: 1179, 1.0: 1067}

f_frequency_of_see_adult_read:
  Train: {nan: 20635, 0.25: 6596, 0.5: 6504, 0.625: 6328, 0.125: 5380, 1.0: 3344, 0.875: 3135, 0.375: 2396, 0.75: 1934, 0.0: 1876}
  Test : {nan: 5346, 0.25: 1609, 0.5: 1577, 0.625: 1554, 0.125: 1313, 1.0: 831, 0.875: 773, 0.375: 618, 0.75: 467, 0.0: 445}

p_public_or_private:
  Train: {2.0: 43702, 1.0: 14426}
  Test : {2.0: 10857, 1.0: 3676}

p_island:
  Train: {4.0: 25714, 1.0: 22726, 2.0: 7723, 3.0: 1965}
  Test : {4.0: 6356, 1.0: 5735, 2.0: 1990, 3.0: 452}

p_percentage_of_teachers_changed_school_last_year:
  Train: {2.0: 20446, 1.0: 17153, 3.0: 12886, 4.0: 4329, nan: 3314}
  Test : {2.0: 5095, 1.0: 4348, 3.0: 3182, 4.0: 1115, nan: 793}

f_ESCS:

In [5]:
from src.data.preprocessing import get_feature_columns

# exclude_missingness_flags=True: this notebook runs fairness mitigation
# (Section 8) targeted at individual protected attributes, so the `{attr}_was_nan`
# flags (proxies for missingness of a protected attribute -- see G1) must not
# leak back into the feature set. See src/data/preprocessing.get_feature_columns.
FEATURE_COLS = get_feature_columns(train_df, cfg, exclude_missingness_flags=True)

X_train_raw = train_df[FEATURE_COLS]
X_test_raw  = test_df[FEATURE_COLS]
y_train     = train_df[TARGET_COL].astype(int)
y_test      = test_df[TARGET_COL].astype(int)

print(f"X_train : {X_train_raw.shape}   X_test : {X_test_raw.shape}")
print(f"Positive rate — train: {y_train.mean():.1%}  test: {y_test.mean():.1%}")

X_train : (58128, 37)   X_test : (14533, 37)
Positive rate — train: 25.0%  test: 24.4%

### Feature encoding

Logistic Regression and MLP require fully numerical input; XGBoost also benefits
from it when using the sklearn wrapper. We apply:

- **OrdinalEncoder** (fit on X_train) to all `object`-dtype columns  
- **StandardScaler** (fit on X_train) to all numerical columns  

The fitted transformers are stored in `DataSplit.encoders` and `DataSplit.scaler`
so they can be applied to synthetic data in the same way.

In [6]:
from src.data.preprocessor import fit_feature_encoders, apply_feature_encoders

enc, scaler, cat_cols, num_cols = fit_feature_encoders(X_train_raw)
X_train = apply_feature_encoders(X_train_raw, enc, scaler, cat_cols, num_cols)
X_test  = apply_feature_encoders(X_test_raw,  enc, scaler, cat_cols, num_cols)

print(f"Encoded X_train: {X_train.shape}  (cat={len(cat_cols)}, num={len(num_cols)})")
print(f"Any NaNs remaining: {X_train.isna().any().any()}")

Encoded X_train: (58128, 37)  (cat=2, num=35)
Any NaNs remaining: False

In [7]:
FEATURE_NAMES  = X_train.columns.tolist()
PROTECTED_COLS = [c for c in PROTECTED_ATTRS if c in protected_train.columns]

split = DataSplit(
    X_train        = X_train,
    X_test         = X_test,
    y_train        = y_train,
    y_test         = y_test,
    protected_train= protected_train[PROTECTED_COLS],
    protected_test = protected_test[PROTECTED_COLS],
    feature_names  = FEATURE_NAMES,
    target_name    = TARGET_COL,
    protected_attrs= PROTECTED_COLS,
    encoders       = {"ordinal": enc},
    scaler         = scaler,
)

# Persist for downstream notebooks (Goal 4 / 5)
save_split(split, cfg["paths"]["processed_data"].parent / "data_split.pkl")
print("DataSplit built and saved.")
print(f"  X_train      : {split.X_train.shape}")
print(f"  X_test       : {split.X_test.shape}")
print(f"  Protected    : {PROTECTED_COLS}")

2026-07-25 02:22:23 | INFO     | src.data.preprocessor | DataSplit saved to C:\Users\tomma\Desktop\petrellirambaldi2526\Data\data_split.pkl.

DataSplit built and saved.
  X_train      : (58128, 37)
  X_test       : (14533, 37)
  Protected    : ['s_gender', 's_birth_country', 'f_mother_education_level', 'f_father_education_level', 'f_mother_occupation', 'f_father_occupation', 'f_extent_of_books_at_home', 'f_frequency_of_see_adult_read', 'p_public_or_private', 'p_island', 'p_percentage_of_teachers_changed_school_last_year', 'f_ESCS']

## 3 · Load Synthetic Datasets (Goal 2 outputs)

We load the four CSV files produced by Notebook 02, align their column schema to
the real training set (inner join on feature names), and apply the same
OrdinalEncoder + StandardScaler fitted above.

> **Note:** SMOTE produces an oversampled dataset that includes all original
> training rows plus new synthetic minority-class rows, so its size will differ
> from the other generators.

In [8]:
from src.utils.config import get_synthetic_output_path


def load_synthetic(method: str) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame]:
    """Load synthetic CSV, encode features, return (X_synth, y_synth, protected_synth).

    protected_synth holds the RAW (unencoded) protected-attribute columns from
    the synthetic CSV, row-aligned with X_synth/y_synth. Needed by the
    mitigation loop below: a synthetic training set can have a different row
    count than the real training set (e.g. SMOTE's class-balanced output), so
    split.protected_train can't be reused for it -- each source must carry its
    own protected-attribute values.
    """
    path = get_synthetic_output_path(cfg, method)
    if not path.exists():
        raise FileNotFoundError(
            f"Synthetic data not found at {path}.\n"
            f"Run Notebook 02 first to generate it."
        )
    df = pd.read_csv(path)

    if TARGET_COL not in df.columns:
        raise ValueError(f"Target column '{TARGET_COL}' missing from {path}.")

    y_synth = df[TARGET_COL].astype(int)

    # Keep only features present in the real training set
    feat_cols = [c for c in FEATURE_NAMES if c in df.columns]
    missing   = set(FEATURE_NAMES) - set(df.columns)
    if missing:
        print(f"  [{method}] WARNING: {len(missing)} feature cols absent "
              f"from synthetic data — filled with 0.")

    X_synth_raw = pd.DataFrame(index=df.index)
    for col in FEATURE_NAMES:
        X_synth_raw[col] = df[col] if col in df.columns else 0.0

    X_synth = apply_feature_encoders(X_synth_raw, enc, scaler, cat_cols, num_cols)

    protected_synth = pd.DataFrame(
        {c: (df[c] if c in df.columns else np.nan) for c in PROTECTED_COLS},
        index=df.index,
    )

    return X_synth, y_synth, protected_synth


synthetic_data: dict[str, tuple[pd.DataFrame, pd.Series, pd.DataFrame]] = {}

for method in METHODS:
    try:
        X_s, y_s, prot_s = load_synthetic(method)
        synthetic_data[method] = (X_s, y_s, prot_s)
        pos_rate = y_s.mean()
        print(f"  [{method}]  rows={len(X_s):,}   +class={pos_rate:.1%}   "
              f"cols={X_s.shape[1]}")
    except FileNotFoundError as e:
        print(f"  [{method}]  SKIPPED — {e}")

print(f"\nLoaded {len(synthetic_data)}/{len(METHODS)} synthetic datasets.")

  [ctgan]  rows=58,128   +class=24.5%   cols=37

  [tvae]  rows=58,128   +class=23.6%   cols=37

  [gaussian_copula]  rows=58,128   +class=25.1%   cols=37

  [smote]  rows=87,188   +class=50.0%   cols=37

Loaded 4/4 synthetic datasets.

In [9]:
# Quick sanity check: class balance across all datasets
raw_synthetics_for_plot = {}
for method, (X_s, y_s, _) in synthetic_data.items():
    df_plot = X_s.copy()
    df_plot[TARGET_COL] = y_s.values
    raw_synthetics_for_plot[method] = df_plot

real_plot = X_train.copy()
real_plot[TARGET_COL] = y_train.values

_ = plot_class_balance(real_plot, raw_synthetics_for_plot, cfg, save=True)
plt.show()
print("Class balance looks reasonable if synthetic proportions are close to real.")

2026-07-25 02:22:25 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\class_balance.png

Class balance looks reasonable if synthetic proportions are close to real.

## 4 · Real-Data Baseline Validation

We run `Evaluator.baseline(clf)` for all three classifiers on the real training split.
This step **validates the metric pipeline**: if these numbers look reasonable for a
dataset of this size and complexity, we can trust the TSTR deltas downstream.

Expected ballpark for the Aequitas education dataset with a balanced-accuracy target:
- Logistic Regression: BA ≈ 0.65–0.75
- XGBoost: BA ≈ 0.70–0.80
- MLP: BA ≈ 0.65–0.78

In [10]:
evaluator = Evaluator(split, cfg)

baseline_rows = []
for clf_name in CLASSIFIERS:
    result = evaluator.baseline(clf_name)
    row = {
        "method"            : BASELINE,
        "classifier"        : clf_name,
        "balanced_accuracy" : result["balanced_accuracy"],
        "f1_macro"          : result["f1_macro"],
        "roc_auc"           : result["roc_auc"],
    }
    
    # Attach per-attribute fairness metrics
    for attr in PROTECTED_COLS:
        for metric in ("dpd", "eod", "di"):
            key = f"{attr}_{metric}"
            if key in result:
                row[key] = result[key]
    baseline_rows.append(row)
    print(f"  [{clf_name}]  BA={result['balanced_accuracy']:.4f}  "
          f"F1={result['f1_macro']:.4f}  AUC={result['roc_auc']:.4f}")

2026-07-25 02:22:25 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [logistic_regression] …

2026-07-25 02:22:26 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6737 | BA=0.6226

  [logistic_regression]  BA=0.6226  F1=0.5875  AUC=0.6737
2026-07-25 02:22:26 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [xgboost] …

2026-07-25 02:22:27 | INFO     | src.evaluation.evaluator |   [real] AUC=0.7135 | BA=0.6538

  [xgboost]  BA=0.6538  F1=0.6180  AUC=0.7135
2026-07-25 02:22:27 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [mlp] …

2026-07-25 02:22:38 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6899 | BA=0.5629

  [mlp]  BA=0.5629  F1=0.5584  AUC=0.6899

In [11]:
baseline_df = pd.DataFrame(baseline_rows)

# Compute mean fairness metrics per classifier (across protected attrs)
for metric in ("dpd", "eod", "di", "odds_ratio"):
    cols = [c for c in baseline_df.columns
            if c.endswith(f"_{metric}") and not c.startswith(("fairness_gap", "mean_"))]
    if cols:
        baseline_df[f"mean_{metric}"] = baseline_df[cols].mean(axis=1)

display_cols = ["classifier", "balanced_accuracy", "f1_macro", "roc_auc",
                "mean_dpd", "mean_eod", "mean_di", "mean_odds_ratio"]
display_cols = [c for c in display_cols if c in baseline_df.columns]

print("Real-data baseline metrics:")
print(baseline_df[display_cols].round(4).to_string(index=False))

Real-data baseline metrics:
         classifier  balanced_accuracy  f1_macro  roc_auc  mean_dpd  mean_eod  mean_di
logistic_regression             0.6226    0.5875   0.6737    0.3328    0.3314   0.5077
            xgboost             0.6538    0.6180   0.7135    0.3545    0.3562   0.4808
                mlp             0.5629    0.5584   0.6899    0.1109    0.1687   0.2758

In [12]:
# Fairness check: flag any classifier that already violates thresholds on real data
print("\nFairness threshold checks on real data:")
print(f"  DPD > 0.1 is concerning (demographic parity violation)")
print(f"  EOD > 0.1 is concerning (equalized odds violation)")
print(f"  DI  < 0.8 is concerning (four-fifths rule violation)\n")

for _, row in baseline_df.iterrows():
    flags = []
    if "mean_dpd" in row and row["mean_dpd"] > 0.1:
        flags.append(f"mean_DPD={row['mean_dpd']:.3f}")
    if "mean_eod" in row and row["mean_eod"] > 0.1:
        flags.append(f"mean_EOD={row['mean_eod']:.3f}")
    if "mean_di"  in row and row["mean_di"]  < 0.8:
        flags.append(f"mean_DI={row['mean_di']:.3f}")
    status = "⚠️  " + ", ".join(flags) if flags else "✓ all within thresholds"
    print(f"  [{row['classifier']}]  {status}")

Fairness threshold checks on real data:
  DPD > 0.1 is concerning (demographic parity violation)
  EOD > 0.1 is concerning (equalized odds violation)
  DI  < 0.8 is concerning (four-fifths rule violation)

  [logistic_regression]  ⚠️  mean_DPD=0.333, mean_EOD=0.331, mean_DI=0.508
  [xgboost]  ⚠️  mean_DPD=0.355, mean_EOD=0.356, mean_DI=0.481
  [mlp]  ⚠️  mean_DPD=0.111, mean_EOD=0.169, mean_DI=0.276

> **📝 Result — pre-existing bias, independent of synthetic generation.**
> All three classifiers already violate the DPD/EOD/DI thresholds when trained on the **real** data (mean DPD 0.13–0.41, mean DI 0.35–0.48, all well below the 0.8 four-fifths rule). MLP is the least biased of the three (mean DPD=0.127) but still flagged. This means the unfairness we will see later in the TSTR loop is **inherited from the real dataset / task**, not introduced by CTGAN/TVAE/GaussianCopula/SMOTE — any generator that faithfully reproduces the real joint distribution will reproduce this bias too.

## 5 · TSTR Evaluation Loop

For each `(generator, classifier)` pair:
1. Call `evaluator.baseline(clf)` to set the correct real-data reference for that classifier
2. Train classifier on synthetic data
3. Test on the real held-out test set
4. Record utility metrics, fairness metrics, MMD, and correlation deltas

This is the core Train-on-Synthetic, Test-on-Real (TSTR) framework from the proposal.

In [13]:
all_rows = baseline_rows.copy()  # seed with real baseline rows

for clf_name in CLASSIFIERS:
    # Re-run baseline for this classifier to anchor _real_metrics correctly
    evaluator.baseline(clf_name)

    for method, (X_synth, y_synth, _) in synthetic_data.items():
        logger.info(f"Evaluating [{method} | {clf_name}] ...")
        result = evaluator.evaluate(
            X_synth        = X_synth,
            y_synth        = y_synth,
            classifier_name= clf_name,
            generator_name = method,
            repetition     = 0,
            X_real_for_mmd = split.X_train,
        )
        # rename "generator" -> "method" for plotting compatibility
        row = {"method": result.pop("generator"), **result}
        all_rows.append(row)
        print(f"  [{method} | {clf_name}]  "
              f"BA={row['balanced_accuracy']:.4f}  "
              f"ΔBA={row['delta_balanced_accuracy']:+.4f}  "
              f"MMD={row['mmd']:.4f}")

print(f"\n{len(all_rows)} rows collected ({len(CLASSIFIERS)} baselines + "
      f"{len(synthetic_data) * len(CLASSIFIERS)} TSTR evaluations).")

2026-07-25 02:22:38 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [logistic_regression] …

2026-07-25 02:22:39 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6737 | BA=0.6226

2026-07-25 02:22:39 | INFO     | notebook_03 | Evaluating [ctgan | logistic_regression] ...

2026-07-25 02:22:39 | INFO     | src.evaluation.evaluator | Evaluating [ctgan | logistic_regression | rep=0] …

2026-07-25 02:22:39 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.5785 | BA=0.5600

  [ctgan | logistic_regression]  BA=0.5600  ΔBA=+0.0626  MMD=0.0034
2026-07-25 02:22:42 | INFO     | notebook_03 | Evaluating [tvae | logistic_regression] ...

2026-07-25 02:22:42 | INFO     | src.evaluation.evaluator | Evaluating [tvae | logistic_regression | rep=0] …

2026-07-25 02:22:43 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6528 | BA=0.6042

  [tvae | logistic_regression]  BA=0.6042  ΔBA=+0.0185  MMD=0.0250
2026-07-25 02:22:46 | INFO     | notebook_03 | Evaluating [gaussian_copula | logistic_regression] ...

2026-07-25 02:22:46 | INFO     | src.evaluation.evaluator | Evaluating [gaussian_copula | logistic_regression | rep=0] …

2026-07-25 02:22:46 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.4024 | BA=0.4317

  [gaussian_copula | logistic_regression]  BA=0.4317  ΔBA=+0.1909  MMD=0.0023
2026-07-25 02:22:49 | INFO     | notebook_03 | Evaluating [smote | logistic_regression] ...

2026-07-25 02:22:49 | INFO     | src.evaluation.evaluator | Evaluating [smote | logistic_regression | rep=0] …

2026-07-25 02:22:50 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6727 | BA=0.6194

  [smote | logistic_regression]  BA=0.6194  ΔBA=+0.0033  MMD=0.0020
2026-07-25 02:22:53 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [xgboost] …

2026-07-25 02:22:54 | INFO     | src.evaluation.evaluator |   [real] AUC=0.7135 | BA=0.6538

2026-07-25 02:22:54 | INFO     | notebook_03 | Evaluating [ctgan | xgboost] ...

2026-07-25 02:22:54 | INFO     | src.evaluation.evaluator | Evaluating [ctgan | xgboost | rep=0] …

2026-07-25 02:22:56 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.5525 | BA=0.5344

  [ctgan | xgboost]  BA=0.5344  ΔBA=+0.1194  MMD=0.0034
2026-07-25 02:22:59 | INFO     | notebook_03 | Evaluating [tvae | xgboost] ...

2026-07-25 02:22:59 | INFO     | src.evaluation.evaluator | Evaluating [tvae | xgboost | rep=0] …

2026-07-25 02:23:00 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6600 | BA=0.6148

  [tvae | xgboost]  BA=0.6148  ΔBA=+0.0390  MMD=0.0250
2026-07-25 02:23:04 | INFO     | notebook_03 | Evaluating [gaussian_copula | xgboost] ...

2026-07-25 02:23:04 | INFO     | src.evaluation.evaluator | Evaluating [gaussian_copula | xgboost | rep=0] …

2026-07-25 02:23:05 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.4275 | BA=0.4455

  [gaussian_copula | xgboost]  BA=0.4455  ΔBA=+0.2083  MMD=0.0023
2026-07-25 02:23:08 | INFO     | notebook_03 | Evaluating [smote | xgboost] ...

2026-07-25 02:23:08 | INFO     | src.evaluation.evaluator | Evaluating [smote | xgboost | rep=0] …

2026-07-25 02:23:10 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.5543 | BA=0.5259

  [smote | xgboost]  BA=0.5259  ΔBA=+0.1279  MMD=0.0020
2026-07-25 02:23:13 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [mlp] …

2026-07-25 02:23:25 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6899 | BA=0.5629

2026-07-25 02:23:25 | INFO     | notebook_03 | Evaluating [ctgan | mlp] ...

2026-07-25 02:23:25 | INFO     | src.evaluation.evaluator | Evaluating [ctgan | mlp | rep=0] …

2026-07-25 02:23:34 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.5425 | BA=0.5001

  [ctgan | mlp]  BA=0.5001  ΔBA=+0.0628  MMD=0.0034
2026-07-25 02:23:37 | INFO     | notebook_03 | Evaluating [tvae | mlp] ...

2026-07-25 02:23:37 | INFO     | src.evaluation.evaluator | Evaluating [tvae | mlp | rep=0] …

2026-07-25 02:23:49 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6536 | BA=0.5847

  [tvae | mlp]  BA=0.5847  ΔBA=-0.0218  MMD=0.0250
2026-07-25 02:23:53 | INFO     | notebook_03 | Evaluating [gaussian_copula | mlp] ...

2026-07-25 02:23:53 | INFO     | src.evaluation.evaluator | Evaluating [gaussian_copula | mlp | rep=0] …

2026-07-25 02:24:00 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.4599 | BA=0.4999

  [gaussian_copula | mlp]  BA=0.4999  ΔBA=+0.0630  MMD=0.0023
2026-07-25 02:24:03 | INFO     | notebook_03 | Evaluating [smote | mlp] ...

2026-07-25 02:24:03 | INFO     | src.evaluation.evaluator | Evaluating [smote | mlp | rep=0] …

2026-07-25 02:24:38 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6353 | BA=0.5956

  [smote | mlp]  BA=0.5956  ΔBA=-0.0327  MMD=0.0020

15 rows collected (3 baselines + 12 TSTR evaluations).

In [14]:
results_df = pd.DataFrame(all_rows)

# Add aggregated mean fairness columns (mean across protected attributes).
# Excludes "mean_*" itself (already provided per-row by Evaluator for synthetic
# rows) to avoid averaging that column into its own recomputation.
for metric in ("dpd", "eod", "di", "odds_ratio"):
    attr_cols = [c for c in results_df.columns
                 if c.endswith(f"_{metric}") and not c.startswith(("fairness_gap", "mean_"))]
    if attr_cols:
        results_df[f"mean_{metric}"] = results_df[attr_cols].mean(axis=1)

# Save results
results_path = cfg["paths"]["results_dir"] / "goal3_results.csv"
results_path.parent.mkdir(parents=True, exist_ok=True)
results_df.to_csv(results_path, index=False)
print(f"Results saved → {results_path}")
print(f"Shape: {results_df.shape}")
results_df.head(3)

Results saved → C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\high_perf\goal3_results.csv
Shape: (15, 66)

,method,classifier,balanced_accuracy,f1_macro,roc_auc,s_gender_dpd,s_gender_eod,s_gender_di,s_birth_country_dpd,s_birth_country_eod,...,mean_dpd,mean_eod,mean_di,mean_odds_ratio,delta_balanced_accuracy,delta_f1_macro,delta_roc_auc,mmd,corr_mean_abs_delta,corr_max_abs_delta
0,real,logistic_regression,0.622629,0.587467,0.673722,0.121622,0.134518,0.739784,0.092637,0.108494,...,0.332837,0.331368,0.507709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,real,xgboost,0.653807,0.617955,0.713531,0.074904,0.092985,0.825357,0.126880,0.167466,...,0.354505,0.356168,0.480785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,real,mlp,0.562888,0.558446,0.689855,0.028293,0.057815,0.646596,0.041952,0.108524,...,0.110933,0.168720,0.275846,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 6 · Utility Analysis

We examine how much predictive utility is lost when classifiers are trained on
synthetic data instead of real data.  
The primary metric is **balanced accuracy** (BA), which is robust to the class
imbalance present in the excellence-detection task. We also report F1-macro
and ROC-AUC for completeness.

In [15]:
print(f"Total rows: {len(all_rows)}")
print(f"Methods present: {set(r['method'] for r in all_rows)}")

Total rows: 15
Methods present: {'smote', 'ctgan', 'real', 'tvae', 'gaussian_copula'}

In [16]:
utility_cols = ["method", "classifier", "balanced_accuracy", "f1_macro", "roc_auc",
                "delta_balanced_accuracy", "delta_f1_macro", "delta_roc_auc", "mmd"]
utility_table = results_df[utility_cols].sort_values(
    ["classifier", "balanced_accuracy"], ascending=[True, False]
)
print("Utility metrics (all methods × classifiers):\n")
print(utility_table.round(4).to_string(index=False))

Utility metrics (all methods × classifiers):

         method          classifier  balanced_accuracy  f1_macro  roc_auc  delta_balanced_accuracy  delta_f1_macro  delta_roc_auc    mmd
           real logistic_regression             0.6226    0.5875   0.6737                      NaN             NaN            NaN    NaN
          smote logistic_regression             0.6194    0.5813   0.6727                   0.0033          0.0061         0.0010 0.0020
           tvae logistic_regression             0.6042    0.6002   0.6528                   0.0185         -0.0127         0.0209 0.0250
          ctgan logistic_regression             0.5600    0.5251   0.5785                   0.0626          0.0624         0.0952 0.0034
gaussian_copula logistic_regression             0.4317    0.4204   0.4024                   0.1909          0.1671         0.2714 0.0023
          smote                 mlp             0.5956    0.5710   0.6353                  -0.0327         -0.0126         0.0545 0.0020
           tvae                 mlp             0.5847    0.5902   0.6536                  -0.0218         -0.0317         0.0362 0.0250
           real                 mlp             0.5629    0.5584   0.6899                      NaN             NaN            NaN    NaN
          ctgan                 mlp             0.5001    0.4309   0.5425                   0.0628          0.1276         0.1473 0.0034
gaussian_copula                 mlp             0.4999    0.4305   0.4599                   0.0630          0.1279         0.2299 0.0023
           real             xgboost             0.6538    0.6180   0.7135                      NaN             NaN            NaN    NaN
           tvae             xgboost             0.6148    0.6028   0.6600                   0.0390          0.0151         0.0535 0.0250
          ctgan             xgboost             0.5344    0.5009   0.5525                   0.1194          0.1170         0.1611 0.0034
          smote             xgboost             0.5259    0.5002   0.5543                   0.1279          0.1177         0.1593 0.0020
gaussian_copula             xgboost             0.4455    0.4116   0.4275                   0.2083          0.2064         0.2860 0.0023

In [17]:
# Best method per classifier by balanced accuracy
print("Best synthetic method per classifier (by balanced accuracy):\n")
synth_mask = results_df["method"] != BASELINE
best = (results_df[synth_mask]
        .groupby("classifier")
        .apply(lambda g: g.nlargest(1, "balanced_accuracy"))
        .reset_index(drop=True)
        [["classifier", "method", "balanced_accuracy", "delta_balanced_accuracy"]])
print(best.round(4).to_string(index=False))

Best synthetic method per classifier (by balanced accuracy):

         classifier method  balanced_accuracy  delta_balanced_accuracy
logistic_regression  smote             0.6194                   0.0033
                mlp  smote             0.5956                  -0.0327
            xgboost   tvae             0.6148                   0.0390

In [18]:
for metric in ["balanced_accuracy", "f1_macro", "roc_auc"]:
    fig = plot_utility_bar(results_df, metric, cfg, save=True)
    plt.show()

2026-07-25 02:24:41 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\utility_balanced_accuracy.png

2026-07-25 02:24:42 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\utility_f1_macro.png

2026-07-25 02:24:42 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\utility_roc_auc.png

In [19]:
fig = plot_mmd_bar(results_df, cfg, save=True)
plt.show()

print("\nMMD summary (lower = synthetic distribution closer to real):")
mmd_summary = (results_df[results_df["method"] != BASELINE]
               .drop_duplicates("method")[["method","mmd"]]
               .sort_values("mmd"))
print(mmd_summary.round(4).to_string(index=False))

2026-07-25 02:24:42 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\mmd_comparison.png

MMD summary (lower = synthetic distribution closer to real):
         method    mmd
          smote 0.0020
gaussian_copula 0.0023
          ctgan 0.0034
           tvae 0.0250

> **📝 Result (updated after the 2026-07-18 synthetic-data regeneration) — MMD no longer tracks utility, and GaussianCopula has collapsed.**
> With the current synthetic CSVs, mean balanced-accuracy loss vs. the real baseline ranks generators as **TVAE (−0.018) < CTGAN (−0.029) < SMOTE (−0.049) ≪ GaussianCopula (−0.117, catastrophic)** — a different order from the pre-regeneration run, where CTGAN was best. MMD, meanwhile, still ranks **CTGAN (0.0028) < SMOTE (0.0055) < GaussianCopula (0.0065) < TVAE (0.0071)** — CTGAN has the *best* distributional fidelity but is only second-best on utility now, and GaussianCopula has middling MMD despite being nearly unusable downstream (BA 0.49–0.51 for LR/XGBoost — chance level). MMD is not a reliable stand-in for TSTR utility on this data.

## 7 · Fairness Analysis

For each configured protected attribute (`config.yaml`'s `dataset.protected_attributes`,
intersected with the columns actually present in the data) and each
`(method, classifier)` combination we measure:

| Metric | Definition | Good value |
|--------|-----------|------------|
| **DPD** | \|Pr[Ŷ=1\|A=0] − Pr[Ŷ=1\|A=1]\| | close to 0 |
| **EOD** | max(\|ΔTPR\|, \|ΔFPR\|) | close to 0 |
| **DI** | Pr[Ŷ=1\|A=0] / Pr[Ŷ=1\|A=1] | ≥ 0.8 (four-fifths rule) |

We compare real-trained models with synth-trained models. A good generator
**preserves** the fairness profile of the real baseline — it neither improves
nor worsens it artificially.

In [20]:
fairness_base_cols = ["method", "classifier"]
dpd_cols = [c for c in results_df.columns if c.endswith("_dpd") and not c.startswith("fairness")]
eod_cols = [c for c in results_df.columns if c.endswith("_eod") and not c.startswith("fairness")]
di_cols  = [c for c in results_df.columns if c.endswith("_di")  and not c.startswith("fairness")]
odds_cols = [c for c in results_df.columns if c.endswith("_odds_ratio") and not c.startswith("fairness")]
mean_cols = [c for c in ["mean_dpd","mean_eod","mean_di","mean_odds_ratio"] if c in results_df.columns]
gap_cols  = [c for c in results_df.columns if c.startswith("fairness_gap_")]

fairness_table = results_df[fairness_base_cols + dpd_cols + eod_cols + di_cols + odds_cols + mean_cols].copy()
print("Fairness metrics (all methods × classifiers):\n")
print(fairness_table.round(4).to_string(index=False))

Fairness metrics (all methods × classifiers):

         method          classifier  s_gender_dpd  s_birth_country_dpd  f_mother_education_level_dpd  f_father_education_level_dpd  f_mother_occupation_dpd  f_father_occupation_dpd  f_extent_of_books_at_home_dpd  f_frequency_of_see_adult_read_dpd  p_public_or_private_dpd  p_island_dpd  p_percentage_of_teachers_changed_school_last_year_dpd  f_ESCS_dpd  mean_dpd  s_gender_eod  s_birth_country_eod  f_mother_education_level_eod  f_father_education_level_eod  f_mother_occupation_eod  f_father_occupation_eod  f_extent_of_books_at_home_eod  f_frequency_of_see_adult_read_eod  p_public_or_private_eod  p_island_eod  p_percentage_of_teachers_changed_school_last_year_eod  f_ESCS_eod  mean_eod  s_gender_di  s_birth_country_di  f_mother_education_level_di  f_father_education_level_di  f_mother_occupation_di  f_father_occupation_di  f_extent_of_books_at_home_di  f_frequency_of_see_adult_read_di  p_public_or_private_di  p_island_di  p_percentage_of_teachers_changed_school_last_year_di  f_ESCS_di  mean_di  s_gender_odds_ratio  s_birth_country_odds_ratio  f_mother_education_level_odds_ratio  f_father_education_level_odds_ratio  f_mother_occupation_odds_ratio  f_father_occupation_odds_ratio  f_extent_of_books_at_home_odds_ratio  f_frequency_of_see_adult_read_odds_ratio  p_public_or_private_odds_ratio  p_island_odds_ratio  p_percentage_of_teachers_changed_school_last_year_odds_ratio  f_ESCS_odds_ratio  mean_odds_ratio  mean_dpd  mean_eod  mean_di  mean_odds_ratio
           real logistic_regression        0.1216               0.0926                        0.5225                        0.5027                   0.4007                   0.3603                         0.4322                             0.2046                   0.5148        0.1569                                                 0.2365      0.4486    0.3328        0.1345               0.1085                        0.5127                        0.4862                   0.3861                   0.3383                         0.4103                             0.2054                   0.5138        0.1852                                                 0.2691      0.4261    0.3314       0.7398              0.7737                       0.3319                       0.3757                  0.4665                  0.4935                        0.3844                            0.6359                  0.3508       0.6810                                                0.5055     0.3538   0.5077                  NaN                         NaN                                  NaN                                  NaN                             NaN                             NaN                                   NaN                                       NaN                             NaN                  NaN                                                           NaN                NaN              NaN    0.3328    0.3314   0.5077              NaN
           real             xgboost        0.0749               0.1269                        0.5750                        0.5451                   0.4481                   0.4131                         0.4564                             0.2407                   0.4974        0.1286                                                 0.2342      0.5136    0.3545        0.0930               0.1675                        0.5715                        0.5421                   0.4444                   0.4042                         0.4378                             0.2281                   0.4924        0.1464                                                 0.2446      0.5020    0.3562       0.8254              0.6779                       0.2846                       0.3376                  0.4223                  0.4417                        0.3505                            0.5800                  0.3491       0.7209                                                0.4929     0.2865   0.4808                  NaN                         NaN                                  NaN                                  NaN                             NaN                             NaN                                   NaN                                       NaN                             NaN                  NaN                                                           NaN                NaN              NaN    0.3545    0.3562   0.4808              NaN
           real                 mlp        0.0283               0.0420                        0.1579                        0.1834                   0.1885                   0.1447                         0.1227                             0.0517                   0.1687        0.0667                                                 0.0558      0.1209    0.1109        0.0578               0.1085                        0.2296                        0.2596                   0.2479                   0.1907                         0.1762                             0.0708                   0.2727        0.1308                                                 0.1048      0.1752    0.1687       0.6466              0.3719                       0.1191                       0.1313                  0.1715                  0.2303                        0.1806                            0.5085                  0.1231       0.3446                                                0.3259     0.1567   0.2758                  NaN                         NaN                                  NaN                                  NaN                             NaN                             NaN                                   NaN                                       NaN                             NaN                  NaN                                                           NaN                NaN              NaN    0.1109    0.1687   0.2758              NaN
          ctgan logistic_regression        0.0995               0.3371                        0.2330                        0.2032                   0.2477                   0.3307                         0.1414                             0.0760                   0.2406        0.0265                                                 0.0110      0.2087    0.1796        0.1043               0.4387                        0.2271                        0.1944                   0.2483                   0.3296                         0.1701                             0.0779                   0.2504        0.0414                                                 0.0381      0.2343    0.1962       0.8020              0.2593                       0.6230                       0.6679                  0.6265                  0.5466                        0.7418                            0.8506                  0.6188       0.9428                                                0.9760     0.6428   0.6915               1.1921                      5.0577                               0.6638                               0.7116                          0.6631                          0.6139                                0.7324                                    0.9218                          1.5534               1.0077                                                        1.0744             0.6449           1.2364    0.1796    0.1962   0.6915           1.2364
           tvae logistic_regression        0.0968               0.1032                        0.5230                        0.5098                   0.5428                   0.5940                         0.4895                             0.2628                   0.4061        0.1161                                                 0.2089      0.5432    0.3663        0.1456               0.2406                        0.5440                        0.4970                   0.5352                   0.5875                         0.5307                             0.2772                   0.3876        0.1429                                                 0.2786      0.5896    0.3964       0.6944              0.6190                       0.1877                       0.2417                  0.2605                  0.2278                        0.1876                            0.4373                  0.2915       0.6497                                                0.3699     0.1180   0.3571               0.7058                      2.2720                               0.2710                               0.3497                          0.3685                          0.3341                                0.2620                                    0.5546                          2.3438               0.7122                                                        2.3081             0.1849           0.8889    0.3663    0.3964   0.3571           0.8889
gaussian_copula logistic_regression        0.1947               0.2891                        0.3142                        0.3059                   0.3778                   0.3576                         0.2292                             0.0794                   0.3256        0.0795                                                 0.3038      0.3513    0.2673        0.2021               0.3291                        0.3092                        0.3110                   0.3873                   0.3653                         0.2454                             0.0722                   0.3480        0.0804                                                 0.2981      0.3431    0.2743       0.6445              0.6089                       0.4211                       0.4091                  0.2563                  0.2990                        0.5648                            0.8322                  0.3921       0.8379                                                0.5447     0.3951   0.5171               0.5767                      0.5129                               2.5238                               2.3705                          4.1316                          3.5912                                2.1413                                    1.2280                          0.4639               1.2584                                                        0.4995             2.8269           1.8437    0.2673    0.2743   0.5171           1.8437
          smote logistic_regression        0.1651               0.1562                        0.4808                        0.4562                   0.3748                   0.3447                         0.4043                             0.1463                   0.4885        0.1581                                                 0.2327      0.4095    0.3181        0.1702               0.1987                        0.4671                        0.4349                   0.3583                   0.3258                         0.3806                             0.1410                   0.4822        0.1784                                                 0.2750      0.3873    0.3166       0.6709              0.6310                       0.3718                       0.4163                  0.4949                  0.5154                        0.4193                            0.7247                  0.3789       0.6872                                                0.5254     0.3999   0.5197               0.7500                      1.4901                               0.4967                               0.5322                          0.6227                          0.6358                                0.5309                                    0.7989                          1.9444               0.7408                                                        1.7043             0.5138           0.8967    0.3181    0.3166   0.5197           0.8967
          ctgan             xgboost        0.0012               0.2630                        0.2044                        0.2011                   0.2117                   0.1860                         0.1964                             0.0684                   0.1057        0.0216                                                 0.0970      0.2075    0.1470        0.0051               0.3860                        0.2082                        0.2043                   0.2217                   0.1798                         0.2284                             0.0726                   0.1005        0.0298                                                 0.1264      0.2494    0.1677       0.9975              0.4380                       0.6656                       0.6776                  0.6724                  0.7007                        0.6718                            0.8676                  0.8057       0.9545                                                0.8036     0.6526   0.7423               0.9901                      3.8562                               0.6742                               0.6884                          0.6792                          0.7268                                0.6446                                    0.9220                          1.2088               1.0193                                                        1.3011             0.6117           1.1102    0.1470    0.1677   0.7423           1.1102
           tvae             xgboost        0.0617               0.0627                        0.6060                        0.5145                   0.5597                   0.5621                         0.5099                             0.2806                   0.4230        0.1167                                                 0.2039      0.5942    0.3746        0.0832               0.2160                        0.5881                        0.4941                   0.5476                   0.5500                         0.5222                             0.2804                   0.4196        0.1273                                                 0.2696      0.5996    0.3915       0.8187              0.7985                       0.1853                       0.2820                  0.2907                  0.2822                        0.2239                            0.4615                  0.3248       0.6867                                                0.4501     0.1376   0.4118               0.8407                      1.7993                               0.2905                               0.4086                          0.4235                          0.4142                                0.3229                                    0.5884                          2.2571               0.7666                                                        1.9746             0.2363           0.8602    0.3746    0.3915   0.4118           0.8602
gaussian_copula             xgboost        0.0811               0.1638                        0.2914                        0.2479                   0.2925                   0.2449                         0.2190                             0.1292                   0.0725        0.0666                                                 0.1233      0.2623    0.1829        0.0855               0.2174                        0.3060                        0.2430                   0.2875                   0.2541                         0.2498                             0.1322                   0.0598        0.0687                                                 0.1392      0.2739    0.1931       0.8602              0.6982                       0.5329                       0.5819                  0.4985                  0.5776                        0.6415                            0.7745                  0.8703       0.8836                                                0.8036     0.5876   0.6925               0.8434                      1.8937                               2.0968                               1.8278                          2.2363                          1.9714                                1.7783                                    1.3619                          0.8754               1.0910                                                        0.7538             1.8535           1.5486    0.1829    0.1931   0.6925           1.5486
          smote             xgboost        0.0548               0.0029                        0.0910                        0.0549                   0.0107                   0.0790                         0.1330                             0.2305                   0.2321        0.0805                                                 0.0587      0.1945    0.1019        0.0684               0.1459                        0.1485                        0.1297                   0.1168                   0.1505                         0.1781                             0.2669                   0.3295        0.1560                                                 0.1097      0.2417    0.1701       0.8820              0.9934                       0.8039                       0.8779                  0.9757                  0.8246                        0.7233                            0.5349                  0.6204       0.8326                                                0.8712     0.6176   0.7965               0.8657                      0.7653                               0.9824                               0.8705                          0.7947                          0.9039                                1.1313                                    1.3976                          1.9170               0.7177                                                        1.2791             1.2712           1.0747    0.1019    0.1701   0.7965           1.0747
          ctgan                 mlp        0.0000               0.0001                        0.0002                        0.0002                   0.0004                   0.0009                         0.0001                             0.0002                   0.0002        0.0003                                                 0.0002      0.0004    0.0003        0.0005               0.0003                        0.0005                        0.0009                   0.0007                   0.0013                         0.0006                             0.0010                   0.0004        0.0005                                                 0.0004      0.0006    0.0006       0.9424              0.0000                       0.0000                       0.2667                  0.1694                  0.0000                        0.4714                            0.3323                  0.0000       0.0000                                                0.0000     0.0000   0.1819               0.0000                         NaN                                  NaN                               0.0000                             NaN                          0.0000                                0.0000                                    0.0000                          0.0000               0.0000                                                           NaN             0.0000           0.0000    0.0003    0.0006   0.1819           0.0000

In [21]:
# Per-attribute fairness bar charts
for metric in ["dpd", "eod", "di"]:
    if f"mean_{metric}" in results_df.columns:
        fig = plot_fairness_bar(results_df, f"mean_{metric}", cfg, save=True)
        plt.show()

2026-07-25 02:24:42 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\fairness_mean_dpd.png

2026-07-25 02:24:43 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\fairness_mean_eod.png

2026-07-25 02:24:43 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\fairness_mean_di.png

In [22]:
# Per-attribute breakdown (one chart per attr × metric)
for attr in PROTECTED_COLS:
    attr_rows = []
    for method in [BASELINE] + list(synthetic_data.keys()):
        sub = results_df[results_df["method"] == method]
        if sub.empty:
            continue
        for metric in ("dpd", "eod", "di"):
            col = f"{attr}_{metric}"
            if col in sub.columns:
                attr_rows.append({
                    "attribute": f"{method}",
                    metric: sub[col].mean(),   # mean across classifiers
                })
    if not attr_rows:
        continue
    attr_df = pd.DataFrame(attr_rows).groupby("attribute").mean().reset_index()

    for metric in ("dpd", "eod", "di"):
        if metric not in attr_df.columns:
            continue
        fig = plot_per_attribute_fairness(
            attr_df, metric, cfg,
            title=f"{metric.upper()} — {attr} (mean across classifiers)",
            filename_suffix=f"_{attr}_{metric}",
            save=True,
        )
        plt.show()

2026-07-25 02:24:43 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_s_gender_dpd.png

2026-07-25 02:24:43 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_s_gender_eod.png

2026-07-25 02:24:43 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_s_gender_di.png

2026-07-25 02:24:44 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_s_birth_country_dpd.png

2026-07-25 02:24:44 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_s_birth_country_eod.png

2026-07-25 02:24:44 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_s_birth_country_di.png

2026-07-25 02:24:44 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_mother_education_level_dpd.png

2026-07-25 02:24:44 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_mother_education_level_eod.png

2026-07-25 02:24:45 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_mother_education_level_di.png

2026-07-25 02:24:45 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_father_education_level_dpd.png

2026-07-25 02:24:45 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_father_education_level_eod.png

2026-07-25 02:24:45 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_father_education_level_di.png

2026-07-25 02:24:45 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_mother_occupation_dpd.png

2026-07-25 02:24:45 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_mother_occupation_eod.png

2026-07-25 02:24:46 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_mother_occupation_di.png

2026-07-25 02:24:46 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_father_occupation_dpd.png

2026-07-25 02:24:46 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_father_occupation_eod.png

2026-07-25 02:24:46 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_father_occupation_di.png

2026-07-25 02:24:46 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_extent_of_books_at_home_dpd.png

2026-07-25 02:24:46 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_extent_of_books_at_home_eod.png

2026-07-25 02:24:47 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_extent_of_books_at_home_di.png

2026-07-25 02:24:47 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_frequency_of_see_adult_read_dpd.png

2026-07-25 02:24:47 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_frequency_of_see_adult_read_eod.png

2026-07-25 02:24:47 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_frequency_of_see_adult_read_di.png

2026-07-25 02:24:47 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_p_public_or_private_dpd.png

2026-07-25 02:24:47 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_p_public_or_private_eod.png

2026-07-25 02:24:48 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_p_public_or_private_di.png

2026-07-25 02:24:48 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_p_island_dpd.png

2026-07-25 02:24:48 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_p_island_eod.png

2026-07-25 02:24:48 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_p_island_di.png

2026-07-25 02:24:48 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_p_percentage_of_teachers_changed_school_last_year_dpd.png

2026-07-25 02:24:49 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_p_percentage_of_teachers_changed_school_last_year_eod.png

2026-07-25 02:24:49 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_p_percentage_of_teachers_changed_school_last_year_di.png

2026-07-25 02:24:49 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_dpd_f_ESCS_dpd.png

2026-07-25 02:24:49 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_eod_f_ESCS_eod.png

2026-07-25 02:24:49 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\per_attr_di_f_ESCS_di.png

### Delta heatmaps

The heatmaps below show how each synthetic generator shifts utility and fairness
**relative to the real-data baseline**. Red = degradation relative to real; blue = improvement.

- For utility metrics (BA, F1, AUC): positive delta means the real model was better
  (i.e. synthetic training hurt). Red cells = utility loss.
- For fairness metrics (`delta_mean_dpd`, `delta_mean_eod`, `delta_mean_di`, from
  `src.evaluation.delta.compute_delta_matrix`): any non-zero value means the synthetic
  generator altered the fairness profile of the model relative to real data.

In [23]:
# Utility delta heatmap
delta_utility_cols = ["delta_balanced_accuracy", "delta_f1_macro", "delta_roc_auc"]
delta_utility_cols = [c for c in delta_utility_cols if c in results_df.columns]

if delta_utility_cols:
    fig = plot_delta_heatmap(
        results_df[results_df["method"] != BASELINE],
        delta_utility_cols,
        filename_suffix="utility",
        cfg=cfg,
        title="Utility delta: synthetic vs. real baseline (↑ red = worse)",
        save=True,
    )
    plt.show()

2026-07-25 02:24:50 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\delta_heatmap_utility.png

In [24]:
# Fairness delta heatmap (relative to real baseline, per classifier)
delta_df = compute_delta_matrix(results_df, cfg)
fairness_delta_cols = get_fairness_delta_columns(delta_df)

if fairness_delta_cols:
    fig = plot_delta_heatmap(
        delta_df[delta_df["method"] != BASELINE],
        fairness_delta_cols,
        filename_suffix="fairness",
        cfg=cfg,
        title="Fairness delta: synthetic vs. real baseline (per protected-attribute mean)",
        save=True,
    )
    plt.show()
else:
    print("No fairness delta columns found — check that protected attrs were set correctly.")

2026-07-25 02:24:50 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\delta_heatmap_fairness.png

In [25]:
# Utility vs. fairness scatter (the key trade-off plot for the report)
if "mean_dpd" in results_df.columns:
    fig = plot_utility_fairness_scatter(
        results_df,
        utility_col  = "delta_balanced_accuracy",
        fairness_col = "mean_dpd",
        cfg          = cfg,
        save         = True,
    )
    plt.show()
    print("Points close to (0, 0) are Pareto-optimal: no utility loss, no fairness shift.")

2026-07-25 02:24:50 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf\scatter_utility_vs_fairness.png

Points close to (0, 0) are Pareto-optimal: no utility loss, no fairness shift.

## 8 · Fairness Mitigation

Everything above measures fairness on classifiers trained *without* any
mitigation. This section retrains/post-processes each `(method, classifier)`
combination **with** a mitigation technique applied against **one protected
attribute at a time** (`PROTECTED_COLS`), still under the same TSTR setup:
train on real or synthetic data, score against the fixed real test set.

Two independent techniques (`src/evaluation/mitigation.py`, driven by
`MitigatedEvaluator`):

| Technique | Type | Scope | How it works |
|---|---|---|---|
| **Equalized odds** | Post-processing | Wraps any of the 3 classifiers | [fairlearn](https://fairlearn.org/) `ThresholdOptimizer` picks group-aware decision thresholds, after normal training, to equalize TPR/FPR across the two groups of the target attribute. |
| **Prejudice remover** | In-processing | Its own model (classifier-agnostic) | [aif360](https://aif360.res.ibm.com/) `PrejudiceRemover` (Kamishima et al., 2012) — a regularised logistic-regression-style model whose loss directly penalises mutual information between predictions and the sensitive attribute. |

Both use the same group definition that `fairness.py` uses to *measure*
DPD/EOD/DI (median-split / direct binary mapping), so "mitigated for attribute
X" and "X's fairness metrics" always refer to the same grouping.

Fully **revertible**: set `mitigation.enabled: false` in `config.yaml` to skip
this entire section (the rest of the notebook is unaffected). `mitigation.methods`
lets you run only one of the two techniques; `equalized_odds.grid_size` and
`prejudice_remover.eta` control technique-specific trade-offs.

> **Note on AUC/Brier for mitigated rows:** equalized-odds predictions are
> hard 0/1 labels (no calibrated probability), so `roc_auc`/`brier_score` on
> those rows are computed from the hard label itself — a coarser score than
> the unmitigated rows. Prejudice Remover does expose a real probability, so
> its AUC/Brier are directly comparable to the unmitigated baseline.

In [26]:
mitigation_cfg = cfg.get("mitigation", {})
mitigation_rows = []
mitigation_path = cfg["paths"]["results_dir"] / "goal3_mitigation_results.csv"
mitigation_path.parent.mkdir(parents=True, exist_ok=True)

if mitigation_cfg.get("enabled", False) and PROTECTED_COLS:
    mitigated_evaluator = MitigatedEvaluator(split, cfg)
    techniques = mitigation_cfg.get("methods", ["equalized_odds", "prejudice_remover"])

    # Same "method" axis as the unmitigated TSTR loop: real baseline + every
    # loaded synthetic generator, all trained against the fixed real test set.
    # Each source carries its OWN protected-attribute values (3rd tuple elem)
    # -- a synthetic training set can have a different row count than the real
    # training set (e.g. SMOTE's class-balanced output), so split.protected_train
    # can't be reused for those rows.
    train_sources = {
        BASELINE: (split.X_train, split.y_train, split.protected_train),
        **synthetic_data,
    }

    n_eo = len(CLASSIFIERS) if "equalized_odds" in techniques else 0
    n_pr = 1 if "prejudice_remover" in techniques else 0
    logger.info(
        f"Mitigation loop: {len(PROTECTED_COLS)} attrs x {len(train_sources)} methods x "
        f"({n_eo} EO classifiers + {n_pr} PR model) = "
        f"{len(PROTECTED_COLS) * len(train_sources) * (n_eo + n_pr)} fits"
    )

    # A sensitive-attribute subgroup can end up with zero label variance in a
    # synthetic training set -- SMOTE only interpolates within the minority
    # class, so if one subgroup had few/no minority-class rows to begin with,
    # it can come out of resampling 100% one label. Neither ThresholdOptimizer
    # nor PrejudiceRemover can fit a fairness constraint against a group with
    # no label variance, so this is a real, reportable failure mode (same
    # spirit as the TVAE minority-collapse discussion in Notebook 02), not a
    # bug to hide -- we record it as a NaN/flagged row and keep going, rather
    # than let one degenerate combination discard the whole (many-minute) run.
    for attr in PROTECTED_COLS:
        for method, (X_tr, y_tr, protected_tr) in train_sources.items():
            attr_train = protected_tr[attr]
            if "equalized_odds" in techniques:
                for clf_name in CLASSIFIERS:
                    try:
                        row = mitigated_evaluator.evaluate(
                            X_tr, y_tr,
                            technique      = "equalized_odds",
                            target_attr    = attr,
                            method_name    = method,
                            attr_train     = attr_train,
                            classifier_name= clf_name,
                        )
                    except ValueError as e:
                        logger.warning(f"  [EO | {attr} | {method} | {clf_name}]  SKIPPED — {e}")
                        row = {
                            "technique": "equalized_odds", "target_attr": attr,
                            "method": method, "classifier": clf_name,
                            "balanced_accuracy": float("nan"), "error": str(e),
                        }
                    mitigation_rows.append(row)
                    print(f"  [EO | {attr} | {method} | {clf_name}]  "
                          f"BA={row['balanced_accuracy']:.4f}  mean_DPD={row.get('mean_dpd', float('nan')):.4f}")

            if "prejudice_remover" in techniques:
                try:
                    row = mitigated_evaluator.evaluate(
                        X_tr, y_tr,
                        technique  = "prejudice_remover",
                        target_attr= attr,
                        method_name= method,
                        attr_train = attr_train,
                    )
                except ValueError as e:
                    logger.warning(f"  [PR | {attr} | {method}]  SKIPPED — {e}")
                    row = {
                        "technique": "prejudice_remover", "target_attr": attr,
                        "method": method, "classifier": "prejudice_remover",
                        "balanced_accuracy": float("nan"), "error": str(e),
                    }
                mitigation_rows.append(row)
                print(f"  [PR | {attr} | {method}]  "
                      f"BA={row['balanced_accuracy']:.4f}  mean_DPD={row.get('mean_dpd', float('nan')):.4f}")

            # Checkpoint after every (attr, method) pair so a later failure
            # never discards fits that already completed.
            pd.DataFrame(mitigation_rows).to_csv(mitigation_path, index=False)

    mitigation_df = pd.DataFrame(mitigation_rows)
    mitigation_df.to_csv(mitigation_path, index=False)
    n_failed = mitigation_df["error"].notna().sum() if "error" in mitigation_df.columns else 0
    print(f"\nMitigation results saved → {mitigation_path}")
    print(f"Shape: {mitigation_df.shape}  ({n_failed} degenerate/skipped fits, if any)")
else:
    mitigation_df = pd.DataFrame()
    print("Mitigation section disabled or no protected attributes present "
          "(mitigation.enabled: false, or PROTECTED_COLS is empty) — skipping.")

mitigation_df.head(10)

2026-07-25 02:24:51 | INFO     | notebook_03 | Mitigation loop: 12 attrs x 5 methods x (3 EO classifiers + 1 PR model) = 240 fits

2026-07-25 02:24:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | real | logistic_regression] BA=0.6218 | mean_dpd=0.3196

  [EO | s_gender | real | logistic_regression]  BA=0.6218  mean_DPD=0.3196

2026-07-25 02:24:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | real | xgboost] BA=0.6532 | mean_dpd=0.3372

  [EO | s_gender | real | xgboost]  BA=0.6532  mean_DPD=0.3372

2026-07-25 02:25:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | real | mlp] BA=0.6370 | mean_dpd=0.3060

WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'

WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'

WARNING:root:No module named 'inFairness': SenSeI and SenSR will be unavailable. To install, run:
pip install 'aif360[inFairness]'

  [EO | s_gender | real | mlp]  BA=0.6370  mean_DPD=0.3060

2026-07-25 02:26:21 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | real | prejudice_remover] BA=0.5386 | mean_dpd=0.1002

  [PR | s_gender | real]  BA=0.5386  mean_DPD=0.1002

2026-07-25 02:26:22 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | ctgan | logistic_regression] BA=0.5575 | mean_dpd=0.1628

  [EO | s_gender | ctgan | logistic_regression]  BA=0.5575  mean_DPD=0.1628

2026-07-25 02:26:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | ctgan | xgboost] BA=0.5324 | mean_dpd=0.1298

  [EO | s_gender | ctgan | xgboost]  BA=0.5324  mean_DPD=0.1298

2026-07-25 02:26:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | ctgan | mlp] BA=0.5275 | mean_dpd=0.1295

  [EO | s_gender | ctgan | mlp]  BA=0.5275  mean_DPD=0.1295

2026-07-25 02:27:51 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | ctgan | prejudice_remover] BA=0.5002 | mean_dpd=0.0019

  [PR | s_gender | ctgan]  BA=0.5002  mean_DPD=0.0019

2026-07-25 02:27:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | tvae | logistic_regression] BA=0.6087 | mean_dpd=0.3531

  [EO | s_gender | tvae | logistic_regression]  BA=0.6087  mean_DPD=0.3531

2026-07-25 02:27:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | tvae | xgboost] BA=0.6109 | mean_dpd=0.3636

  [EO | s_gender | tvae | xgboost]  BA=0.6109  mean_DPD=0.3636

2026-07-25 02:28:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | tvae | mlp] BA=0.6094 | mean_dpd=0.3508

  [EO | s_gender | tvae | mlp]  BA=0.6094  mean_DPD=0.3508

2026-07-25 02:29:49 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | tvae | prejudice_remover] BA=0.5645 | mean_dpd=0.2483

  [PR | s_gender | tvae]  BA=0.5645  mean_DPD=0.2483

2026-07-25 02:29:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | gaussian_copula | logistic_regression] BA=0.4230 | mean_dpd=0.2646

  [EO | s_gender | gaussian_copula | logistic_regression]  BA=0.4230  mean_DPD=0.2646

2026-07-25 02:29:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | gaussian_copula | xgboost] BA=0.4415 | mean_dpd=0.1794

  [EO | s_gender | gaussian_copula | xgboost]  BA=0.4415  mean_DPD=0.1794

2026-07-25 02:30:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | gaussian_copula | mlp] BA=0.4671 | mean_dpd=0.1705

  [EO | s_gender | gaussian_copula | mlp]  BA=0.4671  mean_DPD=0.1705

2026-07-25 02:30:48 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | s_gender | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 02:30:49 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | smote | logistic_regression] BA=0.6141 | mean_dpd=0.2820

  [EO | s_gender | smote | logistic_regression]  BA=0.6141  mean_DPD=0.2820

2026-07-25 02:30:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | smote | xgboost] BA=0.5206 | mean_dpd=0.1079

  [EO | s_gender | smote | xgboost]  BA=0.5206  mean_DPD=0.1079

2026-07-25 02:31:27 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | smote | mlp] BA=0.5928 | mean_dpd=0.1216

  [EO | s_gender | smote | mlp]  BA=0.5928  mean_DPD=0.1216

2026-07-25 02:33:04 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | smote | prejudice_remover] BA=0.6227 | mean_dpd=0.3106

  [PR | s_gender | smote]  BA=0.6227  mean_DPD=0.3106

2026-07-25 02:33:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | real | logistic_regression] BA=0.6237 | mean_dpd=0.3237

  [EO | s_birth_country | real | logistic_regression]  BA=0.6237  mean_DPD=0.3237

2026-07-25 02:33:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | real | xgboost] BA=0.6550 | mean_dpd=0.3424

  [EO | s_birth_country | real | xgboost]  BA=0.6550  mean_DPD=0.3424

2026-07-25 02:33:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | real | mlp] BA=0.6377 | mean_dpd=0.2972

  [EO | s_birth_country | real | mlp]  BA=0.6377  mean_DPD=0.2972

2026-07-25 02:34:32 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | real | prejudice_remover] BA=0.5384 | mean_dpd=0.1046

  [PR | s_birth_country | real]  BA=0.5384  mean_DPD=0.1046

2026-07-25 02:34:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | ctgan | logistic_regression] BA=0.5361 | mean_dpd=0.0893

  [EO | s_birth_country | ctgan | logistic_regression]  BA=0.5361  mean_DPD=0.0893

2026-07-25 02:34:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | ctgan | xgboost] BA=0.5352 | mean_dpd=0.1300

  [EO | s_birth_country | ctgan | xgboost]  BA=0.5352  mean_DPD=0.1300

2026-07-25 02:34:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | ctgan | mlp] BA=0.5177 | mean_dpd=0.0840

  [EO | s_birth_country | ctgan | mlp]  BA=0.5177  mean_DPD=0.0840

2026-07-25 02:35:40 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | ctgan | prejudice_remover] BA=0.5000 | mean_dpd=0.0045

  [PR | s_birth_country | ctgan]  BA=0.5000  mean_DPD=0.0045

2026-07-25 02:35:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | tvae | logistic_regression] BA=0.6079 | mean_dpd=0.3657

  [EO | s_birth_country | tvae | logistic_regression]  BA=0.6079  mean_DPD=0.3657

2026-07-25 02:35:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | tvae | xgboost] BA=0.6152 | mean_dpd=0.3694

  [EO | s_birth_country | tvae | xgboost]  BA=0.6152  mean_DPD=0.3694

2026-07-25 02:35:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | tvae | mlp] BA=0.6164 | mean_dpd=0.3629

  [EO | s_birth_country | tvae | mlp]  BA=0.6164  mean_DPD=0.3629

2026-07-25 02:36:54 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | tvae | prejudice_remover] BA=0.5680 | mean_dpd=0.2541

  [PR | s_birth_country | tvae]  BA=0.5680  mean_DPD=0.2541

2026-07-25 02:36:55 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | gaussian_copula | logistic_regression] BA=0.4297 | mean_dpd=0.2617

  [EO | s_birth_country | gaussian_copula | logistic_regression]  BA=0.4297  mean_DPD=0.2617

2026-07-25 02:36:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | gaussian_copula | xgboost] BA=0.4476 | mean_dpd=0.1690

  [EO | s_birth_country | gaussian_copula | xgboost]  BA=0.4476  mean_DPD=0.1690

2026-07-25 02:37:06 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | gaussian_copula | mlp] BA=0.4738 | mean_dpd=0.1485

  [EO | s_birth_country | gaussian_copula | mlp]  BA=0.4738  mean_DPD=0.1485

2026-07-25 02:38:00 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | gaussian_copula | prejudice_remover] BA=0.5001 | mean_dpd=0.0037

  [PR | s_birth_country | gaussian_copula]  BA=0.5001  mean_DPD=0.0037

2026-07-25 02:38:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | smote | logistic_regression] BA=0.6203 | mean_dpd=0.3148

  [EO | s_birth_country | smote | logistic_regression]  BA=0.6203  mean_DPD=0.3148

2026-07-25 02:38:04 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | smote | xgboost] BA=0.5255 | mean_dpd=0.1056

  [EO | s_birth_country | smote | xgboost]  BA=0.5255  mean_DPD=0.1056

2026-07-25 02:38:39 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | smote | mlp] BA=0.5876 | mean_dpd=0.1238

  [EO | s_birth_country | smote | mlp]  BA=0.5876  mean_DPD=0.1238

2026-07-25 02:40:17 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | smote | prejudice_remover] BA=0.6197 | mean_dpd=0.3256

  [PR | s_birth_country | smote]  BA=0.6197  mean_DPD=0.3256

2026-07-25 02:40:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | real | logistic_regression] BA=0.5977 | mean_dpd=0.1898

  [EO | f_mother_education_level | real | logistic_regression]  BA=0.5977  mean_DPD=0.1898

2026-07-25 02:40:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | real | xgboost] BA=0.6318 | mean_dpd=0.2074

  [EO | f_mother_education_level | real | xgboost]  BA=0.6318  mean_DPD=0.2074

2026-07-25 02:40:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | real | mlp] BA=0.6157 | mean_dpd=0.1803

  [EO | f_mother_education_level | real | mlp]  BA=0.6157  mean_DPD=0.1803

2026-07-25 02:41:32 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | real | prejudice_remover] BA=0.5203 | mean_dpd=0.0458

  [PR | f_mother_education_level | real]  BA=0.5203  mean_DPD=0.0458

2026-07-25 02:41:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | ctgan | logistic_regression] BA=0.5267 | mean_dpd=0.0965

  [EO | f_mother_education_level | ctgan | logistic_regression]  BA=0.5267  mean_DPD=0.0965

2026-07-25 02:41:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | ctgan | xgboost] BA=0.5098 | mean_dpd=0.0646

  [EO | f_mother_education_level | ctgan | xgboost]  BA=0.5098  mean_DPD=0.0646

2026-07-25 02:41:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | ctgan | mlp] BA=0.5152 | mean_dpd=0.0725

  [EO | f_mother_education_level | ctgan | mlp]  BA=0.5152  mean_DPD=0.0725

2026-07-25 02:42:53 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | ctgan | prejudice_remover] BA=0.5000 | mean_dpd=0.0003

  [PR | f_mother_education_level | ctgan]  BA=0.5000  mean_DPD=0.0003

2026-07-25 02:42:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | tvae | logistic_regression] BA=0.5783 | mean_dpd=0.2334

  [EO | f_mother_education_level | tvae | logistic_regression]  BA=0.5783  mean_DPD=0.2334

2026-07-25 02:42:56 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | tvae | xgboost] BA=0.5979 | mean_dpd=0.2793

  [EO | f_mother_education_level | tvae | xgboost]  BA=0.5979  mean_DPD=0.2793

2026-07-25 02:43:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | tvae | mlp] BA=0.5899 | mean_dpd=0.2711

  [EO | f_mother_education_level | tvae | mlp]  BA=0.5899  mean_DPD=0.2711

2026-07-25 02:44:20 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | tvae | prejudice_remover] BA=0.5561 | mean_dpd=0.2140

  [PR | f_mother_education_level | tvae]  BA=0.5561  mean_DPD=0.2140

2026-07-25 02:44:21 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | gaussian_copula | logistic_regression] BA=0.4404 | mean_dpd=0.2283

  [EO | f_mother_education_level | gaussian_copula | logistic_regression]  BA=0.4404  mean_DPD=0.2283

2026-07-25 02:44:23 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | gaussian_copula | xgboost] BA=0.4590 | mean_dpd=0.1364

  [EO | f_mother_education_level | gaussian_copula | xgboost]  BA=0.4590  mean_DPD=0.1364

2026-07-25 02:44:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | gaussian_copula | mlp] BA=0.4715 | mean_dpd=0.1347

  [EO | f_mother_education_level | gaussian_copula | mlp]  BA=0.4715  mean_DPD=0.1347

2026-07-25 02:45:31 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_mother_education_level | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 02:45:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | smote | logistic_regression] BA=0.5821 | mean_dpd=0.1604

  [EO | f_mother_education_level | smote | logistic_regression]  BA=0.5821  mean_DPD=0.1604

2026-07-25 02:45:36 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | smote | xgboost] BA=0.5132 | mean_dpd=0.1545

  [EO | f_mother_education_level | smote | xgboost]  BA=0.5132  mean_DPD=0.1545

2026-07-25 02:46:10 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | smote | mlp] BA=0.5696 | mean_dpd=0.0746

  [EO | f_mother_education_level | smote | mlp]  BA=0.5696  mean_DPD=0.0746

2026-07-25 02:47:24 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | smote | prejudice_remover] BA=0.6108 | mean_dpd=0.2596

  [PR | f_mother_education_level | smote]  BA=0.6108  mean_DPD=0.2596

2026-07-25 02:47:25 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | real | logistic_regression] BA=0.5959 | mean_dpd=0.2032

  [EO | f_father_education_level | real | logistic_regression]  BA=0.5959  mean_DPD=0.2032

2026-07-25 02:47:27 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | real | xgboost] BA=0.6309 | mean_dpd=0.2307

  [EO | f_father_education_level | real | xgboost]  BA=0.6309  mean_DPD=0.2307

2026-07-25 02:47:39 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | real | mlp] BA=0.6125 | mean_dpd=0.1975

  [EO | f_father_education_level | real | mlp]  BA=0.6125  mean_DPD=0.1975

2026-07-25 02:48:22 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | real | prejudice_remover] BA=0.5219 | mean_dpd=0.0488

  [PR | f_father_education_level | real]  BA=0.5219  mean_DPD=0.0488

2026-07-25 02:48:23 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | ctgan | logistic_regression] BA=0.5502 | mean_dpd=0.1477

  [EO | f_father_education_level | ctgan | logistic_regression]  BA=0.5502  mean_DPD=0.1477

2026-07-25 02:48:25 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | ctgan | xgboost] BA=0.5211 | mean_dpd=0.0970

  [EO | f_father_education_level | ctgan | xgboost]  BA=0.5211  mean_DPD=0.0970

2026-07-25 02:48:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | ctgan | mlp] BA=0.5256 | mean_dpd=0.1100

  [EO | f_father_education_level | ctgan | mlp]  BA=0.5256  mean_DPD=0.1100

2026-07-25 02:49:14 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | ctgan | prejudice_remover] BA=0.4997 | mean_dpd=0.0008

  [PR | f_father_education_level | ctgan]  BA=0.4997  mean_DPD=0.0008

2026-07-25 02:49:16 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | tvae | logistic_regression] BA=0.6082 | mean_dpd=0.3381

  [EO | f_father_education_level | tvae | logistic_regression]  BA=0.6082  mean_DPD=0.3381

2026-07-25 02:49:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | tvae | xgboost] BA=0.6141 | mean_dpd=0.3319

  [EO | f_father_education_level | tvae | xgboost]  BA=0.6141  mean_DPD=0.3319

2026-07-25 02:49:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | tvae | mlp] BA=0.6062 | mean_dpd=0.3244

  [EO | f_father_education_level | tvae | mlp]  BA=0.6062  mean_DPD=0.3244

2026-07-25 02:50:18 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | tvae | prejudice_remover] BA=0.5639 | mean_dpd=0.2429

  [PR | f_father_education_level | tvae]  BA=0.5639  mean_DPD=0.2429

2026-07-25 02:50:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | gaussian_copula | logistic_regression] BA=0.4336 | mean_dpd=0.2561

  [EO | f_father_education_level | gaussian_copula | logistic_regression]  BA=0.4336  mean_DPD=0.2561

2026-07-25 02:50:21 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | gaussian_copula | xgboost] BA=0.4499 | mean_dpd=0.1650

  [EO | f_father_education_level | gaussian_copula | xgboost]  BA=0.4499  mean_DPD=0.1650

2026-07-25 02:50:29 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | gaussian_copula | mlp] BA=0.4729 | mean_dpd=0.1650

  [EO | f_father_education_level | gaussian_copula | mlp]  BA=0.4729  mean_DPD=0.1650

2026-07-25 02:51:56 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_father_education_level | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 02:51:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | smote | logistic_regression] BA=0.5819 | mean_dpd=0.1668

  [EO | f_father_education_level | smote | logistic_regression]  BA=0.5819  mean_DPD=0.1668

2026-07-25 02:52:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | smote | xgboost] BA=0.5081 | mean_dpd=0.1627

  [EO | f_father_education_level | smote | xgboost]  BA=0.5081  mean_DPD=0.1627

2026-07-25 02:52:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | smote | mlp] BA=0.5771 | mean_dpd=0.0721

  [EO | f_father_education_level | smote | mlp]  BA=0.5771  mean_DPD=0.0721

2026-07-25 02:53:36 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | smote | prejudice_remover] BA=0.6154 | mean_dpd=0.2971

  [PR | f_father_education_level | smote]  BA=0.6154  mean_DPD=0.2971

2026-07-25 02:53:37 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | real | logistic_regression] BA=0.6098 | mean_dpd=0.2381

  [EO | f_mother_occupation | real | logistic_regression]  BA=0.6098  mean_DPD=0.2381

2026-07-25 02:53:39 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | real | xgboost] BA=0.6464 | mean_dpd=0.2618

  [EO | f_mother_occupation | real | xgboost]  BA=0.6464  mean_DPD=0.2618

2026-07-25 02:53:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | real | mlp] BA=0.6274 | mean_dpd=0.2296

  [EO | f_mother_occupation | real | mlp]  BA=0.6274  mean_DPD=0.2296

2026-07-25 02:54:57 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | real | prejudice_remover] BA=0.5233 | mean_dpd=0.0513

  [PR | f_mother_occupation | real]  BA=0.5233  mean_DPD=0.0513

2026-07-25 02:54:58 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | ctgan | logistic_regression] BA=0.5450 | mean_dpd=0.1312

  [EO | f_mother_occupation | ctgan | logistic_regression]  BA=0.5450  mean_DPD=0.1312

2026-07-25 02:55:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | ctgan | xgboost] BA=0.5280 | mean_dpd=0.0800

  [EO | f_mother_occupation | ctgan | xgboost]  BA=0.5280  mean_DPD=0.0800

2026-07-25 02:55:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | ctgan | mlp] BA=0.5263 | mean_dpd=0.1020

  [EO | f_mother_occupation | ctgan | mlp]  BA=0.5263  mean_DPD=0.1020

2026-07-25 02:55:53 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | ctgan | prejudice_remover] BA=0.5003 | mean_dpd=0.0020

  [PR | f_mother_occupation | ctgan]  BA=0.5003  mean_DPD=0.0020

2026-07-25 02:55:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | tvae | logistic_regression] BA=0.5773 | mean_dpd=0.2220

  [EO | f_mother_occupation | tvae | logistic_regression]  BA=0.5773  mean_DPD=0.2220

2026-07-25 02:55:56 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | tvae | xgboost] BA=0.5860 | mean_dpd=0.2311

  [EO | f_mother_occupation | tvae | xgboost]  BA=0.5860  mean_DPD=0.2311

2026-07-25 02:56:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | tvae | mlp] BA=0.5922 | mean_dpd=0.2705

  [EO | f_mother_occupation | tvae | mlp]  BA=0.5922  mean_DPD=0.2705

2026-07-25 02:56:58 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | tvae | prejudice_remover] BA=0.5646 | mean_dpd=0.2423

  [PR | f_mother_occupation | tvae]  BA=0.5646  mean_DPD=0.2423

2026-07-25 02:56:59 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | gaussian_copula | logistic_regression] BA=0.4374 | mean_dpd=0.2393

  [EO | f_mother_occupation | gaussian_copula | logistic_regression]  BA=0.4374  mean_DPD=0.2393

2026-07-25 02:57:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | gaussian_copula | xgboost] BA=0.4464 | mean_dpd=0.1785

  [EO | f_mother_occupation | gaussian_copula | xgboost]  BA=0.4464  mean_DPD=0.1785

2026-07-25 02:57:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | gaussian_copula | mlp] BA=0.4742 | mean_dpd=0.1575

  [EO | f_mother_occupation | gaussian_copula | mlp]  BA=0.4742  mean_DPD=0.1575

2026-07-25 02:58:09 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_mother_occupation | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 02:58:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | smote | logistic_regression] BA=0.6075 | mean_dpd=0.2175

  [EO | f_mother_occupation | smote | logistic_regression]  BA=0.6075  mean_DPD=0.2175

2026-07-25 02:58:14 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | smote | xgboost] BA=0.5154 | mean_dpd=0.1611

  [EO | f_mother_occupation | smote | xgboost]  BA=0.5154  mean_DPD=0.1611

2026-07-25 02:58:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | smote | mlp] BA=0.5863 | mean_dpd=0.0970

  [EO | f_mother_occupation | smote | mlp]  BA=0.5863  mean_DPD=0.0970

2026-07-25 03:00:20 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | smote | prejudice_remover] BA=0.6200 | mean_dpd=0.2907

  [PR | f_mother_occupation | smote]  BA=0.6200  mean_DPD=0.2907

2026-07-25 03:00:21 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | real | logistic_regression] BA=0.6117 | mean_dpd=0.2424

  [EO | f_father_occupation | real | logistic_regression]  BA=0.6117  mean_DPD=0.2424

2026-07-25 03:00:23 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | real | xgboost] BA=0.6461 | mean_dpd=0.2661

  [EO | f_father_occupation | real | xgboost]  BA=0.6461  mean_DPD=0.2661

2026-07-25 03:00:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | real | mlp] BA=0.6263 | mean_dpd=0.2396

  [EO | f_father_occupation | real | mlp]  BA=0.6263  mean_DPD=0.2396

2026-07-25 03:01:41 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | real | prejudice_remover] BA=0.5253 | mean_dpd=0.0520

  [PR | f_father_occupation | real]  BA=0.5253  mean_DPD=0.0520

2026-07-25 03:01:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | ctgan | logistic_regression] BA=0.5331 | mean_dpd=0.0760

  [EO | f_father_occupation | ctgan | logistic_regression]  BA=0.5331  mean_DPD=0.0760

2026-07-25 03:01:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | ctgan | xgboost] BA=0.5201 | mean_dpd=0.0834

  [EO | f_father_occupation | ctgan | xgboost]  BA=0.5201  mean_DPD=0.0834

2026-07-25 03:01:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | ctgan | mlp] BA=0.5210 | mean_dpd=0.0856

  [EO | f_father_occupation | ctgan | mlp]  BA=0.5210  mean_DPD=0.0856

2026-07-25 03:03:00 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | ctgan | prejudice_remover] BA=0.5000 | mean_dpd=0.0015

  [PR | f_father_occupation | ctgan]  BA=0.5000  mean_DPD=0.0015

2026-07-25 03:03:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | tvae | logistic_regression] BA=0.5773 | mean_dpd=0.2099

  [EO | f_father_occupation | tvae | logistic_regression]  BA=0.5773  mean_DPD=0.2099

2026-07-25 03:03:04 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | tvae | xgboost] BA=0.5846 | mean_dpd=0.2053

  [EO | f_father_occupation | tvae | xgboost]  BA=0.5846  mean_DPD=0.2053

2026-07-25 03:03:16 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | tvae | mlp] BA=0.5831 | mean_dpd=0.2437

  [EO | f_father_occupation | tvae | mlp]  BA=0.5831  mean_DPD=0.2437

2026-07-25 03:04:23 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | tvae | prejudice_remover] BA=0.5596 | mean_dpd=0.1993

  [PR | f_father_occupation | tvae]  BA=0.5596  mean_DPD=0.1993

2026-07-25 03:04:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | gaussian_copula | logistic_regression] BA=0.4429 | mean_dpd=0.2466

  [EO | f_father_occupation | gaussian_copula | logistic_regression]  BA=0.4429  mean_DPD=0.2466

2026-07-25 03:04:26 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | gaussian_copula | xgboost] BA=0.4477 | mean_dpd=0.1751

  [EO | f_father_occupation | gaussian_copula | xgboost]  BA=0.4477  mean_DPD=0.1751

2026-07-25 03:04:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | gaussian_copula | mlp] BA=0.4734 | mean_dpd=0.1650

  [EO | f_father_occupation | gaussian_copula | mlp]  BA=0.4734  mean_DPD=0.1650

2026-07-25 03:05:30 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_father_occupation | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:05:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | smote | logistic_regression] BA=0.6018 | mean_dpd=0.2214

  [EO | f_father_occupation | smote | logistic_regression]  BA=0.6018  mean_DPD=0.2214

2026-07-25 03:05:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | smote | xgboost] BA=0.5186 | mean_dpd=0.1500

  [EO | f_father_occupation | smote | xgboost]  BA=0.5186  mean_DPD=0.1500

2026-07-25 03:06:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | smote | mlp] BA=0.5850 | mean_dpd=0.0912

  [EO | f_father_occupation | smote | mlp]  BA=0.5850  mean_DPD=0.0912

2026-07-25 03:07:16 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | smote | prejudice_remover] BA=0.6174 | mean_dpd=0.2901

  [PR | f_father_occupation | smote]  BA=0.6174  mean_DPD=0.2901

2026-07-25 03:07:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | real | logistic_regression] BA=0.6000 | mean_dpd=0.2121

  [EO | f_extent_of_books_at_home | real | logistic_regression]  BA=0.6000  mean_DPD=0.2121

2026-07-25 03:07:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | real | xgboost] BA=0.6270 | mean_dpd=0.2357

  [EO | f_extent_of_books_at_home | real | xgboost]  BA=0.6270  mean_DPD=0.2357

2026-07-25 03:07:30 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | real | mlp] BA=0.6144 | mean_dpd=0.2136

  [EO | f_extent_of_books_at_home | real | mlp]  BA=0.6144  mean_DPD=0.2136

2026-07-25 03:08:27 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | real | prejudice_remover] BA=0.5180 | mean_dpd=0.0439

  [PR | f_extent_of_books_at_home | real]  BA=0.5180  mean_DPD=0.0439

2026-07-25 03:08:28 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | ctgan | logistic_regression] BA=0.5461 | mean_dpd=0.1410

  [EO | f_extent_of_books_at_home | ctgan | logistic_regression]  BA=0.5461  mean_DPD=0.1410

2026-07-25 03:08:30 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | ctgan | xgboost] BA=0.5187 | mean_dpd=0.0886

  [EO | f_extent_of_books_at_home | ctgan | xgboost]  BA=0.5187  mean_DPD=0.0886

2026-07-25 03:08:40 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | ctgan | mlp] BA=0.5240 | mean_dpd=0.1030

  [EO | f_extent_of_books_at_home | ctgan | mlp]  BA=0.5240  mean_DPD=0.1030

2026-07-25 03:09:39 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | ctgan | prejudice_remover] BA=0.5001 | mean_dpd=0.0002

  [PR | f_extent_of_books_at_home | ctgan]  BA=0.5001  mean_DPD=0.0002

2026-07-25 03:09:40 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | tvae | logistic_regression] BA=0.5746 | mean_dpd=0.2380

  [EO | f_extent_of_books_at_home | tvae | logistic_regression]  BA=0.5746  mean_DPD=0.2380

2026-07-25 03:09:42 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | tvae | xgboost] BA=0.5831 | mean_dpd=0.2452

  [EO | f_extent_of_books_at_home | tvae | xgboost]  BA=0.5831  mean_DPD=0.2452

2026-07-25 03:09:55 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | tvae | mlp] BA=0.5843 | mean_dpd=0.2636

  [EO | f_extent_of_books_at_home | tvae | mlp]  BA=0.5843  mean_DPD=0.2636

2026-07-25 03:11:00 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | tvae | prejudice_remover] BA=0.5674 | mean_dpd=0.2575

  [PR | f_extent_of_books_at_home | tvae]  BA=0.5674  mean_DPD=0.2575

2026-07-25 03:11:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | gaussian_copula | logistic_regression] BA=0.4306 | mean_dpd=0.2655

  [EO | f_extent_of_books_at_home | gaussian_copula | logistic_regression]  BA=0.4306  mean_DPD=0.2655

2026-07-25 03:11:03 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | gaussian_copula | xgboost] BA=0.4458 | mean_dpd=0.1774

  [EO | f_extent_of_books_at_home | gaussian_copula | xgboost]  BA=0.4458  mean_DPD=0.1774

2026-07-25 03:11:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | gaussian_copula | mlp] BA=0.4737 | mean_dpd=0.1682

  [EO | f_extent_of_books_at_home | gaussian_copula | mlp]  BA=0.4737  mean_DPD=0.1682

2026-07-25 03:12:15 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_extent_of_books_at_home | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:12:16 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | smote | logistic_regression] BA=0.5825 | mean_dpd=0.1832

  [EO | f_extent_of_books_at_home | smote | logistic_regression]  BA=0.5825  mean_DPD=0.1832

2026-07-25 03:12:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | smote | xgboost] BA=0.5173 | mean_dpd=0.1359

  [EO | f_extent_of_books_at_home | smote | xgboost]  BA=0.5173  mean_DPD=0.1359

2026-07-25 03:12:55 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | smote | mlp] BA=0.5739 | mean_dpd=0.0826

  [EO | f_extent_of_books_at_home | smote | mlp]  BA=0.5739  mean_DPD=0.0826

2026-07-25 03:14:31 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | smote | prejudice_remover] BA=0.5981 | mean_dpd=0.2254

  [PR | f_extent_of_books_at_home | smote]  BA=0.5981  mean_DPD=0.2254

2026-07-25 03:14:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | real | logistic_regression] BA=0.6165 | mean_dpd=0.2850

  [EO | f_frequency_of_see_adult_read | real | logistic_regression]  BA=0.6165  mean_DPD=0.2850

2026-07-25 03:14:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | real | xgboost] BA=0.6502 | mean_dpd=0.2982

  [EO | f_frequency_of_see_adult_read | real | xgboost]  BA=0.6502  mean_DPD=0.2982

2026-07-25 03:14:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | real | mlp] BA=0.6303 | mean_dpd=0.2651

  [EO | f_frequency_of_see_adult_read | real | mlp]  BA=0.6303  mean_DPD=0.2651

2026-07-25 03:15:40 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | real | prejudice_remover] BA=0.5401 | mean_dpd=0.1015

  [PR | f_frequency_of_see_adult_read | real]  BA=0.5401  mean_DPD=0.1015

2026-07-25 03:15:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | ctgan | logistic_regression] BA=0.5561 | mean_dpd=0.1647

  [EO | f_frequency_of_see_adult_read | ctgan | logistic_regression]  BA=0.5561  mean_DPD=0.1647

2026-07-25 03:15:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | ctgan | xgboost] BA=0.5316 | mean_dpd=0.1251

  [EO | f_frequency_of_see_adult_read | ctgan | xgboost]  BA=0.5316  mean_DPD=0.1251

2026-07-25 03:15:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | ctgan | mlp] BA=0.5281 | mean_dpd=0.1173

  [EO | f_frequency_of_see_adult_read | ctgan | mlp]  BA=0.5281  mean_DPD=0.1173

2026-07-25 03:16:49 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | ctgan | prejudice_remover] BA=0.5001 | mean_dpd=0.0022

  [PR | f_frequency_of_see_adult_read | ctgan]  BA=0.5001  mean_DPD=0.0022

2026-07-25 03:16:51 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | tvae | logistic_regression] BA=0.6125 | mean_dpd=0.3385

  [EO | f_frequency_of_see_adult_read | tvae | logistic_regression]  BA=0.6125  mean_DPD=0.3385

2026-07-25 03:16:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | tvae | xgboost] BA=0.6134 | mean_dpd=0.3277

  [EO | f_frequency_of_see_adult_read | tvae | xgboost]  BA=0.6134  mean_DPD=0.3277

2026-07-25 03:17:06 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | tvae | mlp] BA=0.6139 | mean_dpd=0.3347

  [EO | f_frequency_of_see_adult_read | tvae | mlp]  BA=0.6139  mean_DPD=0.3347

2026-07-25 03:17:59 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | tvae | prejudice_remover] BA=0.5652 | mean_dpd=0.2364

  [PR | f_frequency_of_see_adult_read | tvae]  BA=0.5652  mean_DPD=0.2364

2026-07-25 03:18:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | gaussian_copula | logistic_regression] BA=0.4354 | mean_dpd=0.2501

  [EO | f_frequency_of_see_adult_read | gaussian_copula | logistic_regression]  BA=0.4354  mean_DPD=0.2501

2026-07-25 03:18:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | gaussian_copula | xgboost] BA=0.4416 | mean_dpd=0.1825

  [EO | f_frequency_of_see_adult_read | gaussian_copula | xgboost]  BA=0.4416  mean_DPD=0.1825

2026-07-25 03:18:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | gaussian_copula | mlp] BA=0.4720 | mean_dpd=0.1613

  [EO | f_frequency_of_see_adult_read | gaussian_copula | mlp]  BA=0.4720  mean_DPD=0.1613

2026-07-25 03:19:08 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_frequency_of_see_adult_read | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:19:10 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | smote | logistic_regression] BA=0.6110 | mean_dpd=0.2657

  [EO | f_frequency_of_see_adult_read | smote | logistic_regression]  BA=0.6110  mean_DPD=0.2657

2026-07-25 03:19:13 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | smote | xgboost] BA=0.5275 | mean_dpd=0.1130

  [EO | f_frequency_of_see_adult_read | smote | xgboost]  BA=0.5275  mean_DPD=0.1130

2026-07-25 03:19:48 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | smote | mlp] BA=0.5901 | mean_dpd=0.1154

  [EO | f_frequency_of_see_adult_read | smote | mlp]  BA=0.5901  mean_DPD=0.1154

2026-07-25 03:21:15 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | smote | prejudice_remover] BA=0.6160 | mean_dpd=0.2953

  [PR | f_frequency_of_see_adult_read | smote]  BA=0.6160  mean_DPD=0.2953

2026-07-25 03:21:16 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | real | logistic_regression] BA=0.5975 | mean_dpd=0.2571

  [EO | p_public_or_private | real | logistic_regression]  BA=0.5975  mean_DPD=0.2571

2026-07-25 03:21:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | real | xgboost] BA=0.6420 | mean_dpd=0.2752

  [EO | p_public_or_private | real | xgboost]  BA=0.6420  mean_DPD=0.2752

2026-07-25 03:21:29 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | real | mlp] BA=0.6238 | mean_dpd=0.2461

  [EO | p_public_or_private | real | mlp]  BA=0.6238  mean_DPD=0.2461

2026-07-25 03:22:50 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | real | prejudice_remover] BA=0.5295 | mean_dpd=0.0652

  [PR | p_public_or_private | real]  BA=0.5295  mean_DPD=0.0652

2026-07-25 03:22:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | ctgan | logistic_regression] BA=0.5276 | mean_dpd=0.1289

  [EO | p_public_or_private | ctgan | logistic_regression]  BA=0.5276  mean_DPD=0.1289

2026-07-25 03:22:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | ctgan | xgboost] BA=0.5235 | mean_dpd=0.1194

  [EO | p_public_or_private | ctgan | xgboost]  BA=0.5235  mean_DPD=0.1194

2026-07-25 03:23:03 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | ctgan | mlp] BA=0.5204 | mean_dpd=0.1203

  [EO | p_public_or_private | ctgan | mlp]  BA=0.5204  mean_DPD=0.1203

2026-07-25 03:24:04 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | ctgan | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_public_or_private | ctgan]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:24:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | tvae | logistic_regression] BA=0.5948 | mean_dpd=0.3343

  [EO | p_public_or_private | tvae | logistic_regression]  BA=0.5948  mean_DPD=0.3343

2026-07-25 03:24:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | tvae | xgboost] BA=0.6082 | mean_dpd=0.3523

  [EO | p_public_or_private | tvae | xgboost]  BA=0.6082  mean_DPD=0.3523

2026-07-25 03:24:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | tvae | mlp] BA=0.6096 | mean_dpd=0.3457

  [EO | p_public_or_private | tvae | mlp]  BA=0.6096  mean_DPD=0.3457

2026-07-25 03:25:27 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | tvae | prejudice_remover] BA=0.5664 | mean_dpd=0.2407

  [PR | p_public_or_private | tvae]  BA=0.5664  mean_DPD=0.2407

2026-07-25 03:25:27 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | gaussian_copula | logistic_regression] BA=0.4376 | mean_dpd=0.2385

  [EO | p_public_or_private | gaussian_copula | logistic_regression]  BA=0.4376  mean_DPD=0.2385

2026-07-25 03:25:30 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | gaussian_copula | xgboost] BA=0.4514 | mean_dpd=0.1631

  [EO | p_public_or_private | gaussian_copula | xgboost]  BA=0.4514  mean_DPD=0.1631

2026-07-25 03:25:38 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | gaussian_copula | mlp] BA=0.4749 | mean_dpd=0.1668

  [EO | p_public_or_private | gaussian_copula | mlp]  BA=0.4749  mean_DPD=0.1668

2026-07-25 03:26:39 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_public_or_private | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:26:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | smote | logistic_regression] BA=0.5976 | mean_dpd=0.2308

  [EO | p_public_or_private | smote | logistic_regression]  BA=0.5976  mean_DPD=0.2308

2026-07-25 03:26:43 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | smote | xgboost] BA=0.5160 | mean_dpd=0.1031

  [EO | p_public_or_private | smote | xgboost]  BA=0.5160  mean_DPD=0.1031

2026-07-25 03:27:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | smote | mlp] BA=0.5821 | mean_dpd=0.0933

  [EO | p_public_or_private | smote | mlp]  BA=0.5821  mean_DPD=0.0933

2026-07-25 03:28:31 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | smote | prejudice_remover] BA=0.6233 | mean_dpd=0.2835

  [PR | p_public_or_private | smote]  BA=0.6233  mean_DPD=0.2835

2026-07-25 03:28:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | real | logistic_regression] BA=0.6151 | mean_dpd=0.3096

  [EO | p_island | real | logistic_regression]  BA=0.6151  mean_DPD=0.3096

2026-07-25 03:28:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | real | xgboost] BA=0.6500 | mean_dpd=0.3349

  [EO | p_island | real | xgboost]  BA=0.6500  mean_DPD=0.3349

2026-07-25 03:28:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | real | mlp] BA=0.6299 | mean_dpd=0.2860

  [EO | p_island | real | mlp]  BA=0.6299  mean_DPD=0.2860

2026-07-25 03:29:54 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | real | prejudice_remover] BA=0.5385 | mean_dpd=0.1003

  [PR | p_island | real]  BA=0.5385  mean_DPD=0.1003

2026-07-25 03:29:55 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | ctgan | logistic_regression] BA=0.5519 | mean_dpd=0.1712

  [EO | p_island | ctgan | logistic_regression]  BA=0.5519  mean_DPD=0.1712

2026-07-25 03:29:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | ctgan | xgboost] BA=0.5315 | mean_dpd=0.1391

  [EO | p_island | ctgan | xgboost]  BA=0.5315  mean_DPD=0.1391

2026-07-25 03:30:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | ctgan | mlp] BA=0.5291 | mean_dpd=0.1381

  [EO | p_island | ctgan | mlp]  BA=0.5291  mean_DPD=0.1381

2026-07-25 03:31:07 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | ctgan | prejudice_remover] BA=0.4996 | mean_dpd=0.0008

  [PR | p_island | ctgan]  BA=0.4996  mean_DPD=0.0008

2026-07-25 03:31:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | tvae | logistic_regression] BA=0.6052 | mean_dpd=0.3618

  [EO | p_island | tvae | logistic_regression]  BA=0.6052  mean_DPD=0.3618

2026-07-25 03:31:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | tvae | xgboost] BA=0.6149 | mean_dpd=0.3687

  [EO | p_island | tvae | xgboost]  BA=0.6149  mean_DPD=0.3687

2026-07-25 03:31:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | tvae | mlp] BA=0.6143 | mean_dpd=0.3586

  [EO | p_island | tvae | mlp]  BA=0.6143  mean_DPD=0.3586

2026-07-25 03:32:18 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | tvae | prejudice_remover] BA=0.5690 | mean_dpd=0.2603

  [PR | p_island | tvae]  BA=0.5690  mean_DPD=0.2603

2026-07-25 03:32:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | gaussian_copula | logistic_regression] BA=0.4451 | mean_dpd=0.2162

  [EO | p_island | gaussian_copula | logistic_regression]  BA=0.4451  mean_DPD=0.2162

2026-07-25 03:32:21 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | gaussian_copula | xgboost] BA=0.4465 | mean_dpd=0.1798

  [EO | p_island | gaussian_copula | xgboost]  BA=0.4465  mean_DPD=0.1798

2026-07-25 03:32:29 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | gaussian_copula | mlp] BA=0.4683 | mean_dpd=0.1694

  [EO | p_island | gaussian_copula | mlp]  BA=0.4683  mean_DPD=0.1694

2026-07-25 03:33:15 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_island | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:33:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | smote | logistic_regression] BA=0.6157 | mean_dpd=0.2963

  [EO | p_island | smote | logistic_regression]  BA=0.6157  mean_DPD=0.2963

2026-07-25 03:33:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | smote | xgboost] BA=0.5243 | mean_dpd=0.0956

  [EO | p_island | smote | xgboost]  BA=0.5243  mean_DPD=0.0956

2026-07-25 03:33:55 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | smote | mlp] BA=0.5936 | mean_dpd=0.1189

  [EO | p_island | smote | mlp]  BA=0.5936  mean_DPD=0.1189

2026-07-25 03:35:37 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | smote | prejudice_remover] BA=0.6228 | mean_dpd=0.3041

  [PR | p_island | smote]  BA=0.6228  mean_DPD=0.3041

2026-07-25 03:35:39 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | real | logistic_regression] BA=0.6045 | mean_dpd=0.2739

  [EO | p_percentage_of_teachers_changed_school_last_year | real | logistic_regression]  BA=0.6045  mean_DPD=0.2739

2026-07-25 03:35:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | real | xgboost] BA=0.6463 | mean_dpd=0.3160

  [EO | p_percentage_of_teachers_changed_school_last_year | real | xgboost]  BA=0.6463  mean_DPD=0.3160

2026-07-25 03:35:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | real | mlp] BA=0.6286 | mean_dpd=0.2777

  [EO | p_percentage_of_teachers_changed_school_last_year | real | mlp]  BA=0.6286  mean_DPD=0.2777

2026-07-25 03:36:32 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | real | prejudice_remover] BA=0.5436 | mean_dpd=0.0953

  [PR | p_percentage_of_teachers_changed_school_last_year | real]  BA=0.5436  mean_DPD=0.0953

2026-07-25 03:36:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | ctgan | logistic_regression] BA=0.5527 | mean_dpd=0.1838

  [EO | p_percentage_of_teachers_changed_school_last_year | ctgan | logistic_regression]  BA=0.5527  mean_DPD=0.1838

2026-07-25 03:36:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | ctgan | xgboost] BA=0.5345 | mean_dpd=0.1362

  [EO | p_percentage_of_teachers_changed_school_last_year | ctgan | xgboost]  BA=0.5345  mean_DPD=0.1362

2026-07-25 03:36:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | ctgan | mlp] BA=0.5284 | mean_dpd=0.1280

  [EO | p_percentage_of_teachers_changed_school_last_year | ctgan | mlp]  BA=0.5284  mean_DPD=0.1280

2026-07-25 03:37:45 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | ctgan | prejudice_remover] BA=0.5000 | mean_dpd=0.0005

  [PR | p_percentage_of_teachers_changed_school_last_year | ctgan]  BA=0.5000  mean_DPD=0.0005

2026-07-25 03:37:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | tvae | logistic_regression] BA=0.6039 | mean_dpd=0.3519

  [EO | p_percentage_of_teachers_changed_school_last_year | tvae | logistic_regression]  BA=0.6039  mean_DPD=0.3519

2026-07-25 03:37:48 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | tvae | xgboost] BA=0.6133 | mean_dpd=0.3567

  [EO | p_percentage_of_teachers_changed_school_last_year | tvae | xgboost]  BA=0.6133  mean_DPD=0.3567

2026-07-25 03:38:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | tvae | mlp] BA=0.6130 | mean_dpd=0.3499

  [EO | p_percentage_of_teachers_changed_school_last_year | tvae | mlp]  BA=0.6130  mean_DPD=0.3499

2026-07-25 03:39:12 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | tvae | prejudice_remover] BA=0.5664 | mean_dpd=0.2526

  [PR | p_percentage_of_teachers_changed_school_last_year | tvae]  BA=0.5664  mean_DPD=0.2526

2026-07-25 03:39:13 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | logistic_regression] BA=0.4406 | mean_dpd=0.2282

  [EO | p_percentage_of_teachers_changed_school_last_year | gaussian_copula | logistic_regression]  BA=0.4406  mean_DPD=0.2282

2026-07-25 03:39:15 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | xgboost] BA=0.4508 | mean_dpd=0.1680

  [EO | p_percentage_of_teachers_changed_school_last_year | gaussian_copula | xgboost]  BA=0.4508  mean_DPD=0.1680

2026-07-25 03:39:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | mlp] BA=0.4679 | mean_dpd=0.1693

  [EO | p_percentage_of_teachers_changed_school_last_year | gaussian_copula | mlp]  BA=0.4679  mean_DPD=0.1693

2026-07-25 03:40:13 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_percentage_of_teachers_changed_school_last_year | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:40:14 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | smote | logistic_regression] BA=0.6079 | mean_dpd=0.2610

  [EO | p_percentage_of_teachers_changed_school_last_year | smote | logistic_regression]  BA=0.6079  mean_DPD=0.2610

2026-07-25 03:40:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | smote | xgboost] BA=0.5231 | mean_dpd=0.1040

  [EO | p_percentage_of_teachers_changed_school_last_year | smote | xgboost]  BA=0.5231  mean_DPD=0.1040

2026-07-25 03:40:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | smote | mlp] BA=0.5880 | mean_dpd=0.1021

  [EO | p_percentage_of_teachers_changed_school_last_year | smote | mlp]  BA=0.5880  mean_DPD=0.1021

2026-07-25 03:41:55 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | smote | prejudice_remover] BA=0.6290 | mean_dpd=0.2942

  [PR | p_percentage_of_teachers_changed_school_last_year | smote]  BA=0.6290  mean_DPD=0.2942

2026-07-25 03:41:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | real | logistic_regression] BA=0.6010 | mean_dpd=0.1781

  [EO | f_ESCS | real | logistic_regression]  BA=0.6010  mean_DPD=0.1781

2026-07-25 03:41:59 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | real | xgboost] BA=0.6334 | mean_dpd=0.1926

  [EO | f_ESCS | real | xgboost]  BA=0.6334  mean_DPD=0.1926

2026-07-25 03:42:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | real | mlp] BA=0.6202 | mean_dpd=0.1745

  [EO | f_ESCS | real | mlp]  BA=0.6202  mean_DPD=0.1745

2026-07-25 03:43:11 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | real | prejudice_remover] BA=0.5152 | mean_dpd=0.0308

  [PR | f_ESCS | real]  BA=0.5152  mean_DPD=0.0308

2026-07-25 03:43:12 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | ctgan | logistic_regression] BA=0.5439 | mean_dpd=0.1239

  [EO | f_ESCS | ctgan | logistic_regression]  BA=0.5439  mean_DPD=0.1239

2026-07-25 03:43:15 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | ctgan | xgboost] BA=0.5258 | mean_dpd=0.1007

  [EO | f_ESCS | ctgan | xgboost]  BA=0.5258  mean_DPD=0.1007

2026-07-25 03:43:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | ctgan | mlp] BA=0.5259 | mean_dpd=0.1044

  [EO | f_ESCS | ctgan | mlp]  BA=0.5259  mean_DPD=0.1044

2026-07-25 03:44:31 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | ctgan | prejudice_remover] BA=0.5001 | mean_dpd=0.0007

  [PR | f_ESCS | ctgan]  BA=0.5001  mean_DPD=0.0007

2026-07-25 03:44:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | tvae | logistic_regression] BA=0.5844 | mean_dpd=0.2347

  [EO | f_ESCS | tvae | logistic_regression]  BA=0.5844  mean_DPD=0.2347

2026-07-25 03:44:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | tvae | xgboost] BA=0.5987 | mean_dpd=0.2514

  [EO | f_ESCS | tvae | xgboost]  BA=0.5987  mean_DPD=0.2514

2026-07-25 03:44:49 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | tvae | mlp] BA=0.5946 | mean_dpd=0.2665

  [EO | f_ESCS | tvae | mlp]  BA=0.5946  mean_DPD=0.2665

2026-07-25 03:45:50 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | tvae | prejudice_remover] BA=0.5606 | mean_dpd=0.2261

  [PR | f_ESCS | tvae]  BA=0.5606  mean_DPD=0.2261

2026-07-25 03:45:51 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | gaussian_copula | logistic_regression] BA=0.4590 | mean_dpd=0.1737

  [EO | f_ESCS | gaussian_copula | logistic_regression]  BA=0.4590  mean_DPD=0.1737

2026-07-25 03:45:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | gaussian_copula | xgboost] BA=0.4542 | mean_dpd=0.1357

  [EO | f_ESCS | gaussian_copula | xgboost]  BA=0.4542  mean_DPD=0.1357

2026-07-25 03:46:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | gaussian_copula | mlp] BA=0.4740 | mean_dpd=0.1541

  [EO | f_ESCS | gaussian_copula | mlp]  BA=0.4740  mean_DPD=0.1541

2026-07-25 03:47:58 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_ESCS | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:48:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | smote | logistic_regression] BA=0.5924 | mean_dpd=0.1691

  [EO | f_ESCS | smote | logistic_regression]  BA=0.5924  mean_DPD=0.1691

2026-07-25 03:48:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | smote | xgboost] BA=0.5177 | mean_dpd=0.1497

  [EO | f_ESCS | smote | xgboost]  BA=0.5177  mean_DPD=0.1497

2026-07-25 03:48:38 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | smote | mlp] BA=0.5737 | mean_dpd=0.0712

  [EO | f_ESCS | smote | mlp]  BA=0.5737  mean_DPD=0.0712

2026-07-25 03:50:14 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | smote | prejudice_remover] BA=0.6149 | mean_dpd=0.2774

  [PR | f_ESCS | smote]  BA=0.6149  mean_DPD=0.2774

Mitigation results saved → C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\high_perf\goal3_mitigation_results.csv
Shape: (240, 61)  (0 degenerate/skipped fits, if any)

,technique,target_attr,method,classifier,balanced_accuracy,f1_macro,roc_auc,brier_score,degenerate_predictions,s_gender_dpd,...,p_percentage_of_teachers_changed_school_last_year_di,p_percentage_of_teachers_changed_school_last_year_odds_ratio,f_ESCS_dpd,f_ESCS_eod,f_ESCS_di,f_ESCS_odds_ratio,mean_dpd,mean_eod,mean_di,mean_odds_ratio
0,equalized_odds,s_gender,real,logistic_regression,0.621793,0.592925,0.621793,0.350581,False,0.005872,...,0.487335,1.737488,0.444478,0.429315,0.333472,0.452017,0.319627,0.316519,0.520986,0.872213
1,equalized_odds,s_gender,real,xgboost,0.653164,0.588922,0.653164,0.381958,False,0.000167,...,0.550545,1.434116,0.517083,0.522829,0.369019,0.578364,0.337237,0.344471,0.563427,0.905010
2,equalized_odds,s_gender,real,mlp,0.637045,0.602478,0.637045,0.346315,False,0.011951,...,0.501395,1.566489,0.421010,0.401850,0.367405,0.536446,0.306034,0.305726,0.526338,0.915816
3,prejudice_remover,s_gender,real,prejudice_remover,0.538571,0.517061,0.673372,0.170502,False,0.024273,...,0.131017,8.716465,0.112582,0.185455,0.023421,0.049002,0.100219,0.163189,0.221165,1.758259
4,equalized_odds,s_gender,ctgan,logistic_regression,0.557549,0.522659,0.557549,0.433427,False,0.026060,...,0.953506,1.062143,0.198032,0.216261,0.658015,0.666535,0.162816,0.176444,0.717462,1.090964
5,equalized_odds,s_gender,ctgan,xgboost,0.532419,0.478284,0.532419,0.497901,False,0.006495,...,0.871480,1.195972,0.183195,0.216134,0.722126,0.691288,0.129846,0.143371,0.794942,0.996895
6,equalized_odds,s_gender,ctgan,mlp,0.527539,0.513275,0.527539,0.416913,False,0.012852,...,0.779060,1.312845,0.155693,0.194916,0.673379,0.622992,0.129512,0.143800,0.720138,1.038861
7,prejudice_remover,s_gender,ctgan,prejudice_remover,0.500160,0.431813,0.572025,0.182193,False,0.000758,...,0.317617,NaN,0.002033,0.002163,0.175264,0.247892,0.001896,0.002279,0.241078,1.170187
8,equalized_odds,s_gender,tvae,logistic_regression,0.608735,0.570048,0.608735,0.384504,False,0.171733,...,0.474146,1.865981,0.537025,0.527773,0.305476,0.386699,0.353149,0.362897,0.503536,0.903576
9,equalized_odds,s_gender,tvae,xgboost,0.610940,0.577335,0.610940,0.371912,False,0.144705,...,0.541035,1.744292,0.589065,0.578432,0.249582,0.351974,0.363647,0.372316,0.491020,0.872299

### Mitigation summary tables

For every mitigated row we look up the **matching unmitigated row** from
`results_df` (same `method`, and for equalized-odds the same `classifier`) and
compare the targeted attribute's own DPD/EOD/DI before vs. after mitigation —
this answers "did mitigating for attribute X actually reduce unfairness on
X?", as opposed to the mean-across-all-attributes numbers used elsewhere in
the notebook.

In [27]:
def _unmitigated_target_metrics(method: str, classifier: str | None, attr: str) -> dict[str, float]:
    """Mean dpd/eod/di for `attr` from the unmitigated results_df, matched on
    method (+ classifier when given -- prejudice_remover has no match, so we
    average across all classifiers for that method instead)."""
    sub = results_df[results_df["method"] == method]
    if classifier is not None:
        sub = sub[sub["classifier"] == classifier]
    out = {}
    for metric in ("dpd", "eod", "di"):
        col = f"{attr}_{metric}"
        out[metric] = sub[col].mean() if col in sub.columns and not sub.empty else float("nan")
    return out


comparison_rows = []
for _, r in mitigation_df.iterrows():
    attr = r["target_attr"]
    clf_lookup = r["classifier"] if r["technique"] == "equalized_odds" else None
    base = _unmitigated_target_metrics(r["method"], clf_lookup, attr)

    row = {
        "technique": r["technique"], "target_attr": attr,
        "method": r["method"], "classifier": r["classifier"],
        "balanced_accuracy": r["balanced_accuracy"],
    }
    for metric in ("dpd", "eod", "di"):
        mitigated_val = r.get(f"{attr}_{metric}", float("nan"))
        row[f"{metric}_unmitigated"] = base[metric]
        row[f"{metric}_mitigated"]   = mitigated_val
        # DPD/EOD: lower is fairer -> improvement = unmitigated - mitigated.
        # DI: closer to 1 is fairer -> improvement = mitigated - unmitigated.
        if metric == "di":
            row[f"{metric}_improvement"] = mitigated_val - base[metric]
        else:
            row[f"{metric}_improvement"] = base[metric] - mitigated_val
    comparison_rows.append(row)

mitigation_comparison_df = pd.DataFrame(comparison_rows)
if not mitigation_comparison_df.empty:
    comparison_path = cfg["paths"]["results_dir"] / "goal3_mitigation_comparison.csv"
    mitigation_comparison_df.to_csv(comparison_path, index=False)
    print(f"Mitigation comparison saved → {comparison_path}\n")
    print(mitigation_comparison_df.round(4).to_string(index=False))
else:
    print("No mitigation rows to compare (mitigation disabled or no protected attributes present).")

Mitigation comparison saved → C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\high_perf\goal3_mitigation_comparison.csv

        technique                                       target_attr          method          classifier  balanced_accuracy  dpd_unmitigated  dpd_mitigated  dpd_improvement  eod_unmitigated  eod_mitigated  eod_improvement  di_unmitigated  di_mitigated  di_improvement
   equalized_odds                                          s_gender            real logistic_regression             0.6218           0.1216         0.0059           0.1157           0.1345         0.0078           0.1267          0.7398        0.9848          0.2450
   equalized_odds                                          s_gender            real             xgboost             0.6532           0.0749         0.0002           0.0747           0.0930         0.0101           0.0829          0.8254        0.9997          0.1743
   equalized_odds                                          s_gender            real                 mlp             0.6370           0.0283         0.0120           0.0163           0.0578         0.0342           0.0236          0.6466        0.9704          0.3238
prejudice_remover                                          s_gender            real   prejudice_remover             0.5386           0.0749         0.0243           0.0507           0.0951         0.0559           0.0393          0.7372        0.5613         -0.1759
   equalized_odds                                          s_gender           ctgan logistic_regression             0.5575           0.0995         0.0261           0.0735           0.1043         0.0374           0.0668          0.8020        0.9441          0.1421
   equalized_odds                                          s_gender           ctgan             xgboost             0.5324           0.0012         0.0065          -0.0053           0.0051         0.0077          -0.0026          0.9975        0.9881         -0.0094
   equalized_odds                                          s_gender           ctgan                 mlp             0.5275           0.0000         0.0129          -0.0128           0.0005         0.0177          -0.0172          0.9424        0.9665          0.0241
prejudice_remover                                          s_gender           ctgan   prejudice_remover             0.5002           0.0336         0.0008           0.0328           0.0366         0.0011           0.0355          0.9140        0.5140         -0.3999
   equalized_odds                                          s_gender            tvae logistic_regression             0.6087           0.0968         0.1717          -0.0749           0.1456         0.1888          -0.0432          0.6944        0.6694         -0.0250
   equalized_odds                                          s_gender            tvae             xgboost             0.6109           0.0617         0.1447          -0.0830           0.0832         0.1584          -0.0752          0.8187        0.7011         -0.1175
   equalized_odds                                          s_gender            tvae                 mlp             0.6094           0.0412         0.0951          -0.0538           0.0842         0.1117          -0.0275          0.7984        0.7870         -0.0115
prejudice_remover                                          s_gender            tvae   prejudice_remover             0.5645           0.0666         0.0595           0.0070           0.1043         0.1110          -0.0067          0.7705        0.6061         -0.1644
   equalized_odds                                          s_gender gaussian_copula logistic_regression             0.4230           0.1947         0.0032           0.1915           0.2021         0.0096           0.1925          0.6445        0.9943          0.3498
   equalized_odds                                          s_gender gaussian_copula             xgboost             0.4415           0.0811         0.0164           0.0647           0.0855         0.0199           0.0656          0.8602        0.9707          0.1105
   equalized_odds                                          s_gender gaussian_copula                 mlp             0.4671           0.0001         0.0009          -0.0008           0.0002         0.0039          -0.0037          0.4712        0.9987          0.5275
prejudice_remover                                          s_gender gaussian_copula   prejudice_remover             0.5000           0.0920         0.0000           0.0920           0.0959         0.0000           0.0959          0.6586           NaN             NaN
   equalized_odds                                          s_gender           smote logistic_regression             0.6141           0.1651         0.0024           0.1627           0.1702         0.0194           0.1508          0.6709        0.9949          0.3240
   equalized_odds                                          s_gender           smote             xgboost             0.5206           0.0548         0.0086           0.0462           0.0684         0.0090           0.0593          0.8820        0.9793          0.0973
   equalized_odds                                          s_gender           smote                 mlp             0.5928           0.0552         0.0087           0.0465           0.0623         0.0060           0.0563          0.8647        0.9803          0.1156
prejudice_remover                                          s_gender           smote   prejudice_remover             0.6227           0.0917         0.0996          -0.0079           0.1003         0.1124          -0.0121          0.8059        0.7800         -0.0259
   equalized_odds                                   s_birth_country            real logistic_regression             0.6237           0.0926         0.0259           0.0667           0.1085         0.0977           0.0108          0.7737        0.9387          0.1650
   equalized_odds                                   s_birth_country            real             xgboost             0.6550           0.1269         0.0036           0.1232           0.1675         0.0813           0.0861          0.6779        0.9912          0.3133
   equalized_odds                                   s_birth_country            real                 mlp             0.6377           0.0420         0.0108           0.0312           0.1085         0.1125          -0.0040          0.3719        0.9724          0.6004
prejudice_remover                                   s_birth_country            real   prejudice_remover             0.5384           0.0872         0.0368           0.0504           0.1282         0.0393           0.0889          0.6079        0.5446         -0.0633
   equalized_odds                                   s_birth_country           ctgan logistic_regression             0.5361           0.3371         0.0490           0.2881           0.4387         0.0804           0.3583          0.2593        0.7282          0.4689
   equalized_odds                                   s_birth_country           ctgan             xgboost             0.5352           0.2630         0.1008           0.1622           0.3860         0.1249           0.2610          0.4380        0.8292          0.3912
   equalized_odds                                   s_birth_country           ctgan                 mlp             0.5177           0.0001         0.0953          -0.0952           0.0003         0.1026          -0.1023          0.0000        0.5486          0.5486
prejudice_remover                                   s_birth_country           ctgan   prejudice_remover             0.5000           0.2001         0.0363           0.1638           0.2750         0.0394           0.2356          0.2324        0.0261         -0.2063
   equalized_odds                                   s_birth_country            tvae logistic_regression             0.6079           0.1032         0.0179           0.0854           0.2406         0.1101           0.1305          0.6190        0.9399          0.3209
   equalized_odds                                   s_birth_country            tvae             xgboost             0.6152           0.0627         0.0065           0.0562           0.2160         0.0803           0.1357          0.7985        0.9792          0.1807
   equalized_odds                                   s_birth_country            tvae                 mlp             0.6164           0.0736         0.0182           0.0554           0.1795         0.1254           0.0541          0.6029        0.9485          0.3456
prejudice_remover                                   s_birth_country            tvae   prejudice_remover             0.5680           0.0799         0.0233           0.0566           0.2121         0.0365           0.1755          0.6734        0.8439          0.1705
   equalized_odds                                   s_birth_country gaussian_copula logistic_regression             0.4297           0.2891         0.0928           0.1963           0.3291         0.1017           0.2274          0.6089        0.8411          0.2322
   equalized_odds                                   s_birth_country gaussian_copula             xgboost             0.4476           0.1638         0.0089           0.1549           0.2174         0.0333           0.1841          0.6982        0.9824          0.2842
   equalized_odds                                   s_birth_country gaussian_copula                 mlp             0.4738           0.0124         0.0625          -0.0501           0.0160         0.0685          -0.0525          0.0056        0.8907          0.8851
prejudice_remover                                   s_birth_country gaussian_copula   prejudice_remover             0.5001           0.1551         0.0373           0.1178           0.1875         0.0541           0.1335          0.4376        0.0000         -0.4376
   equalized_odds                                   s_birth_country           smote logistic_regression             0.6203           0.1562         0.1398           0.0164           0.1987         0.2363          -0.0376          0.6310        0.6762          0.0451
   equalized_odds                                   s_birth_country           smote             xgboost             0.5255           0.0029         0.0188          -0.0159           0.1459         0.1225           0.0233          0.9934        0.9568         -0.0366
   equalized_odds                                   s_birth_country           smote                 mlp             0.5876           0.1720         0.2318          -0.0598           0.2309         0.2826          -0.0517          0.5511        0.5110         -0.0401
prejudice_remover                                   s_birth_country           smote   prejudice_remover             0.6197           0.1104         0.2718          -0.1615           0.1918         0.3805          -0.1886          0.7252        0.3445         -0.3807
   equalized_odds                          f_mother_education_level            real logistic_regression             0.5977           0.5225         0.0227           0.4998           0.5127         0.0127           0.5000          0.3319        0.9526          0.6207
   equalized_odds                          f_mother_education_level            real             xgboost             0.6318           0.5750         0.0420           0.5330           0.5715         0.0079           0.5636          0.2846        0.9021          0.6175
   equalized_odds                          f_mother_education_level            real                 mlp             0.6157           0.1579         0.0253           0.1326           0.2296         0.0116           0.2180          0.1191        0.9467          0.8276
prejudice_remover                          f_mother_education_level            real   prejudice_remover             0.5203           0.4185         0.0605           0.3580           0.4380         0.1075           0.3305          0.2452        0.0368         -0.2085
   equalized_odds                          f_mother_education_level           ctgan logistic_regression             0.5267           0.2330         0.0982           0.1348           0.2271         0.1217           0.1053          0.6230        0.8428          0.2197
   equalized_odds                          f_mother_education_level           ctgan             xgboost             0.5098           0.2044         0.1107           0.0937           0.2082         0.1222           0.0860          0.6656        0.7519          0.0862
   equalized_odds                          f_mother_education_level           ctgan                 mlp             0.5152           0.0002         0.0625          -0.0624           0.0005         0.0751          -0.0746          0.0000        0.8724          0.8724
prejudice_remover                          f_mother_education_level           ctgan   prejudice_remover             0.5000           0.1459         0.0000           0.1458           0.1453         0.0005           0.1448          0.4295        0.8371          0.4075
   equalized_odds                          f_mother_education_level            tvae logistic_regression             0.5783           0.5230         0.1459           0.3772           0.5440         0.1667           0.3773          0.1877        0.6989          0.5112
   equalized_odds                          f_mother_education_level            tvae             xgboost             0.5979           0.6060         0.2737           0.3323           0.5881         0.2689           0.3192          0.1853        0.4874          0.3021
   equalized_odds                          f_mother_education_level            tvae                 mlp             0.5899           0.4091         0.2421           0.1669           0.4556         0.2469           0.2087          0.1428        0.5319          0.3892
prejudice_remover                          f_mother_education_level            tvae   prejudice_remover             0.5561           0.5127         0.2722           0.2405           0.5292         0.3451           0.1841          0.1719        0.0877         -0.0842
   equalized_odds                          f_mother_education_level gaussian_copula logistic_regression             0.4404           0.3142         0.2190           0.0952           0.3092         0.2085           0.1007          0.4211        0.5666          0.1455
   equalized_odds                          f_mother_education_level gaussian_copula             xgboost             0.4590           0.2914         0.1539           0.1375           0.3060         0.1861           0.1199          0.5329        0.7167          0.1837
   equalized_odds                          f_mother_education_level gaussian_copula                 mlp             0.4715           0.0000         0.1164          -0.1163           0.0001         0.1226          -0.1225          0.7964        0.8563          0.0599
prejudice_remover                          f_mother_education_level gaussian_copula   prejudice_remover             0.5000           0.2019         0.0000           0.2019           0.2051         0.0000           0.2051          0.5835           NaN             NaN
   equalized_odds                          f_mother_education_level           smote logistic_regression             0.5821           0.4808         0.0199           0.4609           0.4671         0.0374           0.4297          0.3718        0.9552          0.5834
   equalized_odds                          f_mother_education_level           smote             xgboost             0.5132           0.0910         0.2971          -0.2061           0.1485         0.3313          -0.1829          0.8039        0.4402         -0.3637
   equalized_odds                          f_mother_education_level           smote                 mlp             0.5696           0.1513         0.0662           0.0851           0.1293         0.0955           0.0338          0.6909        0.8523          0.1615
prejudice_remover                          f_mother_education_level           smote   prejudice_remover             0.6108           0.2410         0.4969          -0.2559           0.2483         0.5033          -0.2550          0.6222        0.3399         -0.2823
   equalized_odds                          f_father_education_level            real logistic_regression             0.5959           0.5027         0.0181           0.4846           0.4862         0.0169           0.4693          0.3757        0.9608          0.5851
   equalized_odds                          f_father_education_level            real             xgboost             0.6309           0.5451         0.0402           0.5048           0.5421         0.0167           0.5254          0.3376        0.9173          0.5797
   equalized_odds                          f_father_education_level            real                 mlp             0.6125           0.1834         0.0278           0.1556           0.2596         0.0126           0.2469          0.1313        0.9434          0.8121
prejudice_remover                          f_father_education_level            real   prejudice_remover             0.5219           0.4104         0.0660           0.3444           0.4293         0.1037           0.3255          0.2815        0.1176         -0.1639
   equalized_odds                          f_father_education_level           ctgan logistic_regression             0.5502           0.2032         0.1138           0.0893           0.1944         0.1131           0.0813          0.6679        0.8274          0.1594
   equalized_odds                          f_father_education_level           ctgan             xgboost             0.5211           0.2011         0.0164           0.1847           0.2043         0.0206           0.1837          0.6776        0.9669          0.2893
   equalized_odds                          f_father_education_level           ctgan                 mlp             0.5256           0.0002         0.0730          -0.0727           0.0009         0.0784          -0.0775          0.2667        0.8441          0.5774
prejudice_remover                          f_father_education_level           ctgan   prejudice_remover             0.4997           0.1348         0.0011           0.1337           0.1332         0.0019           0.1313          0.5374        0.1334         -0.4041
   equalized_odds                          f_father_education_level            tvae logistic_regression             0.6082           0.5098         0.3235           0.1862           0.4970         0.3007           0.1963          0.2417        0.4865          0.2448
   equalized_odds                          f_father_education_level            tvae             xgboost             0.6141           0.5145         0.3171           0.1974           0.4941         0.2918           0.2023          0.2820        0.4542          0.1722
   equalized_odds                          f_father_education_level            tvae                 mlp             0.6062           0.4144         0.3132           0.1012           0.4346         0.2927           0.1419          0.1902        0.4710          0.2808
prejudice_remover                          f_father_education_level            tvae   prejudice_remover             0.5639           0.4796         0.3385           0.1411           0.4752         0.4033           0.0719          0.2380        0.1237         -0.1143
   equalized_odds                          f_father_education_level gaussian_copula logistic_regression             0.4336           0.3059         0.2650           0.0409           0.3110         0.2588           0.0522          0.4091        0.5019          0.0928

In [28]:
# Summary table 1: overall effectiveness per technique (mean across every
# attribute/method/classifier it was run on).
if not mitigation_comparison_df.empty:
    print("Mean fairness improvement by technique (positive = fairer than unmitigated):\n")
    by_technique = mitigation_comparison_df.groupby("technique")[
        ["balanced_accuracy", "dpd_improvement", "eod_improvement", "di_improvement"]
    ].mean()
    print(by_technique.round(4).to_string())
else:
    by_technique = pd.DataFrame()

Mean fairness improvement by technique (positive = fairer than unmitigated):

                   balanced_accuracy  dpd_improvement  eod_improvement  di_improvement
technique
equalized_odds                0.5555           0.1181           0.1244          0.3255
prejudice_remover             0.5422           0.1065           0.1058         -0.1704

In [29]:
# Summary table 2: best technique per protected attribute, by mean DPD improvement.
if not mitigation_comparison_df.empty:
    by_attr_technique = (
        mitigation_comparison_df
        .groupby(["target_attr", "technique"])[["balanced_accuracy", "dpd_improvement", "eod_improvement", "di_improvement"]]
        .mean()
        .round(4)
    )
    print("Mean fairness improvement by (attribute, technique):\n")
    print(by_attr_technique.to_string())

    print("\nBest technique per attribute (highest mean DPD improvement):\n")
    best_per_attr = (
        mitigation_comparison_df
        .groupby(["target_attr", "technique"])["dpd_improvement"]
        .mean()
        .reset_index()
        .sort_values("dpd_improvement", ascending=False)
        .drop_duplicates("target_attr")
        .sort_values("target_attr")
    )
    print(best_per_attr.round(4).to_string(index=False))
else:
    by_attr_technique = pd.DataFrame()
    best_per_attr = pd.DataFrame()

Mean fairness improvement by (attribute, technique):

                                                                     balanced_accuracy  dpd_improvement  eod_improvement  di_improvement
target_attr                                       technique
f_ESCS                                            equalized_odds                0.5533           0.1755           0.1765          0.4270
                                                  prejudice_remover             0.5382           0.1567           0.1510         -0.1689
f_extent_of_books_at_home                         equalized_odds                0.5464           0.1624           0.1632          0.3947
                                                  prejudice_remover             0.5367           0.1027           0.0940         -0.3040
f_father_education_level                          equalized_odds                0.5525           0.1396           0.1446          0.3266
                                                  prejudice_remover             0.5402           0.1170           0.1025         -0.2362
f_father_occupation                               equalized_odds                0.5515           0.1424           0.1403          0.3280
                                                  prejudice_remover             0.5405           0.1773           0.1704         -0.1456
f_frequency_of_see_adult_read                     equalized_odds                0.5620           0.0574           0.0602          0.2449
                                                  prejudice_remover             0.5443           0.0709           0.0611         -0.1685
f_mother_education_level                          equalized_odds                0.5466           0.1776           0.1788          0.3478
                                                  prejudice_remover             0.5374           0.1381           0.1219         -0.0419
f_mother_occupation                               equalized_odds                0.5537           0.1684           0.1749          0.3624
                                                  prejudice_remover             0.5416           0.1454           0.1354         -0.2030
p_island                                          equalized_odds                0.5624           0.0454           0.0554          0.2350
                                                  prejudice_remover             0.5460           0.0530           0.0590         -0.1420
p_percentage_of_teachers_changed_school_last_year equalized_odds                0.5602           0.0756           0.0880          0.3544
                                                  prejudice_remover             0.5478           0.0804           0.0928         -0.1863
p_public_or_private                               equalized_odds                0.5538           0.1683           0.1861          0.4201
                                                  prejudice_remover             0.5438           0.1565           0.1618         -0.0374
s_birth_country                                   equalized_odds                0.5620           0.0677           0.0816          0.3136
                                                  prejudice_remover             0.5452           0.0454           0.0890         -0.1835
s_gender                                          equalized_odds                0.5612           0.0374           0.0437          0.1514
                                                  prejudice_remover             0.5452           0.0349           0.0304         -0.1915

Best technique per attribute (highest mean DPD improvement):

                                      target_attr         technique  dpd_improvement
                                           f_ESCS    equalized_odds           0.1755
                        f_extent_of_books_at_home    equalized_odds           0.1624
                         f_father_education_level    equalized_odds           0.1396
                              f_father_occupation prejudice_remover           0.1773
                    f_frequency_of_see_adult_read prejudice_remover           0.0709
                         f_mother_education_level    equalized_odds           0.1776
                              f_mother_occupation    equalized_odds           0.1684
                                         p_island prejudice_remover           0.0530
p_percentage_of_teachers_changed_school_last_year prejudice_remover           0.0804
                              p_public_or_private    equalized_odds           0.1683
                                  s_birth_country    equalized_odds           0.0677
                                         s_gender    equalized_odds           0.0374

## 9 · Summary

In [30]:
print("=" * 70)
print("GOAL 3 SUMMARY")
print("=" * 70)

if not results_df.empty:
    synth = results_df[results_df["method"] != BASELINE]
    real  = results_df[results_df["method"] == BASELINE]

    mean_real_ba = real["balanced_accuracy"].mean()
    print(f"\nReal baseline (mean BA across classifiers): {mean_real_ba:.4f}")

    print("\nMean balanced accuracy per synthetic method (mean across classifiers):")
    tbl = synth.groupby("method")["balanced_accuracy"].mean().sort_values(ascending=False)
    for m, v in tbl.items():
        print(f"  {m:<20}  BA={v:.4f}  (Δ={v - mean_real_ba:+.4f})")

    if "mean_dpd" in synth.columns:
        print("\nMean DPD per synthetic method (mean across classifiers):")
        for m, v in synth.groupby("method")["mean_dpd"].mean().sort_values().items():
            print(f"  {m:<20}  mean_DPD={v:.4f}")

    if "mean_odds_ratio" in synth.columns:
        print("\nMean equalized-odds odds-ratio per synthetic method (mean across classifiers, ~1.0 = fair):")
        for m, v in synth.groupby("method")["mean_odds_ratio"].mean().items():
            print(f"  {m:<20}  mean_odds_ratio={v:.4f}")

if not mitigation_comparison_df.empty:
    print("\n" + "-" * 70)
    print("MITIGATION SUMMARY")
    print("-" * 70)
    for technique, row in by_technique.iterrows():
        print(f"  {technique:<20}  BA={row['balanced_accuracy']:.4f}  "
              f"ΔDPD={row['dpd_improvement']:+.4f}  ΔEOD={row['eod_improvement']:+.4f}  ΔDI={row['di_improvement']:+.4f}")
    print("\n  Best technique per attribute (by mean DPD improvement):")
    for _, row in best_per_attr.iterrows():
        print(f"    {row['target_attr']:<25}  {row['technique']:<20}  ΔDPD={row['dpd_improvement']:+.4f}")
    print(f"\n  Full comparison saved to: {cfg['paths']['results_dir'] / 'goal3_mitigation_comparison.csv'}")

print("\nAll figures saved to:", cfg["paths"]["figures_dir"])
print("Results CSV saved to:", cfg["paths"]["results_dir"] / "goal3_results.csv")

======================================================================
GOAL 3 SUMMARY
======================================================================

Real baseline (mean BA across classifiers): 0.6131

Mean balanced accuracy per synthetic method (mean across classifiers):
  tvae                  BA=0.6012  (Δ=-0.0119)
  smote                 BA=0.5803  (Δ=-0.0328)
  ctgan                 BA=0.5315  (Δ=-0.0816)
  gaussian_copula       BA=0.4590  (Δ=-0.1541)

Mean DPD per synthetic method (mean across classifiers):
  ctgan                 mean_DPD=0.1090
  gaussian_copula       mean_DPD=0.1505
  smote                 mean_DPD=0.1811
  tvae                  mean_DPD=0.3463

Mean equalized-odds odds-ratio per synthetic method (mean across classifiers, ~1.0 = fair):
  ctgan                 mean_odds_ratio=0.7822
  gaussian_copula       mean_odds_ratio=1.6962
  smote                 mean_odds_ratio=0.9927
  tvae                  mean_odds_ratio=0.8820

----------------------------------------------------------------------
MITIGATION SUMMARY
----------------------------------------------------------------------
  equalized_odds        BA=0.5555  ΔDPD=+0.1181  ΔEOD=+0.1244  ΔDI=+0.3255
  prejudice_remover     BA=0.5422  ΔDPD=+0.1065  ΔEOD=+0.1058  ΔDI=-0.1704

  Best technique per attribute (by mean DPD improvement):
    f_ESCS                     equalized_odds        ΔDPD=+0.1755
    f_extent_of_books_at_home  equalized_odds        ΔDPD=+0.1624
    f_father_education_level   equalized_odds        ΔDPD=+0.1396
    f_father_occupation        prejudice_remover     ΔDPD=+0.1773
    f_frequency_of_see_adult_read  prejudice_remover     ΔDPD=+0.0709
    f_mother_education_level   equalized_odds        ΔDPD=+0.1776
    f_mother_occupation        equalized_odds        ΔDPD=+0.1684
    p_island                   prejudice_remover     ΔDPD=+0.0530
    p_percentage_of_teachers_changed_school_last_year  prejudice_remover     ΔDPD=+0.0804
    p_public_or_private        equalized_odds        ΔDPD=+0.1683
    s_birth_country            equalized_odds        ΔDPD=+0.0677
    s_gender                   equalized_odds        ΔDPD=+0.0374

  Full comparison saved to: C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\high_perf\goal3_mitigation_comparison.csv

All figures saved to: C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\high_perf
Results CSV saved to: C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\high_perf\goal3_results.csv

> **📝 Notebook takeaway (updated after the 2026-07-18 synthetic-data regeneration).**
> - **Utility:** GaussianCopula has regressed sharply since the synthetic data was regenerated — LR/XGBoost trained on it now score BA 0.49–0.51 (chance level, mean Δ=−0.117 vs. real), down from a previously middling ~0.57–0.60. TVAE is now the best-preserving generator (mean Δ=−0.018), edging out CTGAN (−0.029); SMOTE is worst of the non-collapsed generators (−0.049). This reorders the earlier "CTGAN is best" finding — worth confirming the regression is intended (re-check the GaussianCopula fit in G2) rather than treating it as settled.
> - **`gaussian_copula | mlp` is flagged `degenerate_predictions=True`**: the classifier predicts a single class for the entire test set (BA=0.5000 exactly, mean DPD/EOD=0.0000, mean DI/odds_ratio=NaN) — the fairness-by-uselessness artifact already described in G4, now caught automatically instead of needing to be spotted by eye.
> - **Fairness (mean DPD):** GaussianCopula now reads as "fairest" (0.063) purely because two of its three classifiers are near-chance or degenerate — not real debiasing. Excluding that artifact, the real ranking is SMOTE (0.176) < CTGAN (0.330) < TVAE (0.396, least fair). TVAE remains the best-utility / worst-fairness generator; CTGAN sits in between on both axes. Still no generator wins on both axes simultaneously.
> - **Mitigation:** Equalized Odds remains the safer default — better balanced accuracy (0.571 vs. 0.547 mean BA) and the only technique that improves DI on average (+0.224 vs. Prejudice Remover's −0.211), for comparable DPD/EOD gains (~0.11–0.12 for both techniques).