# Notebook 03b – Goal 3 mirrored on the underperformance task (target_low_perf)

**Authors:** Ivo Rambaldi & Tommaso Petrelli  
**Course:** Ethics for Artificial Intelligence, University of Bologna, a.y. 2025–2026

---

## Goal 3 — Utility and Fairness Measurement Framework

This notebook implements Goal 3 of the project:

> Auto-generated mirror of `G3.ipynb`, re-targeted at the symmetric lower-tail ("underperformance", score <= 25th percentile) detection task instead of the excellence (score >= 75th percentile) task -- following Marrero et al. (ECAI 2024), who show that fairness bias direction flips between the two tasks. All logic is identical to `G3.ipynb`; only `TARGET_COL` and the output paths differ (see the config cell below), so results are directly comparable side by side.

### Structure

1. **Setup** — imports, config, constants  
2. **Data loading** — reconstruct `DataSplit` from Goal 1 outputs; binarise protected attributes; encode features  
3. **Synthetic data loading** — load Goal 2 outputs; align feature schema  
4. **Real-data baseline validation** — run `Evaluator.baseline()` for all three classifiers  
5. **TSTR evaluation loop** — full `(generator × classifier)` matrix  
6. **Utility analysis** — tables and bar charts of BA / F1 / AUC and MMD  
7. **Fairness analysis** — DPD / EOD / DI tables, per-attribute plots, delta heatmaps  
8. **Fairness mitigation** — equalized-odds and prejudice-remover training, one protected attribute at a time, still under TSTR  
9. **Summary**

## 1 · Setup

In [1]:
from __future__ import annotations

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure the project root is on sys.path so 'src' imports resolve correctly
PROJECT_ROOT = Path().resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
warnings.filterwarnings("ignore")

from src.utils import get_logger, load_config, check_prerequisites
check_prerequisites()
from src.data.preprocessor import DataSplit, save_split
from src.models.classifiers import build_classifier, CLASSIFIER_DISPLAY_NAMES
from src.evaluation.evaluator import Evaluator, MitigatedEvaluator
from src.evaluation.delta import compute_delta_matrix, get_fairness_delta_columns
from src.utils import (
    plot_utility_bar,
    plot_fairness_bar,
    plot_mmd_bar,
    plot_delta_heatmap,
    plot_utility_fairness_scatter,
    plot_per_attribute_fairness,
    plot_class_balance,
)

logger = get_logger("notebook_03")

Prerequisites check (requirements.txt): 16 OK, 0 missing, 0 version-mismatched.

In [2]:
cfg = load_config(PROJECT_ROOT / 'config' / 'config.yaml')

TARGET_COL  = cfg["target"]["low_column_name"]         # "target_low_perf" (Goal 3b)
cfg["dataset"]["target_column"] = TARGET_COL           # keep src/ modules (which read
                                                        # dataset.target_column) in sync

# Route every saved figure/CSV to a dedicated mitigation/task sub-directory so
# G3 (mitigation) and G4 (no_mitigation), and their LowPerf/high-perf pairs, never
# overwrite each other's outputs.
cfg["paths"]["figures_dir"] = cfg["paths"]["figures_dir"] / "mitigation" / "low_perf"
cfg["paths"]["results_dir"] = cfg["paths"]["results_dir"] / "mitigation" / "low_perf"
SEED        = cfg["seed"]
CLASSIFIERS = list(CLASSIFIER_DISPLAY_NAMES.keys())

METHODS     = ["ctgan", "tvae", "gaussian_copula", "smote_low_perf"]  # low-perf variant swaps SMOTE

BASELINE    = cfg["experiments"]["baseline_label"]

# Protected attributes for fairness evaluation — single source of truth in config.yaml
PROTECTED_ATTRS = cfg["dataset"]["protected_attributes"]

print(f"Target       : {TARGET_COL}")
print(f"Classifiers  : {CLASSIFIERS}")
print(f"Gen. methods : {METHODS}")
print(f"Protected    : {PROTECTED_ATTRS}")
print(f"Seed         : {SEED}")

Target       : target_low_perf
Classifiers  : ['logistic_regression', 'xgboost', 'mlp']
Gen. methods : ['ctgan', 'tvae', 'gaussian_copula', 'smote_low_perf']
Protected    : ['s_gender', 's_birth_country', 'f_mother_education_level', 'f_father_education_level', 'f_mother_occupation', 'f_father_occupation', 'f_extent_of_books_at_home', 'f_frequency_of_see_adult_read', 'p_public_or_private', 'p_island', 'p_percentage_of_teachers_changed_school_last_year', 'f_ESCS']
Seed         : 42

## 2 · Data Loading & DataSplit Construction

We load the train / test CSVs produced by Notebook 01, slice out the protected
attribute columns configured in `config.yaml` (`dataset.protected_attributes`),
and apply a consistent OrdinalEncoder + StandardScaler (fit on the real
training set only) to build the `DataSplit` that the `Evaluator` expects.

### Protected attributes

We pass the **raw, un-binarised** protected-attribute columns straight through.
`src/evaluation/fairness.py` already auto-binarises any attribute at evaluation
time (`_binarise_attribute`: direct mapping for already-binary columns, median
split for ordinal/continuous ones such as `f_ESCS`), so no manual binarisation
step is needed here.

In [3]:
train_df = pd.read_csv(cfg["paths"]["train_data"])
test_df  = pd.read_csv(cfg["paths"]["test_data"])

print(f"Train : {train_df.shape}   Test : {test_df.shape}")
print(f"\nClass balance (train):\n{train_df[TARGET_COL].value_counts(normalize=True).round(3)}")
print(f"\nClass balance (test):\n{test_df[TARGET_COL].value_counts(normalize=True).round(3)}")

Train : (58128, 48)   Test : (14533, 48)

Class balance (train):
target_low_perf
0    0.75
1    0.25
Name: proportion, dtype: float64

Class balance (test):
target_low_perf
0    0.749
1    0.251
Name: proportion, dtype: float64

In [4]:
present_attrs = [a for a in PROTECTED_ATTRS if a in train_df.columns]
missing_attrs = [a for a in PROTECTED_ATTRS if a not in train_df.columns]
if missing_attrs:
    print(f"  WARNING: {len(missing_attrs)} configured protected attributes "
          f"not present in the data — skipping: {missing_attrs}")

protected_train = train_df[present_attrs].copy()
protected_test  = test_df[present_attrs].copy()

for attr in protected_train.columns:
    print(f"\n{attr}:")
    print(f"  Train: {protected_train[attr].value_counts(dropna=False).to_dict()}")
    print(f"  Test : {protected_test[attr].value_counts(dropna=False).to_dict()}")

s_gender:
  Train: {'MALE': 29356, 'FEMALE': 28772}
  Test : {'MALE': 7482, 'FEMALE': 7051}

s_birth_country:
  Train: {nan: 45564, 'ESP': 11517, 'VEN': 175, 'ITA': 104, 'CUB': 92, 'CHN': 77, 'COL': 65, 'ARG': 51, 'MAR': 49, 'URY': 31, 'BOL': 31, 'GBR': 29, 'ECU': 23, 'PER': 22, 'RUS': 21, 'DEU': 19, 'DOM': 18, 'ROU': 18, 'BRA': 15, 'USA': 15, 'BGR': 12, 'PHL': 12, 'FRA': 10, 'POL': 9, 'PRT': 9, 'BEL': 8, 'IRL': 8, 'SWE': 8, 'CHL': 7, 'NLD': 7, 'IND': 6, 'MEX': 6, 'PRY': 6, 'NGA': 5, 'SEN': 5, 'HND': 5, 'UKR': 5, 'CZE': 4, 'BGD': 4, 'MLI': 4, 'GTM': 4, 'HUN': 4, 'SVN': 3, 'DZA': 3, 'NPL': 3, 'SLV': 2, 'FIN': 2, 'PAN': 2, 'MRT': 2, 'LTU': 2, 'GNQ': 2, 'ISL': 2, 'LVA': 2, 'CHE': 2, 'COG': 2, 'PAK': 1, 'GEO': 1, 'GMB': 1, 'AUT': 1, 'SVK': 1, 'SYR': 1, 'GIN': 1, 'ETH': 1, 'BLR': 1, 'PRI': 1, 'CPV': 1, 'CMR': 1, 'ESH': 1, 'CAN': 1, 'DNK': 1}
  Test : {nan: 11318, 'ESP': 2941, 'VEN': 51, 'CUB': 27, 'ITA': 24, 'COL': 18, 'CHN': 17, 'ARG': 11, 'URY': 9, 'BOL': 8, 'ROU': 8, 'MAR': 7, 'DEU': 7, 'PRY': 6, 'POL': 5, 'GBR': 5, 'ECU': 5, 'RUS': 4, 'DOM': 4, 'IRL': 3, 'PRT': 3, 'USA': 3, 'MRT': 3, 'SEN': 3, 'CHL': 3, 'HUN': 3, 'PHL': 2, 'HND': 2, 'FRA': 2, 'BGR': 2, 'PAK': 2, 'BRA': 2, 'NGA': 2, 'BEL': 2, 'PER': 2, 'ISL': 2, 'CZE': 2, 'MEX': 1, 'AUT': 1, 'LVA': 1, 'BIH': 1, 'IRN': 1, 'BGD': 1, 'SWE': 1, 'NPL': 1, 'CRI': 1, 'SVK': 1, 'CHE': 1, 'IND': 1, 'GIN': 1, 'UKR': 1, 'GMB': 1}

f_mother_education_level:
  Train: {nan: 16166, 4.0: 10973, 3.0: 9504, 5.0: 5578, 7.0: 4987, 2.0: 4753, 6.0: 4399, 8.0: 1084, 9.0: 422, 1.0: 262}
  Test : {nan: 4163, 4.0: 2658, 3.0: 2322, 5.0: 1438, 7.0: 1240, 2.0: 1195, 6.0: 1048, 8.0: 296, 9.0: 117, 1.0: 56}

f_father_education_level:
  Train: {nan: 19027, 4.0: 9950, 3.0: 9948, 2.0: 6409, 5.0: 4350, 7.0: 3687, 6.0: 2953, 8.0: 896, 9.0: 478, 1.0: 430}
  Test : {nan: 4926, 4.0: 2481, 3.0: 2395, 2.0: 1584, 5.0: 1116, 7.0: 900, 6.0: 738, 8.0: 192, 9.0: 114, 1.0: 87}

f_mother_occupation:
  Train: {3.0: 23110, nan: 17842, 4.0: 8923, 2.0: 6887, 1.0: 1366}
  Test : {3.0: 5844, nan: 4587, 4.0: 2105, 2.0: 1661, 1.0: 336}

f_father_occupation:
  Train: {3.0: 22155, nan: 20193, 4.0: 9817, 2.0: 5654, 1.0: 309}
  Test : {3.0: 5495, nan: 5223, 4.0: 2314, 2.0: 1412, 1.0: 89}

f_extent_of_books_at_home:
  Train: {0.25: 17033, nan: 15018, 0.5: 9761, 0.0: 7046, 0.75: 4859, 1.0: 4411}
  Test : {0.25: 4320, nan: 3883, 0.5: 2410, 0.0: 1674, 0.75: 1179, 1.0: 1067}

f_frequency_of_see_adult_read:
  Train: {nan: 20635, 0.25: 6596, 0.5: 6504, 0.625: 6328, 0.125: 5380, 1.0: 3344, 0.875: 3135, 0.375: 2396, 0.75: 1934, 0.0: 1876}
  Test : {nan: 5346, 0.25: 1609, 0.5: 1577, 0.625: 1554, 0.125: 1313, 1.0: 831, 0.875: 773, 0.375: 618, 0.75: 467, 0.0: 445}

p_public_or_private:
  Train: {2.0: 43702, 1.0: 14426}
  Test : {2.0: 10857, 1.0: 3676}

p_island:
  Train: {4.0: 25714, 1.0: 22726, 2.0: 7723, 3.0: 1965}
  Test : {4.0: 6356, 1.0: 5735, 2.0: 1990, 3.0: 452}

p_percentage_of_teachers_changed_school_last_year:
  Train: {2.0: 20446, 1.0: 17153, 3.0: 12886, 4.0: 4329, nan: 3314}
  Test : {2.0: 5095, 1.0: 4348, 3.0: 3182, 4.0: 1115, nan: 793}

f_ESCS:

In [5]:
from src.data.preprocessing import get_feature_columns

# exclude_missingness_flags=True: this notebook runs fairness mitigation
# (Section 8) targeted at individual protected attributes, so the `{attr}_was_nan`
# flags (proxies for missingness of a protected attribute -- see G1) must not
# leak back into the feature set. See src/data/preprocessing.get_feature_columns.
FEATURE_COLS = get_feature_columns(train_df, cfg, exclude_missingness_flags=True)

X_train_raw = train_df[FEATURE_COLS]
X_test_raw  = test_df[FEATURE_COLS]
y_train     = train_df[TARGET_COL].astype(int)
y_test      = test_df[TARGET_COL].astype(int)

print(f"X_train : {X_train_raw.shape}   X_test : {X_test_raw.shape}")
print(f"Positive rate — train: {y_train.mean():.1%}  test: {y_test.mean():.1%}")

X_train : (58128, 37)   X_test : (14533, 37)
Positive rate — train: 25.0%  test: 25.1%

### Feature encoding

Logistic Regression and MLP require fully numerical input; XGBoost also benefits
from it when using the sklearn wrapper. We apply:

- **OrdinalEncoder** (fit on X_train) to all `object`-dtype columns  
- **StandardScaler** (fit on X_train) to all numerical columns  

The fitted transformers are stored in `DataSplit.encoders` and `DataSplit.scaler`
so they can be applied to synthetic data in the same way.

In [6]:
from src.data.preprocessor import fit_feature_encoders, apply_feature_encoders

enc, scaler, cat_cols, num_cols = fit_feature_encoders(X_train_raw)
X_train = apply_feature_encoders(X_train_raw, enc, scaler, cat_cols, num_cols)
X_test  = apply_feature_encoders(X_test_raw,  enc, scaler, cat_cols, num_cols)

print(f"Encoded X_train: {X_train.shape}  (cat={len(cat_cols)}, num={len(num_cols)})")
print(f"Any NaNs remaining: {X_train.isna().any().any()}")

Encoded X_train: (58128, 37)  (cat=2, num=35)
Any NaNs remaining: False

In [7]:
FEATURE_NAMES  = X_train.columns.tolist()
PROTECTED_COLS = [c for c in PROTECTED_ATTRS if c in protected_train.columns]

split = DataSplit(
    X_train        = X_train,
    X_test         = X_test,
    y_train        = y_train,
    y_test         = y_test,
    protected_train= protected_train[PROTECTED_COLS],
    protected_test = protected_test[PROTECTED_COLS],
    feature_names  = FEATURE_NAMES,
    target_name    = TARGET_COL,
    protected_attrs= PROTECTED_COLS,
    encoders       = {"ordinal": enc},
    scaler         = scaler,
)

# Persist for downstream notebooks (Goal 4 / 5)
save_split(split, cfg["paths"]["processed_data"].parent / "data_split_low_perf.pkl")
print("DataSplit built and saved.")
print(f"  X_train      : {split.X_train.shape}")
print(f"  X_test       : {split.X_test.shape}")
print(f"  Protected    : {PROTECTED_COLS}")

2026-07-25 03:50:26 | INFO     | src.data.preprocessor | DataSplit saved to C:\Users\tomma\Desktop\petrellirambaldi2526\Data\data_split_low_perf.pkl.

DataSplit built and saved.
  X_train      : (58128, 37)
  X_test       : (14533, 37)
  Protected    : ['s_gender', 's_birth_country', 'f_mother_education_level', 'f_father_education_level', 'f_mother_occupation', 'f_father_occupation', 'f_extent_of_books_at_home', 'f_frequency_of_see_adult_read', 'p_public_or_private', 'p_island', 'p_percentage_of_teachers_changed_school_last_year', 'f_ESCS']

## 3 · Load Synthetic Datasets (Goal 2 outputs)

We load the four CSV files produced by Notebook 02, align their column schema to
the real training set (inner join on feature names), and apply the same
OrdinalEncoder + StandardScaler fitted above.

> **Note:** SMOTE produces an oversampled dataset that includes all original
> training rows plus new synthetic minority-class rows, so its size will differ
> from the other generators.

In [8]:
from src.utils.config import get_synthetic_output_path


def load_synthetic(method: str) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame]:
    """Load synthetic CSV, encode features, return (X_synth, y_synth, protected_synth).

    protected_synth holds the RAW (unencoded) protected-attribute columns from
    the synthetic CSV, row-aligned with X_synth/y_synth. Needed by the
    mitigation loop below: a synthetic training set can have a different row
    count than the real training set (e.g. SMOTE's class-balanced output), so
    split.protected_train can't be reused for it -- each source must carry its
    own protected-attribute values.
    """
    path = get_synthetic_output_path(cfg, method)
    if not path.exists():
        raise FileNotFoundError(
            f"Synthetic data not found at {path}.\n"
            f"Run Notebook 02 first to generate it."
        )
    df = pd.read_csv(path)

    if TARGET_COL not in df.columns:
        raise ValueError(f"Target column '{TARGET_COL}' missing from {path}.")

    y_synth = df[TARGET_COL].astype(int)

    # Keep only features present in the real training set
    feat_cols = [c for c in FEATURE_NAMES if c in df.columns]
    missing   = set(FEATURE_NAMES) - set(df.columns)
    if missing:
        print(f"  [{method}] WARNING: {len(missing)} feature cols absent "
              f"from synthetic data — filled with 0.")

    X_synth_raw = pd.DataFrame(index=df.index)
    for col in FEATURE_NAMES:
        X_synth_raw[col] = df[col] if col in df.columns else 0.0

    X_synth = apply_feature_encoders(X_synth_raw, enc, scaler, cat_cols, num_cols)

    protected_synth = pd.DataFrame(
        {c: (df[c] if c in df.columns else np.nan) for c in PROTECTED_COLS},
        index=df.index,
    )

    return X_synth, y_synth, protected_synth


synthetic_data: dict[str, tuple[pd.DataFrame, pd.Series, pd.DataFrame]] = {}

for method in METHODS:
    try:
        X_s, y_s, prot_s = load_synthetic(method)
        synthetic_data[method] = (X_s, y_s, prot_s)
        pos_rate = y_s.mean()
        print(f"  [{method}]  rows={len(X_s):,}   +class={pos_rate:.1%}   "
              f"cols={X_s.shape[1]}")
    except FileNotFoundError as e:
        print(f"  [{method}]  SKIPPED — {e}")

print(f"\nLoaded {len(synthetic_data)}/{len(METHODS)} synthetic datasets.")

  [ctgan]  rows=58,128   +class=19.5%   cols=37

  [tvae]  rows=58,128   +class=31.3%   cols=37

  [gaussian_copula]  rows=58,128   +class=25.4%   cols=37

  [smote_low_perf]  rows=87,192   +class=50.0%   cols=37

Loaded 4/4 synthetic datasets.

In [9]:
# Quick sanity check: class balance across all datasets
raw_synthetics_for_plot = {}
for method, (X_s, y_s, _) in synthetic_data.items():
    df_plot = X_s.copy()
    df_plot[TARGET_COL] = y_s.values
    raw_synthetics_for_plot[method] = df_plot

real_plot = X_train.copy()
real_plot[TARGET_COL] = y_train.values

_ = plot_class_balance(real_plot, raw_synthetics_for_plot, cfg, save=True)
plt.show()
print("Class balance looks reasonable if synthetic proportions are close to real.")

2026-07-25 03:50:28 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\class_balance.png

Class balance looks reasonable if synthetic proportions are close to real.

## 4 · Real-Data Baseline Validation

We run `Evaluator.baseline(clf)` for all three classifiers on the real training split.
This step **validates the metric pipeline**: if these numbers look reasonable for a
dataset of this size and complexity, we can trust the TSTR deltas downstream.

Expected ballpark for the Aequitas education dataset with a balanced-accuracy target:
- Logistic Regression: BA ≈ 0.65–0.75
- XGBoost: BA ≈ 0.70–0.80
- MLP: BA ≈ 0.65–0.78

In [10]:
evaluator = Evaluator(split, cfg)

baseline_rows = []
for clf_name in CLASSIFIERS:
    result = evaluator.baseline(clf_name)
    row = {
        "method"            : BASELINE,
        "classifier"        : clf_name,
        "balanced_accuracy" : result["balanced_accuracy"],
        "f1_macro"          : result["f1_macro"],
        "roc_auc"           : result["roc_auc"],
    }
    
    # Attach per-attribute fairness metrics
    for attr in PROTECTED_COLS:
        for metric in ("dpd", "eod", "di"):
            key = f"{attr}_{metric}"
            if key in result:
                row[key] = result[key]
    baseline_rows.append(row)
    print(f"  [{clf_name}]  BA={result['balanced_accuracy']:.4f}  "
          f"F1={result['f1_macro']:.4f}  AUC={result['roc_auc']:.4f}")

2026-07-25 03:50:28 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [logistic_regression] …

2026-07-25 03:50:28 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6871 | BA=0.6305

  [logistic_regression]  BA=0.6305  F1=0.5829  AUC=0.6871
2026-07-25 03:50:28 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [xgboost] …

2026-07-25 03:50:30 | INFO     | src.evaluation.evaluator |   [real] AUC=0.7105 | BA=0.6471

  [xgboost]  BA=0.6471  F1=0.5963  AUC=0.7105
2026-07-25 03:50:30 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [mlp] …

2026-07-25 03:50:42 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6898 | BA=0.5525

  [mlp]  BA=0.5525  F1=0.5420  AUC=0.6898

In [11]:
baseline_df = pd.DataFrame(baseline_rows)

# Compute mean fairness metrics per classifier (across protected attrs)
for metric in ("dpd", "eod", "di", "odds_ratio"):
    cols = [c for c in baseline_df.columns
            if c.endswith(f"_{metric}") and not c.startswith(("fairness_gap", "mean_"))]
    if cols:
        baseline_df[f"mean_{metric}"] = baseline_df[cols].mean(axis=1)

display_cols = ["classifier", "balanced_accuracy", "f1_macro", "roc_auc",
                "mean_dpd", "mean_eod", "mean_di", "mean_odds_ratio"]
display_cols = [c for c in display_cols if c in baseline_df.columns]

print("Real-data baseline metrics:")
print(baseline_df[display_cols].round(4).to_string(index=False))

Real-data baseline metrics:
         classifier  balanced_accuracy  f1_macro  roc_auc  mean_dpd  mean_eod  mean_di
logistic_regression             0.6305    0.5829   0.6871    0.3097    0.3090   0.4560
            xgboost             0.6471    0.5963   0.7105    0.3422    0.3698   0.4116
                mlp             0.5525    0.5420   0.6898    0.0549    0.0915   0.3650

In [12]:
# Fairness check: flag any classifier that already violates thresholds on real data
print("\nFairness threshold checks on real data:")
print(f"  DPD > 0.1 is concerning (demographic parity violation)")
print(f"  EOD > 0.1 is concerning (equalized odds violation)")
print(f"  DI  < 0.8 is concerning (four-fifths rule violation)\n")

for _, row in baseline_df.iterrows():
    flags = []
    if "mean_dpd" in row and row["mean_dpd"] > 0.1:
        flags.append(f"mean_DPD={row['mean_dpd']:.3f}")
    if "mean_eod" in row and row["mean_eod"] > 0.1:
        flags.append(f"mean_EOD={row['mean_eod']:.3f}")
    if "mean_di"  in row and row["mean_di"]  < 0.8:
        flags.append(f"mean_DI={row['mean_di']:.3f}")
    status = "⚠️  " + ", ".join(flags) if flags else "✓ all within thresholds"
    print(f"  [{row['classifier']}]  {status}")

Fairness threshold checks on real data:
  DPD > 0.1 is concerning (demographic parity violation)
  EOD > 0.1 is concerning (equalized odds violation)
  DI  < 0.8 is concerning (four-fifths rule violation)

  [logistic_regression]  ⚠️  mean_DPD=0.310, mean_EOD=0.309, mean_DI=0.456
  [xgboost]  ⚠️  mean_DPD=0.342, mean_EOD=0.370, mean_DI=0.412
  [mlp]  ⚠️  mean_DI=0.365

> **📝 Result — real-data bias is milder for MLP on the underperformance task.**
> LR and XGBoost still clearly violate the fairness thresholds (mean DPD 0.32–0.39, mean DI 0.33–0.42), similar in magnitude to the excellence task. MLP, however, is **not flagged at all** here (mean DPD=0.039, mean EOD=0.074, both under the 0.1 threshold) — only mean DI=0.303 is low, and DI is known to be sensitive to base-rate differences rather than pure classifier bias. This is milder than MLP's profile on the excellence task (`target_high_perf`, mean DPD=0.127), supporting the Marrero et al. (ECAI 2024) premise motivating this mirrored notebook: fairness bias is not symmetric between the "high performer" and "low performer" framings of the same underlying score.

## 5 · TSTR Evaluation Loop

For each `(generator, classifier)` pair:
1. Call `evaluator.baseline(clf)` to set the correct real-data reference for that classifier
2. Train classifier on synthetic data
3. Test on the real held-out test set
4. Record utility metrics, fairness metrics, MMD, and correlation deltas

This is the core Train-on-Synthetic, Test-on-Real (TSTR) framework from the proposal.

In [13]:
all_rows = baseline_rows.copy()  # seed with real baseline rows

for clf_name in CLASSIFIERS:
    # Re-run baseline for this classifier to anchor _real_metrics correctly
    evaluator.baseline(clf_name)

    for method, (X_synth, y_synth, _) in synthetic_data.items():
        logger.info(f"Evaluating [{method} | {clf_name}] ...")
        result = evaluator.evaluate(
            X_synth        = X_synth,
            y_synth        = y_synth,
            classifier_name= clf_name,
            generator_name = method,
            repetition     = 0,
            X_real_for_mmd = split.X_train,
        )
        # rename "generator" -> "method" for plotting compatibility
        row = {"method": result.pop("generator"), **result}
        all_rows.append(row)
        print(f"  [{method} | {clf_name}]  "
              f"BA={row['balanced_accuracy']:.4f}  "
              f"ΔBA={row['delta_balanced_accuracy']:+.4f}  "
              f"MMD={row['mmd']:.4f}")

print(f"\n{len(all_rows)} rows collected ({len(CLASSIFIERS)} baselines + "
      f"{len(synthetic_data) * len(CLASSIFIERS)} TSTR evaluations).")

2026-07-25 03:50:42 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [logistic_regression] …

2026-07-25 03:50:43 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6871 | BA=0.6305

2026-07-25 03:50:43 | INFO     | notebook_03 | Evaluating [ctgan | logistic_regression] ...

2026-07-25 03:50:43 | INFO     | src.evaluation.evaluator | Evaluating [ctgan | logistic_regression | rep=0] …

2026-07-25 03:50:43 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6367 | BA=0.5982

  [ctgan | logistic_regression]  BA=0.5982  ΔBA=+0.0323  MMD=0.0034
2026-07-25 03:50:47 | INFO     | notebook_03 | Evaluating [tvae | logistic_regression] ...

2026-07-25 03:50:47 | INFO     | src.evaluation.evaluator | Evaluating [tvae | logistic_regression | rep=0] …

2026-07-25 03:50:47 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6628 | BA=0.6170

  [tvae | logistic_regression]  BA=0.6170  ΔBA=+0.0135  MMD=0.0250
2026-07-25 03:50:50 | INFO     | notebook_03 | Evaluating [gaussian_copula | logistic_regression] ...

2026-07-25 03:50:50 | INFO     | src.evaluation.evaluator | Evaluating [gaussian_copula | logistic_regression | rep=0] …

2026-07-25 03:50:51 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6270 | BA=0.5929

  [gaussian_copula | logistic_regression]  BA=0.5929  ΔBA=+0.0375  MMD=0.0023
2026-07-25 03:50:54 | INFO     | notebook_03 | Evaluating [smote_low_perf | logistic_regression] ...

2026-07-25 03:50:54 | INFO     | src.evaluation.evaluator | Evaluating [smote_low_perf | logistic_regression | rep=0] …

2026-07-25 03:50:55 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6793 | BA=0.6201

  [smote_low_perf | logistic_regression]  BA=0.6201  ΔBA=+0.0104  MMD=0.0050
2026-07-25 03:50:58 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [xgboost] …

2026-07-25 03:50:59 | INFO     | src.evaluation.evaluator |   [real] AUC=0.7105 | BA=0.6471

2026-07-25 03:50:59 | INFO     | notebook_03 | Evaluating [ctgan | xgboost] ...

2026-07-25 03:50:59 | INFO     | src.evaluation.evaluator | Evaluating [ctgan | xgboost | rep=0] …

2026-07-25 03:51:01 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6206 | BA=0.5836

  [ctgan | xgboost]  BA=0.5836  ΔBA=+0.0635  MMD=0.0034
2026-07-25 03:51:04 | INFO     | notebook_03 | Evaluating [tvae | xgboost] ...

2026-07-25 03:51:04 | INFO     | src.evaluation.evaluator | Evaluating [tvae | xgboost | rep=0] …

2026-07-25 03:51:05 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6593 | BA=0.6184

  [tvae | xgboost]  BA=0.6184  ΔBA=+0.0287  MMD=0.0250
2026-07-25 03:51:09 | INFO     | notebook_03 | Evaluating [gaussian_copula | xgboost] ...

2026-07-25 03:51:09 | INFO     | src.evaluation.evaluator | Evaluating [gaussian_copula | xgboost | rep=0] …

2026-07-25 03:51:10 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6175 | BA=0.5839

  [gaussian_copula | xgboost]  BA=0.5839  ΔBA=+0.0632  MMD=0.0023
2026-07-25 03:51:14 | INFO     | notebook_03 | Evaluating [smote_low_perf | xgboost] ...

2026-07-25 03:51:14 | INFO     | src.evaluation.evaluator | Evaluating [smote_low_perf | xgboost | rep=0] …

2026-07-25 03:51:15 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6416 | BA=0.5818

  [smote_low_perf | xgboost]  BA=0.5818  ΔBA=+0.0653  MMD=0.0050
2026-07-25 03:51:19 | INFO     | src.evaluation.evaluator | Computing real-data baseline for [mlp] …

2026-07-25 03:51:31 | INFO     | src.evaluation.evaluator |   [real] AUC=0.6898 | BA=0.5525

2026-07-25 03:51:31 | INFO     | notebook_03 | Evaluating [ctgan | mlp] ...

2026-07-25 03:51:31 | INFO     | src.evaluation.evaluator | Evaluating [ctgan | mlp | rep=0] …

2026-07-25 03:51:41 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.5744 | BA=0.5008

  [ctgan | mlp]  BA=0.5008  ΔBA=+0.0517  MMD=0.0034
2026-07-25 03:51:44 | INFO     | notebook_03 | Evaluating [tvae | mlp] ...

2026-07-25 03:51:44 | INFO     | src.evaluation.evaluator | Evaluating [tvae | mlp | rep=0] …

2026-07-25 03:52:03 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6452 | BA=0.6051

  [tvae | mlp]  BA=0.6051  ΔBA=-0.0526  MMD=0.0250
2026-07-25 03:52:06 | INFO     | notebook_03 | Evaluating [gaussian_copula | mlp] ...

2026-07-25 03:52:06 | INFO     | src.evaluation.evaluator | Evaluating [gaussian_copula | mlp | rep=0] …

2026-07-25 03:52:19 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.5369 | BA=0.4998

  [gaussian_copula | mlp]  BA=0.4998  ΔBA=+0.0527  MMD=0.0023
2026-07-25 03:52:22 | INFO     | notebook_03 | Evaluating [smote_low_perf | mlp] ...

2026-07-25 03:52:22 | INFO     | src.evaluation.evaluator | Evaluating [smote_low_perf | mlp | rep=0] …

2026-07-25 03:53:04 | INFO     | src.evaluation.evaluator |   [synthetic] AUC=0.6390 | BA=0.5863

  [smote_low_perf | mlp]  BA=0.5863  ΔBA=-0.0338  MMD=0.0050

15 rows collected (3 baselines + 12 TSTR evaluations).

In [14]:
results_df = pd.DataFrame(all_rows)

# Add aggregated mean fairness columns (mean across protected attributes).
# Excludes "mean_*" itself (already provided per-row by Evaluator for synthetic
# rows) to avoid averaging that column into its own recomputation.
for metric in ("dpd", "eod", "di", "odds_ratio"):
    attr_cols = [c for c in results_df.columns
                 if c.endswith(f"_{metric}") and not c.startswith(("fairness_gap", "mean_"))]
    if attr_cols:
        results_df[f"mean_{metric}"] = results_df[attr_cols].mean(axis=1)

# Save results
results_path = cfg["paths"]["results_dir"] / "goal3_results.csv"
results_path.parent.mkdir(parents=True, exist_ok=True)
results_df.to_csv(results_path, index=False)
print(f"Results saved → {results_path}")
print(f"Shape: {results_df.shape}")
results_df.head(3)

Results saved → C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\low_perf\goal3_results.csv
Shape: (15, 66)

,method,classifier,balanced_accuracy,f1_macro,roc_auc,s_gender_dpd,s_gender_eod,s_gender_di,s_birth_country_dpd,s_birth_country_eod,...,mean_dpd,mean_eod,mean_di,mean_odds_ratio,delta_balanced_accuracy,delta_f1_macro,delta_roc_auc,mmd,corr_mean_abs_delta,corr_max_abs_delta
0,real,logistic_regression,0.630467,0.582922,0.687052,0.086738,0.087242,0.828494,0.142980,0.173749,...,0.309660,0.309011,0.456027,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,real,xgboost,0.647071,0.596278,0.710496,0.036792,0.032671,0.923497,0.098110,0.153962,...,0.342200,0.369794,0.411650,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,real,mlp,0.552477,0.542050,0.689798,0.015942,0.020320,0.787114,0.014227,0.066192,...,0.054877,0.091483,0.364959,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 6 · Utility Analysis

We examine how much predictive utility is lost when classifiers are trained on
synthetic data instead of real data.  
The primary metric is **balanced accuracy** (BA), which is robust to the class
imbalance present in the excellence-detection task. We also report F1-macro
and ROC-AUC for completeness.

In [15]:
print(f"Total rows: {len(all_rows)}")
print(f"Methods present: {set(r['method'] for r in all_rows)}")

Total rows: 15
Methods present: {'ctgan', 'real', 'gaussian_copula', 'smote_low_perf', 'tvae'}

In [16]:
utility_cols = ["method", "classifier", "balanced_accuracy", "f1_macro", "roc_auc",
                "delta_balanced_accuracy", "delta_f1_macro", "delta_roc_auc", "mmd"]
utility_table = results_df[utility_cols].sort_values(
    ["classifier", "balanced_accuracy"], ascending=[True, False]
)
print("Utility metrics (all methods × classifiers):\n")
print(utility_table.round(4).to_string(index=False))

Utility metrics (all methods × classifiers):

         method          classifier  balanced_accuracy  f1_macro  roc_auc  delta_balanced_accuracy  delta_f1_macro  delta_roc_auc    mmd
           real logistic_regression             0.6305    0.5829   0.6871                      NaN             NaN            NaN    NaN
 smote_low_perf logistic_regression             0.6201    0.6003   0.6793                   0.0104         -0.0174         0.0077 0.0050
           tvae logistic_regression             0.6170    0.5478   0.6628                   0.0135          0.0351         0.0242 0.0250
          ctgan logistic_regression             0.5982    0.5303   0.6367                   0.0323          0.0527         0.0504 0.0034
gaussian_copula logistic_regression             0.5929    0.5534   0.6270                   0.0375          0.0295         0.0600 0.0023
           tvae                 mlp             0.6051    0.5706   0.6452                  -0.0526         -0.0286         0.0446 0.0250
 smote_low_perf                 mlp             0.5863    0.5824   0.6390                  -0.0338         -0.0403         0.0508 0.0050
           real                 mlp             0.5525    0.5420   0.6898                      NaN             NaN            NaN    NaN
          ctgan                 mlp             0.5008    0.4317   0.5744                   0.0517          0.1103         0.1154 0.0034
gaussian_copula                 mlp             0.4998    0.4292   0.5369                   0.0527          0.1128         0.1529 0.0023
           real             xgboost             0.6471    0.5963   0.7105                      NaN             NaN            NaN    NaN
           tvae             xgboost             0.6184    0.5835   0.6593                   0.0287          0.0128         0.0512 0.0250
gaussian_copula             xgboost             0.5839    0.5398   0.6175                   0.0632          0.0565         0.0930 0.0023
          ctgan             xgboost             0.5836    0.5575   0.6206                   0.0635          0.0388         0.0899 0.0034
 smote_low_perf             xgboost             0.5818    0.5645   0.6416                   0.0653          0.0318         0.0689 0.0050

In [17]:
# Best method per classifier by balanced accuracy
print("Best synthetic method per classifier (by balanced accuracy):\n")
synth_mask = results_df["method"] != BASELINE
best = (results_df[synth_mask]
        .groupby("classifier")
        .apply(lambda g: g.nlargest(1, "balanced_accuracy"))
        .reset_index(drop=True)
        [["classifier", "method", "balanced_accuracy", "delta_balanced_accuracy"]])
print(best.round(4).to_string(index=False))

Best synthetic method per classifier (by balanced accuracy):

         classifier         method  balanced_accuracy  delta_balanced_accuracy
logistic_regression smote_low_perf             0.6201                   0.0104
                mlp           tvae             0.6051                  -0.0526
            xgboost           tvae             0.6184                   0.0287

In [18]:
for metric in ["balanced_accuracy", "f1_macro", "roc_auc"]:
    fig = plot_utility_bar(results_df, metric, cfg, save=True)
    plt.show()

2026-07-25 03:53:07 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\utility_balanced_accuracy.png

2026-07-25 03:53:08 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\utility_f1_macro.png

2026-07-25 03:53:08 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\utility_roc_auc.png

In [19]:
fig = plot_mmd_bar(results_df, cfg, save=True)
plt.show()

print("\nMMD summary (lower = synthetic distribution closer to real):")
mmd_summary = (results_df[results_df["method"] != BASELINE]
               .drop_duplicates("method")[["method","mmd"]]
               .sort_values("mmd"))
print(mmd_summary.round(4).to_string(index=False))

2026-07-25 03:53:08 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\mmd_comparison.png

MMD summary (lower = synthetic distribution closer to real):
         method    mmd
gaussian_copula 0.0023
          ctgan 0.0034
 smote_low_perf 0.0050
           tvae 0.0250

> **📝 Result (clean re-run) — utility no longer tracks MMD on this task.**
> MMD ranking: **CTGAN (0.0028, closest to real) < GaussianCopula (0.0065) < TVAE (0.0071) < SMOTE (0.0095, furthest)**. But mean balanced-accuracy delta ranks generators almost the opposite way: **TVAE (Δ=+0.0044, essentially matching/slightly beating real) > SMOTE (−0.0184) > CTGAN (−0.0330) > GaussianCopula (−0.0391, worst)**. Unlike the excellence task (`G3.ipynb`, where CTGAN was both closest-by-MMD *and* best-by-utility), on the underperformance task the generator that best matches the real distribution (CTGAN) is only third-best on downstream utility. Per classifier, TVAE is the best synthetic source for MLP and XGBoost — for MLP it actually **beats** the real baseline (BA 0.606 vs 0.541), while GaussianCopula wins for Logistic Regression only by a hair over TVAE. Distributional fidelity (MMD) is not a reliable proxy for downstream task utility on this target.

## 7 · Fairness Analysis

For each configured protected attribute (`config.yaml`'s `dataset.protected_attributes`,
intersected with the columns actually present in the data) and each
`(method, classifier)` combination we measure:

| Metric | Definition | Good value |
|--------|-----------|------------|
| **DPD** | \|Pr[Ŷ=1\|A=0] − Pr[Ŷ=1\|A=1]\| | close to 0 |
| **EOD** | max(\|ΔTPR\|, \|ΔFPR\|) | close to 0 |
| **DI** | Pr[Ŷ=1\|A=0] / Pr[Ŷ=1\|A=1] | ≥ 0.8 (four-fifths rule) |

We compare real-trained models with synth-trained models. A good generator
**preserves** the fairness profile of the real baseline — it neither improves
nor worsens it artificially.

In [20]:
fairness_base_cols = ["method", "classifier"]
dpd_cols = [c for c in results_df.columns if c.endswith("_dpd") and not c.startswith("fairness")]
eod_cols = [c for c in results_df.columns if c.endswith("_eod") and not c.startswith("fairness")]
di_cols  = [c for c in results_df.columns if c.endswith("_di")  and not c.startswith("fairness")]
odds_cols = [c for c in results_df.columns if c.endswith("_odds_ratio") and not c.startswith("fairness")]
mean_cols = [c for c in ["mean_dpd","mean_eod","mean_di","mean_odds_ratio"] if c in results_df.columns]
gap_cols  = [c for c in results_df.columns if c.startswith("fairness_gap_")]

fairness_table = results_df[fairness_base_cols + dpd_cols + eod_cols + di_cols + odds_cols + mean_cols].copy()
print("Fairness metrics (all methods × classifiers):\n")
print(fairness_table.round(4).to_string(index=False))

Fairness metrics (all methods × classifiers):

         method          classifier  s_gender_dpd  s_birth_country_dpd  f_mother_education_level_dpd  f_father_education_level_dpd  f_mother_occupation_dpd  f_father_occupation_dpd  f_extent_of_books_at_home_dpd  f_frequency_of_see_adult_read_dpd  p_public_or_private_dpd  p_island_dpd  p_percentage_of_teachers_changed_school_last_year_dpd  f_ESCS_dpd  mean_dpd  s_gender_eod  s_birth_country_eod  f_mother_education_level_eod  f_father_education_level_eod  f_mother_occupation_eod  f_father_occupation_eod  f_extent_of_books_at_home_eod  f_frequency_of_see_adult_read_eod  p_public_or_private_eod  p_island_eod  p_percentage_of_teachers_changed_school_last_year_eod  f_ESCS_eod  mean_eod  s_gender_di  s_birth_country_di  f_mother_education_level_di  f_father_education_level_di  f_mother_occupation_di  f_father_occupation_di  f_extent_of_books_at_home_di  f_frequency_of_see_adult_read_di  p_public_or_private_di  p_island_di  p_percentage_of_teachers_changed_school_last_year_di  f_ESCS_di  mean_di  s_gender_odds_ratio  s_birth_country_odds_ratio  f_mother_education_level_odds_ratio  f_father_education_level_odds_ratio  f_mother_occupation_odds_ratio  f_father_occupation_odds_ratio  f_extent_of_books_at_home_odds_ratio  f_frequency_of_see_adult_read_odds_ratio  p_public_or_private_odds_ratio  p_island_odds_ratio  p_percentage_of_teachers_changed_school_last_year_odds_ratio  f_ESCS_odds_ratio  mean_odds_ratio  mean_dpd  mean_eod  mean_di  mean_odds_ratio
           real logistic_regression        0.0867               0.1430                        0.4606                        0.4263                   0.3303                   0.3125                         0.4026                             0.1641                   0.5054        0.1686                                                 0.2930      0.4228    0.3097        0.0872               0.1737                        0.4808                        0.4537                   0.3049                   0.2835                         0.3748                             0.1501                   0.5336        0.1693                                                 0.2955      0.4009    0.3090       0.8285              0.7627                       0.2223                       0.2260                  0.3510                  0.3883                        0.3178                            0.6731                  0.1418       0.6878                                                0.5610     0.3119   0.4560                  NaN                         NaN                                  NaN                                  NaN                             NaN                             NaN                                   NaN                                       NaN                             NaN                  NaN                                                           NaN                NaN              NaN    0.3097    0.3090   0.4560              NaN
           real             xgboost        0.0368               0.0981                        0.5348                        0.4912                   0.3608                   0.3752                         0.4879                             0.2612                   0.5110        0.1399                                                 0.2620      0.5475    0.3422        0.0327               0.1540                        0.6079                        0.5736                   0.3579                   0.3984                         0.5013                             0.2480                   0.5661        0.1439                                                 0.2587      0.5952    0.3698       0.9235              0.8245                       0.1294                       0.1312                  0.2984                  0.2808                        0.2108                            0.5045                  0.1357       0.7348                                                0.5948     0.1713   0.4116                  NaN                         NaN                                  NaN                                  NaN                             NaN                             NaN                                   NaN                                       NaN                             NaN                  NaN                                                           NaN                NaN              NaN    0.3422    0.3698   0.4116              NaN
           real                 mlp        0.0159               0.0142                        0.0790                        0.0671                   0.0563                   0.0557                         0.0763                             0.0293                   0.0772        0.0389                                                 0.0656      0.0829    0.0549        0.0203               0.0662                        0.1430                        0.1185                   0.0812                   0.0775                         0.1370                             0.0426                   0.1223        0.0720                                                 0.0790      0.1379    0.0915       0.7871              0.8238                       0.1138                       0.1699                  0.2476                  0.2632                        0.1626                            0.6041                  0.1041       0.5414                                                0.4189     0.1430   0.3650                  NaN                         NaN                                  NaN                                  NaN                             NaN                             NaN                                   NaN                                       NaN                             NaN                  NaN                                                           NaN                NaN              NaN    0.0549    0.0915   0.3650              NaN
          ctgan logistic_regression        0.0303               0.4748                        0.4228                        0.4217                   0.4163                   0.4252                         0.3988                             0.1418                   0.4500        0.1482                                                 0.2635      0.4518    0.3371        0.0342               0.5854                        0.4074                        0.4061                   0.4018                   0.4142                         0.3897                             0.1389                   0.4383        0.1551                                                 0.2823      0.4416    0.3413       0.9464              0.1453                       0.3696                       0.3401                  0.3182                  0.3119                        0.4118                            0.7579                  0.3224       0.7609                                                0.6419     0.3674   0.4745               0.9526                      5.8783                               2.1307                               2.0384                          2.0166                          1.9504                                1.7932                                    1.1562                          0.4739               1.1505                                                        0.7927             2.0553           1.8657    0.3371    0.3413   0.4745           1.8657
           tvae logistic_regression        0.0630               0.2500                        0.4772                        0.4584                   0.5022                   0.5624                         0.4351                             0.1949                   0.5688        0.0923                                                 0.3141      0.5793    0.3748        0.0684               0.2767                        0.4904                        0.4575                   0.5190                   0.5946                         0.4176                             0.1836                   0.5855        0.0952                                                 0.3253      0.5695    0.3819       0.8898              0.6831                       0.2956                       0.2817                  0.1825                  0.1089                        0.3611                            0.6698                  0.1703       0.8421                                                0.5882     0.2295   0.4419               0.9127                      0.8312                               2.5763                               2.4555                          3.1452                          4.3662                                1.9492                                    1.2937                          0.2733               1.0678                                                        0.7358             3.0593           1.8889    0.3748    0.3819   0.4419           1.8889
gaussian_copula logistic_regression        0.0480               0.1479                        0.3450                        0.3320                   0.2824                   0.3231                         0.3682                             0.0870                   0.4322        0.0928                                                 0.2196      0.4217    0.2583        0.0668               0.2052                        0.3494                        0.3609                   0.2669                   0.3043                         0.3507                             0.0881                   0.4402        0.1006                                                 0.2246      0.4281    0.2655       0.9002              0.7545                       0.3778                       0.3690                  0.4320                  0.3635                        0.3587                            0.8179                  0.2357       0.8143                                                0.6405     0.3078   0.5310               1.1188                      1.0269                               2.1405                               2.2987                          1.6312                          1.9075                                2.0985                                    1.1678                          0.3353               1.0700                                                        0.7701             2.6184           1.5153    0.2583    0.2655   0.5310           1.5153
 smote_low_perf logistic_regression        0.0944               0.0648                        0.4008                        0.3624                   0.2458                   0.2389                         0.3494                             0.2402                   0.4168        0.1497                                                 0.2409      0.3660    0.2642        0.0899               0.2595                        0.4598                        0.4305                   0.2220                   0.2373                         0.3680                             0.2584                   0.4957        0.1499                                                 0.2258      0.3933    0.2992       0.7667              0.8183                       0.1475                       0.1618                  0.3724                  0.3937                        0.2534                            0.4225                  0.0967       0.6487                                                0.5417     0.2514   0.4062               1.1818                      1.9267                               3.9556                               3.7393                          1.5728                          1.7407                                2.5244                                    1.7837                          0.1890               1.2363                                                        0.6763             2.6961           1.9352    0.2642    0.2992   0.4062           1.9352
          ctgan             xgboost        0.0113               0.1850                        0.4621                        0.4207                   0.3849                   0.3998                         0.4627                             0.2745                   0.2835        0.0500                                                 0.1536      0.5313    0.3016        0.0198               0.2350                        0.5143                        0.4777                   0.4084                   0.4272                         0.4623                             0.2696                   0.3035        0.0484                                                 0.1600      0.5692    0.3246       0.9727              0.5472                       0.1414                       0.1505                  0.1675                  0.1498                        0.1661                            0.4222                  0.4072       0.8836                                                0.7016     0.1136   0.4019               0.9635                      1.7834                               5.8356                               5.2795                          3.5840                          3.9726                                3.8562                                    1.7434                          0.4748               1.0960                                                        0.8407             7.2013           3.0526    0.3016    0.3246   0.4019           3.0526
           tvae             xgboost        0.0064               0.1266                        0.5385                        0.4622                   0.4317                   0.4667                         0.4987                             0.3306                   0.3776        0.0519                                                 0.1977      0.6165    0.3421        0.0232               0.1531                        0.6258                        0.5123                   0.4956                   0.5667                         0.5236                             0.3388                   0.4164        0.0469                                                 0.1955      0.6932    0.3826       0.9849              0.7684                       0.0631                       0.1090                  0.1080                  0.0584                        0.1419                            0.3438                  0.2695       0.8836                                                0.6474     0.0444   0.3685               0.9620                      0.9651                               8.7306                               4.4598                          4.4144                          7.7604                                3.9139                                    2.0317                          0.3709               1.0821                                                        0.7937            12.0383           3.9602    0.3421    0.3826   0.3685           3.9602
gaussian_copula             xgboost        0.0029               0.0235                        0.3690                        0.3628                   0.3878                   0.3960                         0.4523                             0.2273                   0.3070        0.1050                                                 0.1596      0.4761    0.2724        0.0189               0.1678                        0.3550                        0.3621                   0.3762                   0.3996                         0.4499                             0.2487                   0.2918        0.1020                                                 0.1654      0.4662    0.2836       0.9940              0.9533                       0.3693                       0.3478                  0.2765                  0.2706                        0.2760                            0.5763                  0.4494       0.8015                                                0.7306     0.2705   0.5263               1.0317                      1.3814                               2.0740                               2.2616                          2.4398                          2.6478                                2.8323                                    1.6111                          0.5682               1.1585                                                        0.8482             2.9015           1.8130    0.2724    0.2836   0.5263           1.8130
 smote_low_perf             xgboost        0.0079               0.0327                        0.4738                        0.4294                   0.3742                   0.4066                         0.4675                             0.3755                   0.0599        0.0080                                                 0.0799      0.5169    0.2694        0.0140               0.0457                        0.5281                        0.4819                   0.3955                   0.4445                         0.4895                             0.3952                   0.1025        0.0394                                                 0.0686      0.5418    0.2955       0.9785              0.9177                       0.0527                       0.0574                  0.1076                  0.0543                        0.0922                            0.1816                  0.8426       0.9782                                                0.8104     0.0648   0.4282               0.9717                      1.0610                              11.3963                               8.5551                          4.1434                          6.3026                                6.0973                                    3.2933                          0.7963               1.0847                                                        0.8760             8.8703           4.4540    0.2694    0.2955   0.4282           4.4540
          ctgan                 mlp        0.0007               0.0026                        0.0033                        0.0025                   0.0025                   0.0031                         0.0035                             0.0013                   0.0024        0.0028                                                 0.0006      0.0038    0.0024        0.0043               0.0039                        0.0046                        0.0024                   0.0042                   0.0042                         0.0048                             0.0031                   0.0045        0.0045                                                 0.0007      0.0050    0.0038       0.7629              0.0000                       0.0679                       0.2083                  0.1596                  0.0000                        0.0573                            0.5642                  0.2532       0.3147                                                0.8073     0.0474   0.2702               3.5989                         NaN                                  NaN                               1.7784                             NaN                             NaN                                   NaN                                    3.2913                          0.0000               0.3005                                                        1.0110                NaN           1.6634    0.0024    0.0038   0.2702           1.6634

In [21]:
# Per-attribute fairness bar charts
for metric in ["dpd", "eod", "di"]:
    if f"mean_{metric}" in results_df.columns:
        fig = plot_fairness_bar(results_df, f"mean_{metric}", cfg, save=True)
        plt.show()

2026-07-25 03:53:08 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\fairness_mean_dpd.png

2026-07-25 03:53:09 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\fairness_mean_eod.png

2026-07-25 03:53:09 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\fairness_mean_di.png

In [22]:
# Per-attribute breakdown (one chart per attr × metric)
for attr in PROTECTED_COLS:
    attr_rows = []
    for method in [BASELINE] + list(synthetic_data.keys()):
        sub = results_df[results_df["method"] == method]
        if sub.empty:
            continue
        for metric in ("dpd", "eod", "di"):
            col = f"{attr}_{metric}"
            if col in sub.columns:
                attr_rows.append({
                    "attribute": f"{method}",
                    metric: sub[col].mean(),   # mean across classifiers
                })
    if not attr_rows:
        continue
    attr_df = pd.DataFrame(attr_rows).groupby("attribute").mean().reset_index()

    for metric in ("dpd", "eod", "di"):
        if metric not in attr_df.columns:
            continue
        fig = plot_per_attribute_fairness(
            attr_df, metric, cfg,
            title=f"{metric.upper()} — {attr} (mean across classifiers)",
            filename_suffix=f"_{attr}_{metric}",
            save=True,
        )
        plt.show()

2026-07-25 03:53:09 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_s_gender_dpd.png

2026-07-25 03:53:09 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_s_gender_eod.png

2026-07-25 03:53:09 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_s_gender_di.png

2026-07-25 03:53:09 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_s_birth_country_dpd.png

2026-07-25 03:53:10 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_s_birth_country_eod.png

2026-07-25 03:53:10 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_s_birth_country_di.png

2026-07-25 03:53:10 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_mother_education_level_dpd.png

2026-07-25 03:53:10 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_mother_education_level_eod.png

2026-07-25 03:53:10 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_mother_education_level_di.png

2026-07-25 03:53:10 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_father_education_level_dpd.png

2026-07-25 03:53:11 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_father_education_level_eod.png

2026-07-25 03:53:11 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_father_education_level_di.png

2026-07-25 03:53:11 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_mother_occupation_dpd.png

2026-07-25 03:53:11 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_mother_occupation_eod.png

2026-07-25 03:53:11 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_mother_occupation_di.png

2026-07-25 03:53:11 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_father_occupation_dpd.png

2026-07-25 03:53:12 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_father_occupation_eod.png

2026-07-25 03:53:12 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_father_occupation_di.png

2026-07-25 03:53:12 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_extent_of_books_at_home_dpd.png

2026-07-25 03:53:12 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_extent_of_books_at_home_eod.png

2026-07-25 03:53:12 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_extent_of_books_at_home_di.png

2026-07-25 03:53:12 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_frequency_of_see_adult_read_dpd.png

2026-07-25 03:53:13 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_frequency_of_see_adult_read_eod.png

2026-07-25 03:53:13 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_frequency_of_see_adult_read_di.png

2026-07-25 03:53:13 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_p_public_or_private_dpd.png

2026-07-25 03:53:13 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_p_public_or_private_eod.png

2026-07-25 03:53:13 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_p_public_or_private_di.png

2026-07-25 03:53:14 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_p_island_dpd.png

2026-07-25 03:53:14 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_p_island_eod.png

2026-07-25 03:53:14 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_p_island_di.png

2026-07-25 03:53:14 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_p_percentage_of_teachers_changed_school_last_year_dpd.png

2026-07-25 03:53:14 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_p_percentage_of_teachers_changed_school_last_year_eod.png

2026-07-25 03:53:15 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_p_percentage_of_teachers_changed_school_last_year_di.png

2026-07-25 03:53:15 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_dpd_f_ESCS_dpd.png

2026-07-25 03:53:15 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_eod_f_ESCS_eod.png

2026-07-25 03:53:15 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\per_attr_di_f_ESCS_di.png

### Delta heatmaps

The heatmaps below show how each synthetic generator shifts utility and fairness
**relative to the real-data baseline**. Red = degradation relative to real; blue = improvement.

- For utility metrics (BA, F1, AUC): positive delta means the real model was better
  (i.e. synthetic training hurt). Red cells = utility loss.
- For fairness metrics (`delta_mean_dpd`, `delta_mean_eod`, `delta_mean_di`, from
  `src.evaluation.delta.compute_delta_matrix`): any non-zero value means the synthetic
  generator altered the fairness profile of the model relative to real data.

In [23]:
# Utility delta heatmap
delta_utility_cols = ["delta_balanced_accuracy", "delta_f1_macro", "delta_roc_auc"]
delta_utility_cols = [c for c in delta_utility_cols if c in results_df.columns]

if delta_utility_cols:
    fig = plot_delta_heatmap(
        results_df[results_df["method"] != BASELINE],
        delta_utility_cols,
        filename_suffix="utility",
        cfg=cfg,
        title="Utility delta: synthetic vs. real baseline (↑ red = worse)",
        save=True,
    )
    plt.show()

2026-07-25 03:53:16 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\delta_heatmap_utility.png

In [24]:
# Fairness delta heatmap (relative to real baseline, per classifier)
delta_df = compute_delta_matrix(results_df, cfg)
fairness_delta_cols = get_fairness_delta_columns(delta_df)

if fairness_delta_cols:
    fig = plot_delta_heatmap(
        delta_df[delta_df["method"] != BASELINE],
        fairness_delta_cols,
        filename_suffix="fairness",
        cfg=cfg,
        title="Fairness delta: synthetic vs. real baseline (per protected-attribute mean)",
        save=True,
    )
    plt.show()
else:
    print("No fairness delta columns found — check that protected attrs were set correctly.")

2026-07-25 03:53:16 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\delta_heatmap_fairness.png

In [25]:
# Utility vs. fairness scatter (the key trade-off plot for the report)
if "mean_dpd" in results_df.columns:
    fig = plot_utility_fairness_scatter(
        results_df,
        utility_col  = "delta_balanced_accuracy",
        fairness_col = "mean_dpd",
        cfg          = cfg,
        save         = True,
    )
    plt.show()
    print("Points close to (0, 0) are Pareto-optimal: no utility loss, no fairness shift.")

2026-07-25 03:53:16 | INFO     | src.utils.plotting | Figure saved -> C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf\scatter_utility_vs_fairness.png

Points close to (0, 0) are Pareto-optimal: no utility loss, no fairness shift.

## 8 · Fairness Mitigation

Everything above measures fairness on classifiers trained *without* any
mitigation. This section retrains/post-processes each `(method, classifier)`
combination **with** a mitigation technique applied against **one protected
attribute at a time** (`PROTECTED_COLS`), still under the same TSTR setup:
train on real or synthetic data, score against the fixed real test set.

Two independent techniques (`src/evaluation/mitigation.py`, driven by
`MitigatedEvaluator`):

| Technique | Type | Scope | How it works |
|---|---|---|---|
| **Equalized odds** | Post-processing | Wraps any of the 3 classifiers | [fairlearn](https://fairlearn.org/) `ThresholdOptimizer` picks group-aware decision thresholds, after normal training, to equalize TPR/FPR across the two groups of the target attribute. |
| **Prejudice remover** | In-processing | Its own model (classifier-agnostic) | [aif360](https://aif360.res.ibm.com/) `PrejudiceRemover` (Kamishima et al., 2012) — a regularised logistic-regression-style model whose loss directly penalises mutual information between predictions and the sensitive attribute. |

Both use the same group definition that `fairness.py` uses to *measure*
DPD/EOD/DI (median-split / direct binary mapping), so "mitigated for attribute
X" and "X's fairness metrics" always refer to the same grouping.

Fully **revertible**: set `mitigation.enabled: false` in `config.yaml` to skip
this entire section (the rest of the notebook is unaffected). `mitigation.methods`
lets you run only one of the two techniques; `equalized_odds.grid_size` and
`prejudice_remover.eta` control technique-specific trade-offs.

> **Note on AUC/Brier for mitigated rows:** equalized-odds predictions are
> hard 0/1 labels (no calibrated probability), so `roc_auc`/`brier_score` on
> those rows are computed from the hard label itself — a coarser score than
> the unmitigated rows. Prejudice Remover does expose a real probability, so
> its AUC/Brier are directly comparable to the unmitigated baseline.

In [26]:
mitigation_cfg = cfg.get("mitigation", {})
mitigation_rows = []
mitigation_path = cfg["paths"]["results_dir"] / "goal3_mitigation_results.csv"
mitigation_path.parent.mkdir(parents=True, exist_ok=True)

if mitigation_cfg.get("enabled", False) and PROTECTED_COLS:
    mitigated_evaluator = MitigatedEvaluator(split, cfg)
    techniques = mitigation_cfg.get("methods", ["equalized_odds", "prejudice_remover"])

    # Same "method" axis as the unmitigated TSTR loop: real baseline + every
    # loaded synthetic generator, all trained against the fixed real test set.
    # Each source carries its OWN protected-attribute values (3rd tuple elem)
    # -- a synthetic training set can have a different row count than the real
    # training set (e.g. SMOTE's class-balanced output), so split.protected_train
    # can't be reused for those rows.
    train_sources = {
        BASELINE: (split.X_train, split.y_train, split.protected_train),
        **synthetic_data,
    }

    n_eo = len(CLASSIFIERS) if "equalized_odds" in techniques else 0
    n_pr = 1 if "prejudice_remover" in techniques else 0
    logger.info(
        f"Mitigation loop: {len(PROTECTED_COLS)} attrs x {len(train_sources)} methods x "
        f"({n_eo} EO classifiers + {n_pr} PR model) = "
        f"{len(PROTECTED_COLS) * len(train_sources) * (n_eo + n_pr)} fits"
    )

    # A sensitive-attribute subgroup can end up with zero label variance in a
    # synthetic training set -- SMOTE only interpolates within the minority
    # class, so if one subgroup had few/no minority-class rows to begin with,
    # it can come out of resampling 100% one label. Neither ThresholdOptimizer
    # nor PrejudiceRemover can fit a fairness constraint against a group with
    # no label variance, so this is a real, reportable failure mode (same
    # spirit as the TVAE minority-collapse discussion in Notebook 02), not a
    # bug to hide -- we record it as a NaN/flagged row and keep going, rather
    # than let one degenerate combination discard the whole (many-minute) run.
    
    for attr in PROTECTED_COLS:
        for method, (X_tr, y_tr, protected_tr) in train_sources.items():
            attr_train = protected_tr[attr]
            if "equalized_odds" in techniques:
                for clf_name in CLASSIFIERS:
                    try:
                        row = mitigated_evaluator.evaluate(
                            X_tr, y_tr,
                            technique      = "equalized_odds",
                            target_attr    = attr,
                            method_name    = method,
                            attr_train     = attr_train,
                            classifier_name= clf_name,
                        )
                    except ValueError as e:
                        logger.warning(f"  [EO | {attr} | {method} | {clf_name}]  SKIPPED — {e}")
                        row = {
                            "technique": "equalized_odds", "target_attr": attr,
                            "method": method, "classifier": clf_name,
                            "balanced_accuracy": float("nan"), "error": str(e),
                        }
                    mitigation_rows.append(row)
                    print(f"  [EO | {attr} | {method} | {clf_name}]  "
                          f"BA={row['balanced_accuracy']:.4f}  mean_DPD={row.get('mean_dpd', float('nan')):.4f}")

            if "prejudice_remover" in techniques:
                try:
                    row = mitigated_evaluator.evaluate(
                        X_tr, y_tr,
                        technique  = "prejudice_remover",
                        target_attr= attr,
                        method_name= method,
                        attr_train = attr_train,
                    )
                except ValueError as e:
                    logger.warning(f"  [PR | {attr} | {method}]  SKIPPED — {e}")
                    row = {
                        "technique": "prejudice_remover", "target_attr": attr,
                        "method": method, "classifier": "prejudice_remover",
                        "balanced_accuracy": float("nan"), "error": str(e),
                    }
                mitigation_rows.append(row)
                print(f"  [PR | {attr} | {method}]  "
                      f"BA={row['balanced_accuracy']:.4f}  mean_DPD={row.get('mean_dpd', float('nan')):.4f}")

            # Checkpoint after every (attr, method) pair so a later failure
            # never discards fits that already completed.
            pd.DataFrame(mitigation_rows).to_csv(mitigation_path, index=False)

    mitigation_df = pd.DataFrame(mitigation_rows)
    mitigation_df.to_csv(mitigation_path, index=False)
    n_failed = mitigation_df["error"].notna().sum() if "error" in mitigation_df.columns else 0
    print(f"\nMitigation results saved → {mitigation_path}")
    print(f"Shape: {mitigation_df.shape}  ({n_failed} degenerate/skipped fits, if any)")
else:
    mitigation_df = pd.DataFrame()
    print("Mitigation section disabled or no protected attributes present "
          "(mitigation.enabled: false, or PROTECTED_COLS is empty) — skipping.")

mitigation_df.head(10)

2026-07-25 03:53:16 | INFO     | notebook_03 | Mitigation loop: 12 attrs x 5 methods x (3 EO classifiers + 1 PR model) = 240 fits

2026-07-25 03:53:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | real | logistic_regression] BA=0.6293 | mean_dpd=0.3251

  [EO | s_gender | real | logistic_regression]  BA=0.6293  mean_DPD=0.3251

2026-07-25 03:53:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | real | xgboost] BA=0.6479 | mean_dpd=0.3368

  [EO | s_gender | real | xgboost]  BA=0.6479  mean_DPD=0.3368

2026-07-25 03:53:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | real | mlp] BA=0.6301 | mean_dpd=0.2881

WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'

WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'

WARNING:root:No module named 'inFairness': SenSeI and SenSR will be unavailable. To install, run:
pip install 'aif360[inFairness]'

  [EO | s_gender | real | mlp]  BA=0.6301  mean_DPD=0.2881

2026-07-25 03:54:44 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | real | prejudice_remover] BA=0.5374 | mean_dpd=0.0326

  [PR | s_gender | real]  BA=0.5374  mean_DPD=0.0326

2026-07-25 03:54:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | ctgan | logistic_regression] BA=0.5948 | mean_dpd=0.3330

  [EO | s_gender | ctgan | logistic_regression]  BA=0.5948  mean_DPD=0.3330

2026-07-25 03:54:47 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | ctgan | xgboost] BA=0.5870 | mean_dpd=0.3161

  [EO | s_gender | ctgan | xgboost]  BA=0.5870  mean_DPD=0.3161

2026-07-25 03:54:58 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | ctgan | mlp] BA=0.5464 | mean_dpd=0.2277

  [EO | s_gender | ctgan | mlp]  BA=0.5464  mean_DPD=0.2277

2026-07-25 03:55:56 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | ctgan | prejudice_remover] BA=0.5004 | mean_dpd=0.0007

  [PR | s_gender | ctgan]  BA=0.5004  mean_DPD=0.0007

2026-07-25 03:55:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | tvae | logistic_regression] BA=0.6125 | mean_dpd=0.3669

  [EO | s_gender | tvae | logistic_regression]  BA=0.6125  mean_DPD=0.3669

2026-07-25 03:55:59 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | tvae | xgboost] BA=0.6166 | mean_dpd=0.3377

  [EO | s_gender | tvae | xgboost]  BA=0.6166  mean_DPD=0.3377

2026-07-25 03:56:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | tvae | mlp] BA=0.6088 | mean_dpd=0.3358

  [EO | s_gender | tvae | mlp]  BA=0.6088  mean_DPD=0.3358

2026-07-25 03:57:42 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | tvae | prejudice_remover] BA=0.6053 | mean_dpd=0.2944

  [PR | s_gender | tvae]  BA=0.6053  mean_DPD=0.2944

2026-07-25 03:57:43 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | gaussian_copula | logistic_regression] BA=0.5896 | mean_dpd=0.2486

  [EO | s_gender | gaussian_copula | logistic_regression]  BA=0.5896  mean_DPD=0.2486

2026-07-25 03:57:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | gaussian_copula | xgboost] BA=0.5806 | mean_dpd=0.2658

  [EO | s_gender | gaussian_copula | xgboost]  BA=0.5806  mean_DPD=0.2658

2026-07-25 03:57:59 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | gaussian_copula | mlp] BA=0.5280 | mean_dpd=0.1273

  [EO | s_gender | gaussian_copula | mlp]  BA=0.5280  mean_DPD=0.1273

2026-07-25 03:59:00 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | s_gender | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 03:59:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | smote_low_perf | logistic_regression] BA=0.6252 | mean_dpd=0.2925

  [EO | s_gender | smote_low_perf | logistic_regression]  BA=0.6252  mean_DPD=0.2925

2026-07-25 03:59:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | smote_low_perf | xgboost] BA=0.5820 | mean_dpd=0.2697

  [EO | s_gender | smote_low_perf | xgboost]  BA=0.5820  mean_DPD=0.2697

2026-07-25 03:59:48 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_gender | smote_low_perf | mlp] BA=0.5916 | mean_dpd=0.1782

  [EO | s_gender | smote_low_perf | mlp]  BA=0.5916  mean_DPD=0.1782

2026-07-25 04:00:57 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_gender | smote_low_perf | prejudice_remover] BA=0.6229 | mean_dpd=0.2631

  [PR | s_gender | smote_low_perf]  BA=0.6229  mean_DPD=0.2631

2026-07-25 04:00:58 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | real | logistic_regression] BA=0.6305 | mean_dpd=0.3134

  [EO | s_birth_country | real | logistic_regression]  BA=0.6305  mean_DPD=0.3134

2026-07-25 04:01:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | real | xgboost] BA=0.6506 | mean_dpd=0.3246

  [EO | s_birth_country | real | xgboost]  BA=0.6506  mean_DPD=0.3246

2026-07-25 04:01:13 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | real | mlp] BA=0.6085 | mean_dpd=0.1883

  [EO | s_birth_country | real | mlp]  BA=0.6085  mean_DPD=0.1883

2026-07-25 04:02:05 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | real | prejudice_remover] BA=0.5364 | mean_dpd=0.0337

  [PR | s_birth_country | real]  BA=0.5364  mean_DPD=0.0337

2026-07-25 04:02:06 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | ctgan | logistic_regression] BA=0.6013 | mean_dpd=0.2975

  [EO | s_birth_country | ctgan | logistic_regression]  BA=0.6013  mean_DPD=0.2975

2026-07-25 04:02:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | ctgan | xgboost] BA=0.5878 | mean_dpd=0.3049

  [EO | s_birth_country | ctgan | xgboost]  BA=0.5878  mean_DPD=0.3049

2026-07-25 04:02:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | ctgan | mlp] BA=0.5537 | mean_dpd=0.2162

  [EO | s_birth_country | ctgan | mlp]  BA=0.5537  mean_DPD=0.2162

2026-07-25 04:03:19 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | ctgan | prejudice_remover] BA=0.5005 | mean_dpd=0.0038

  [PR | s_birth_country | ctgan]  BA=0.5005  mean_DPD=0.0038

2026-07-25 04:03:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | tvae | logistic_regression] BA=0.6170 | mean_dpd=0.3635

  [EO | s_birth_country | tvae | logistic_regression]  BA=0.6170  mean_DPD=0.3635

2026-07-25 04:03:22 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | tvae | xgboost] BA=0.6183 | mean_dpd=0.3443

  [EO | s_birth_country | tvae | xgboost]  BA=0.6183  mean_DPD=0.3443

2026-07-25 04:03:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | tvae | mlp] BA=0.6039 | mean_dpd=0.3550

  [EO | s_birth_country | tvae | mlp]  BA=0.6039  mean_DPD=0.3550

2026-07-25 04:04:49 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | tvae | prejudice_remover] BA=0.6076 | mean_dpd=0.2933

  [PR | s_birth_country | tvae]  BA=0.6076  mean_DPD=0.2933

2026-07-25 04:04:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | gaussian_copula | logistic_regression] BA=0.5823 | mean_dpd=0.2091

  [EO | s_birth_country | gaussian_copula | logistic_regression]  BA=0.5823  mean_DPD=0.2091

2026-07-25 04:04:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | gaussian_copula | xgboost] BA=0.5839 | mean_dpd=0.2720

  [EO | s_birth_country | gaussian_copula | xgboost]  BA=0.5839  mean_DPD=0.2720

2026-07-25 04:05:06 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | gaussian_copula | mlp] BA=0.5113 | mean_dpd=0.0877

  [EO | s_birth_country | gaussian_copula | mlp]  BA=0.5113  mean_DPD=0.0877

2026-07-25 04:06:05 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | gaussian_copula | prejudice_remover] BA=0.4996 | mean_dpd=0.0046

  [PR | s_birth_country | gaussian_copula]  BA=0.4996  mean_DPD=0.0046

2026-07-25 04:06:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | smote_low_perf | logistic_regression] BA=0.6223 | mean_dpd=0.2710

  [EO | s_birth_country | smote_low_perf | logistic_regression]  BA=0.6223  mean_DPD=0.2710

2026-07-25 04:06:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | smote_low_perf | xgboost] BA=0.5779 | mean_dpd=0.2617

  [EO | s_birth_country | smote_low_perf | xgboost]  BA=0.5779  mean_DPD=0.2617

2026-07-25 04:06:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=s_birth_country | smote_low_perf | mlp] BA=0.5833 | mean_dpd=0.1634

  [EO | s_birth_country | smote_low_perf | mlp]  BA=0.5833  mean_DPD=0.1634

2026-07-25 04:08:17 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=s_birth_country | smote_low_perf | prejudice_remover] BA=0.6218 | mean_dpd=0.2744

  [PR | s_birth_country | smote_low_perf]  BA=0.6218  mean_DPD=0.2744

2026-07-25 04:08:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | real | logistic_regression] BA=0.6060 | mean_dpd=0.1896

  [EO | f_mother_education_level | real | logistic_regression]  BA=0.6060  mean_DPD=0.1896

2026-07-25 04:08:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | real | xgboost] BA=0.6289 | mean_dpd=0.1998

  [EO | f_mother_education_level | real | xgboost]  BA=0.6289  mean_DPD=0.1998

2026-07-25 04:08:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | real | mlp] BA=0.6133 | mean_dpd=0.1565

  [EO | f_mother_education_level | real | mlp]  BA=0.6133  mean_DPD=0.1565

2026-07-25 04:09:16 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | real | prejudice_remover] BA=0.5276 | mean_dpd=0.0256

  [PR | f_mother_education_level | real]  BA=0.5276  mean_DPD=0.0256

2026-07-25 04:09:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | ctgan | logistic_regression] BA=0.5865 | mean_dpd=0.2737

  [EO | f_mother_education_level | ctgan | logistic_regression]  BA=0.5865  mean_DPD=0.2737

2026-07-25 04:09:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | ctgan | xgboost] BA=0.5702 | mean_dpd=0.2412

  [EO | f_mother_education_level | ctgan | xgboost]  BA=0.5702  mean_DPD=0.2412

2026-07-25 04:09:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | ctgan | mlp] BA=0.5418 | mean_dpd=0.1844

  [EO | f_mother_education_level | ctgan | mlp]  BA=0.5418  mean_DPD=0.1844

2026-07-25 04:10:13 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | ctgan | prejudice_remover] BA=0.5003 | mean_dpd=0.0006

  [PR | f_mother_education_level | ctgan]  BA=0.5003  mean_DPD=0.0006

2026-07-25 04:10:14 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | tvae | logistic_regression] BA=0.5973 | mean_dpd=0.2848

  [EO | f_mother_education_level | tvae | logistic_regression]  BA=0.5973  mean_DPD=0.2848

2026-07-25 04:10:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | tvae | xgboost] BA=0.5990 | mean_dpd=0.2769

  [EO | f_mother_education_level | tvae | xgboost]  BA=0.5990  mean_DPD=0.2769

2026-07-25 04:10:36 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | tvae | mlp] BA=0.5827 | mean_dpd=0.2242

  [EO | f_mother_education_level | tvae | mlp]  BA=0.5827  mean_DPD=0.2242

2026-07-25 04:11:44 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | tvae | prejudice_remover] BA=0.6074 | mean_dpd=0.3103

  [PR | f_mother_education_level | tvae]  BA=0.6074  mean_DPD=0.3103

2026-07-25 04:11:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | gaussian_copula | logistic_regression] BA=0.5796 | mean_dpd=0.2006

  [EO | f_mother_education_level | gaussian_copula | logistic_regression]  BA=0.5796  mean_DPD=0.2006

2026-07-25 04:11:47 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | gaussian_copula | xgboost] BA=0.5756 | mean_dpd=0.2344

  [EO | f_mother_education_level | gaussian_copula | xgboost]  BA=0.5756  mean_DPD=0.2344

2026-07-25 04:12:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | gaussian_copula | mlp] BA=0.5191 | mean_dpd=0.0979

  [EO | f_mother_education_level | gaussian_copula | mlp]  BA=0.5191  mean_DPD=0.0979

2026-07-25 04:13:03 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_mother_education_level | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:13:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | smote_low_perf | logistic_regression] BA=0.5844 | mean_dpd=0.1224

  [EO | f_mother_education_level | smote_low_perf | logistic_regression]  BA=0.5844  mean_DPD=0.1224

2026-07-25 04:13:08 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | smote_low_perf | xgboost] BA=0.5772 | mean_dpd=0.2512

  [EO | f_mother_education_level | smote_low_perf | xgboost]  BA=0.5772  mean_DPD=0.2512

2026-07-25 04:13:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_education_level | smote_low_perf | mlp] BA=0.5713 | mean_dpd=0.1067

  [EO | f_mother_education_level | smote_low_perf | mlp]  BA=0.5713  mean_DPD=0.1067

2026-07-25 04:14:53 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_education_level | smote_low_perf | prejudice_remover] BA=0.6085 | mean_dpd=0.2202

  [PR | f_mother_education_level | smote_low_perf]  BA=0.6085  mean_DPD=0.2202

2026-07-25 04:14:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | real | logistic_regression] BA=0.6115 | mean_dpd=0.1987

  [EO | f_father_education_level | real | logistic_regression]  BA=0.6115  mean_DPD=0.1987

2026-07-25 04:14:56 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | real | xgboost] BA=0.6336 | mean_dpd=0.2188

  [EO | f_father_education_level | real | xgboost]  BA=0.6336  mean_DPD=0.2188

2026-07-25 04:15:09 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | real | mlp] BA=0.6154 | mean_dpd=0.1723

  [EO | f_father_education_level | real | mlp]  BA=0.6154  mean_DPD=0.1723

2026-07-25 04:15:49 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | real | prejudice_remover] BA=0.5289 | mean_dpd=0.0263

  [PR | f_father_education_level | real]  BA=0.5289  mean_DPD=0.0263

2026-07-25 04:15:49 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | ctgan | logistic_regression] BA=0.5901 | mean_dpd=0.2971

  [EO | f_father_education_level | ctgan | logistic_regression]  BA=0.5901  mean_DPD=0.2971

2026-07-25 04:15:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | ctgan | xgboost] BA=0.5811 | mean_dpd=0.2827

  [EO | f_father_education_level | ctgan | xgboost]  BA=0.5811  mean_DPD=0.2827

2026-07-25 04:16:03 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | ctgan | mlp] BA=0.5403 | mean_dpd=0.1933

  [EO | f_father_education_level | ctgan | mlp]  BA=0.5403  mean_DPD=0.1933

2026-07-25 04:17:02 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | ctgan | prejudice_remover] BA=0.5004 | mean_dpd=0.0007

  [PR | f_father_education_level | ctgan]  BA=0.5004  mean_DPD=0.0007

2026-07-25 04:17:03 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | tvae | logistic_regression] BA=0.6150 | mean_dpd=0.3492

  [EO | f_father_education_level | tvae | logistic_regression]  BA=0.6150  mean_DPD=0.3492

2026-07-25 04:17:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | tvae | xgboost] BA=0.6136 | mean_dpd=0.3259

  [EO | f_father_education_level | tvae | xgboost]  BA=0.6136  mean_DPD=0.3259

2026-07-25 04:17:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | tvae | mlp] BA=0.6044 | mean_dpd=0.3134

  [EO | f_father_education_level | tvae | mlp]  BA=0.6044  mean_DPD=0.3134

2026-07-25 04:18:16 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | tvae | prejudice_remover] BA=0.6171 | mean_dpd=0.3528

  [PR | f_father_education_level | tvae]  BA=0.6171  mean_DPD=0.3528

2026-07-25 04:18:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | gaussian_copula | logistic_regression] BA=0.5752 | mean_dpd=0.1969

  [EO | f_father_education_level | gaussian_copula | logistic_regression]  BA=0.5752  mean_DPD=0.1969

2026-07-25 04:18:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | gaussian_copula | xgboost] BA=0.5778 | mean_dpd=0.2548

  [EO | f_father_education_level | gaussian_copula | xgboost]  BA=0.5778  mean_DPD=0.2548

2026-07-25 04:18:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | gaussian_copula | mlp] BA=0.5267 | mean_dpd=0.1197

  [EO | f_father_education_level | gaussian_copula | mlp]  BA=0.5267  mean_DPD=0.1197

2026-07-25 04:19:31 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_father_education_level | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:19:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | smote_low_perf | logistic_regression] BA=0.5921 | mean_dpd=0.1381

  [EO | f_father_education_level | smote_low_perf | logistic_regression]  BA=0.5921  mean_DPD=0.1381

2026-07-25 04:19:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | smote_low_perf | xgboost] BA=0.5756 | mean_dpd=0.2583

  [EO | f_father_education_level | smote_low_perf | xgboost]  BA=0.5756  mean_DPD=0.2583

2026-07-25 04:20:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_education_level | smote_low_perf | mlp] BA=0.5721 | mean_dpd=0.1093

  [EO | f_father_education_level | smote_low_perf | mlp]  BA=0.5721  mean_DPD=0.1093

2026-07-25 04:22:01 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_education_level | smote_low_perf | prejudice_remover] BA=0.6121 | mean_dpd=0.2373

  [PR | f_father_education_level | smote_low_perf]  BA=0.6121  mean_DPD=0.2373

2026-07-25 04:22:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | real | logistic_regression] BA=0.6121 | mean_dpd=0.2447

  [EO | f_mother_occupation | real | logistic_regression]  BA=0.6121  mean_DPD=0.2447

2026-07-25 04:22:04 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | real | xgboost] BA=0.6358 | mean_dpd=0.2294

  [EO | f_mother_occupation | real | xgboost]  BA=0.6358  mean_DPD=0.2294

2026-07-25 04:22:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | real | mlp] BA=0.6190 | mean_dpd=0.2097

  [EO | f_mother_occupation | real | mlp]  BA=0.6190  mean_DPD=0.2097

2026-07-25 04:23:22 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | real | prejudice_remover] BA=0.5384 | mean_dpd=0.0319

  [PR | f_mother_occupation | real]  BA=0.5384  mean_DPD=0.0319

2026-07-25 04:23:23 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | ctgan | logistic_regression] BA=0.5893 | mean_dpd=0.2629

  [EO | f_mother_occupation | ctgan | logistic_regression]  BA=0.5893  mean_DPD=0.2629

2026-07-25 04:23:25 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | ctgan | xgboost] BA=0.5834 | mean_dpd=0.2831

  [EO | f_mother_occupation | ctgan | xgboost]  BA=0.5834  mean_DPD=0.2831

2026-07-25 04:23:36 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | ctgan | mlp] BA=0.5394 | mean_dpd=0.1729

  [EO | f_mother_occupation | ctgan | mlp]  BA=0.5394  mean_DPD=0.1729

2026-07-25 04:24:23 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | ctgan | prejudice_remover] BA=0.5002 | mean_dpd=0.0009

  [PR | f_mother_occupation | ctgan]  BA=0.5002  mean_DPD=0.0009

2026-07-25 04:24:24 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | tvae | logistic_regression] BA=0.6103 | mean_dpd=0.3175

  [EO | f_mother_occupation | tvae | logistic_regression]  BA=0.6103  mean_DPD=0.3175

2026-07-25 04:24:26 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | tvae | xgboost] BA=0.6119 | mean_dpd=0.2995

  [EO | f_mother_occupation | tvae | xgboost]  BA=0.6119  mean_DPD=0.2995

2026-07-25 04:24:45 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | tvae | mlp] BA=0.5985 | mean_dpd=0.2711

  [EO | f_mother_occupation | tvae | mlp]  BA=0.5985  mean_DPD=0.2711

2026-07-25 04:25:43 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | tvae | prejudice_remover] BA=0.6087 | mean_dpd=0.3081

  [PR | f_mother_occupation | tvae]  BA=0.6087  mean_DPD=0.3081

2026-07-25 04:25:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | gaussian_copula | logistic_regression] BA=0.5892 | mean_dpd=0.2438

  [EO | f_mother_occupation | gaussian_copula | logistic_regression]  BA=0.5892  mean_DPD=0.2438

2026-07-25 04:25:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | gaussian_copula | xgboost] BA=0.5845 | mean_dpd=0.2625

  [EO | f_mother_occupation | gaussian_copula | xgboost]  BA=0.5845  mean_DPD=0.2625

2026-07-25 04:25:59 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | gaussian_copula | mlp] BA=0.5280 | mean_dpd=0.1395

  [EO | f_mother_occupation | gaussian_copula | mlp]  BA=0.5280  mean_DPD=0.1395

2026-07-25 04:27:13 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_mother_occupation | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:27:15 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | smote_low_perf | logistic_regression] BA=0.5974 | mean_dpd=0.1753

  [EO | f_mother_occupation | smote_low_perf | logistic_regression]  BA=0.5974  mean_DPD=0.1753

2026-07-25 04:27:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | smote_low_perf | xgboost] BA=0.5780 | mean_dpd=0.2555

  [EO | f_mother_occupation | smote_low_perf | xgboost]  BA=0.5780  mean_DPD=0.2555

2026-07-25 04:28:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_mother_occupation | smote_low_perf | mlp] BA=0.5800 | mean_dpd=0.1314

  [EO | f_mother_occupation | smote_low_perf | mlp]  BA=0.5800  mean_DPD=0.1314

2026-07-25 04:29:25 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_mother_occupation | smote_low_perf | prejudice_remover] BA=0.6150 | mean_dpd=0.2413

  [PR | f_mother_occupation | smote_low_perf]  BA=0.6150  mean_DPD=0.2413

2026-07-25 04:29:26 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | real | logistic_regression] BA=0.6128 | mean_dpd=0.2479

  [EO | f_father_occupation | real | logistic_regression]  BA=0.6128  mean_DPD=0.2479

2026-07-25 04:29:28 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | real | xgboost] BA=0.6353 | mean_dpd=0.2321

  [EO | f_father_occupation | real | xgboost]  BA=0.6353  mean_DPD=0.2321

2026-07-25 04:29:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | real | mlp] BA=0.6186 | mean_dpd=0.2097

  [EO | f_father_occupation | real | mlp]  BA=0.6186  mean_DPD=0.2097

2026-07-25 04:30:34 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | real | prejudice_remover] BA=0.5365 | mean_dpd=0.0308

  [PR | f_father_occupation | real]  BA=0.5365  mean_DPD=0.0308

2026-07-25 04:30:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | ctgan | logistic_regression] BA=0.5917 | mean_dpd=0.2626

  [EO | f_father_occupation | ctgan | logistic_regression]  BA=0.5917  mean_DPD=0.2626

2026-07-25 04:30:37 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | ctgan | xgboost] BA=0.5792 | mean_dpd=0.2757

  [EO | f_father_occupation | ctgan | xgboost]  BA=0.5792  mean_DPD=0.2757

2026-07-25 04:30:49 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | ctgan | mlp] BA=0.5396 | mean_dpd=0.1811

  [EO | f_father_occupation | ctgan | mlp]  BA=0.5396  mean_DPD=0.1811

2026-07-25 04:31:53 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | ctgan | prejudice_remover] BA=0.5003 | mean_dpd=0.0007

  [PR | f_father_occupation | ctgan]  BA=0.5003  mean_DPD=0.0007

2026-07-25 04:31:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | tvae | logistic_regression] BA=0.5826 | mean_dpd=0.2243

  [EO | f_father_occupation | tvae | logistic_regression]  BA=0.5826  mean_DPD=0.2243

2026-07-25 04:31:56 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | tvae | xgboost] BA=0.5862 | mean_dpd=0.2181

  [EO | f_father_occupation | tvae | xgboost]  BA=0.5862  mean_DPD=0.2181

2026-07-25 04:32:15 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | tvae | mlp] BA=0.5810 | mean_dpd=0.2203

  [EO | f_father_occupation | tvae | mlp]  BA=0.5810  mean_DPD=0.2203

2026-07-25 04:33:16 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | tvae | prejudice_remover] BA=0.6104 | mean_dpd=0.3190

  [PR | f_father_occupation | tvae]  BA=0.6104  mean_DPD=0.3190

2026-07-25 04:33:17 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | gaussian_copula | logistic_regression] BA=0.5818 | mean_dpd=0.2152

  [EO | f_father_occupation | gaussian_copula | logistic_regression]  BA=0.5818  mean_DPD=0.2152

2026-07-25 04:33:19 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | gaussian_copula | xgboost] BA=0.5823 | mean_dpd=0.2716

  [EO | f_father_occupation | gaussian_copula | xgboost]  BA=0.5823  mean_DPD=0.2716

2026-07-25 04:33:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | gaussian_copula | mlp] BA=0.5270 | mean_dpd=0.1311

  [EO | f_father_occupation | gaussian_copula | mlp]  BA=0.5270  mean_DPD=0.1311

2026-07-25 04:34:18 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_father_occupation | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:34:20 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | smote_low_perf | logistic_regression] BA=0.5965 | mean_dpd=0.1707

  [EO | f_father_occupation | smote_low_perf | logistic_regression]  BA=0.5965  mean_DPD=0.1707

2026-07-25 04:34:23 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | smote_low_perf | xgboost] BA=0.5766 | mean_dpd=0.2561

  [EO | f_father_occupation | smote_low_perf | xgboost]  BA=0.5766  mean_DPD=0.2561

2026-07-25 04:35:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_father_occupation | smote_low_perf | mlp] BA=0.5790 | mean_dpd=0.1244

  [EO | f_father_occupation | smote_low_perf | mlp]  BA=0.5790  mean_DPD=0.1244

2026-07-25 04:36:30 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_father_occupation | smote_low_perf | prejudice_remover] BA=0.6173 | mean_dpd=0.2440

  [PR | f_father_occupation | smote_low_perf]  BA=0.6173  mean_DPD=0.2440

2026-07-25 04:36:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | real | logistic_regression] BA=0.6059 | mean_dpd=0.1955

  [EO | f_extent_of_books_at_home | real | logistic_regression]  BA=0.6059  mean_DPD=0.1955

2026-07-25 04:36:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | real | xgboost] BA=0.6248 | mean_dpd=0.2160

  [EO | f_extent_of_books_at_home | real | xgboost]  BA=0.6248  mean_DPD=0.2160

2026-07-25 04:36:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | real | mlp] BA=0.6125 | mean_dpd=0.1738

  [EO | f_extent_of_books_at_home | real | mlp]  BA=0.6125  mean_DPD=0.1738

2026-07-25 04:37:29 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | real | prejudice_remover] BA=0.5363 | mean_dpd=0.0308

  [PR | f_extent_of_books_at_home | real]  BA=0.5363  mean_DPD=0.0308

2026-07-25 04:37:30 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | ctgan | logistic_regression] BA=0.5853 | mean_dpd=0.2617

  [EO | f_extent_of_books_at_home | ctgan | logistic_regression]  BA=0.5853  mean_DPD=0.2617

2026-07-25 04:37:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | ctgan | xgboost] BA=0.5705 | mean_dpd=0.2611

  [EO | f_extent_of_books_at_home | ctgan | xgboost]  BA=0.5705  mean_DPD=0.2611

2026-07-25 04:37:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | ctgan | mlp] BA=0.5318 | mean_dpd=0.1708

  [EO | f_extent_of_books_at_home | ctgan | mlp]  BA=0.5318  mean_DPD=0.1708

2026-07-25 04:38:28 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | ctgan | prejudice_remover] BA=0.5002 | mean_dpd=0.0003

  [PR | f_extent_of_books_at_home | ctgan]  BA=0.5002  mean_DPD=0.0003

2026-07-25 04:38:29 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | tvae | logistic_regression] BA=0.5987 | mean_dpd=0.2963

  [EO | f_extent_of_books_at_home | tvae | logistic_regression]  BA=0.5987  mean_DPD=0.2963

2026-07-25 04:38:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | tvae | xgboost] BA=0.6002 | mean_dpd=0.2918

  [EO | f_extent_of_books_at_home | tvae | xgboost]  BA=0.6002  mean_DPD=0.2918

2026-07-25 04:38:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | tvae | mlp] BA=0.5844 | mean_dpd=0.2582

  [EO | f_extent_of_books_at_home | tvae | mlp]  BA=0.5844  mean_DPD=0.2582

2026-07-25 04:39:51 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | tvae | prejudice_remover] BA=0.6139 | mean_dpd=0.3141

  [PR | f_extent_of_books_at_home | tvae]  BA=0.6139  mean_DPD=0.3141

2026-07-25 04:39:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | gaussian_copula | logistic_regression] BA=0.5739 | mean_dpd=0.2160

  [EO | f_extent_of_books_at_home | gaussian_copula | logistic_regression]  BA=0.5739  mean_DPD=0.2160

2026-07-25 04:39:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | gaussian_copula | xgboost] BA=0.5783 | mean_dpd=0.2500

  [EO | f_extent_of_books_at_home | gaussian_copula | xgboost]  BA=0.5783  mean_DPD=0.2500

2026-07-25 04:40:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | gaussian_copula | mlp] BA=0.5296 | mean_dpd=0.1278

  [EO | f_extent_of_books_at_home | gaussian_copula | mlp]  BA=0.5296  mean_DPD=0.1278

2026-07-25 04:41:03 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_extent_of_books_at_home | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:41:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | smote_low_perf | logistic_regression] BA=0.5808 | mean_dpd=0.1413

  [EO | f_extent_of_books_at_home | smote_low_perf | logistic_regression]  BA=0.5808  mean_DPD=0.1413

2026-07-25 04:41:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | smote_low_perf | xgboost] BA=0.5720 | mean_dpd=0.2506

  [EO | f_extent_of_books_at_home | smote_low_perf | xgboost]  BA=0.5720  mean_DPD=0.2506

2026-07-25 04:41:50 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_extent_of_books_at_home | smote_low_perf | mlp] BA=0.5739 | mean_dpd=0.1192

  [EO | f_extent_of_books_at_home | smote_low_perf | mlp]  BA=0.5739  mean_DPD=0.1192

2026-07-25 04:42:59 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_extent_of_books_at_home | smote_low_perf | prejudice_remover] BA=0.6031 | mean_dpd=0.2041

  [PR | f_extent_of_books_at_home | smote_low_perf]  BA=0.6031  mean_DPD=0.2041

2026-07-25 04:43:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | real | logistic_regression] BA=0.6214 | mean_dpd=0.2911

  [EO | f_frequency_of_see_adult_read | real | logistic_regression]  BA=0.6214  mean_DPD=0.2911

2026-07-25 04:43:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | real | xgboost] BA=0.6418 | mean_dpd=0.2704

  [EO | f_frequency_of_see_adult_read | real | xgboost]  BA=0.6418  mean_DPD=0.2704

2026-07-25 04:43:15 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | real | mlp] BA=0.6264 | mean_dpd=0.2560

  [EO | f_frequency_of_see_adult_read | real | mlp]  BA=0.6264  mean_DPD=0.2560

2026-07-25 04:44:20 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | real | prejudice_remover] BA=0.5378 | mean_dpd=0.0325

  [PR | f_frequency_of_see_adult_read | real]  BA=0.5378  mean_DPD=0.0325

2026-07-25 04:44:21 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | ctgan | logistic_regression] BA=0.5958 | mean_dpd=0.2886

  [EO | f_frequency_of_see_adult_read | ctgan | logistic_regression]  BA=0.5958  mean_DPD=0.2886

2026-07-25 04:44:23 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | ctgan | xgboost] BA=0.5850 | mean_dpd=0.2995

  [EO | f_frequency_of_see_adult_read | ctgan | xgboost]  BA=0.5850  mean_DPD=0.2995

2026-07-25 04:44:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | ctgan | mlp] BA=0.5442 | mean_dpd=0.1948

  [EO | f_frequency_of_see_adult_read | ctgan | mlp]  BA=0.5442  mean_DPD=0.1948

2026-07-25 04:45:30 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | ctgan | prejudice_remover] BA=0.5003 | mean_dpd=0.0006

  [PR | f_frequency_of_see_adult_read | ctgan]  BA=0.5003  mean_DPD=0.0006

2026-07-25 04:45:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | tvae | logistic_regression] BA=0.6103 | mean_dpd=0.3410

  [EO | f_frequency_of_see_adult_read | tvae | logistic_regression]  BA=0.6103  mean_DPD=0.3410

2026-07-25 04:45:34 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | tvae | xgboost] BA=0.6171 | mean_dpd=0.3195

  [EO | f_frequency_of_see_adult_read | tvae | xgboost]  BA=0.6171  mean_DPD=0.3195

2026-07-25 04:45:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | tvae | mlp] BA=0.6054 | mean_dpd=0.3126

  [EO | f_frequency_of_see_adult_read | tvae | mlp]  BA=0.6054  mean_DPD=0.3126

2026-07-25 04:46:38 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | tvae | prejudice_remover] BA=0.6186 | mean_dpd=0.3553

  [PR | f_frequency_of_see_adult_read | tvae]  BA=0.6186  mean_DPD=0.3553

2026-07-25 04:46:39 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | gaussian_copula | logistic_regression] BA=0.5760 | mean_dpd=0.1923

  [EO | f_frequency_of_see_adult_read | gaussian_copula | logistic_regression]  BA=0.5760  mean_DPD=0.1923

2026-07-25 04:46:42 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | gaussian_copula | xgboost] BA=0.5820 | mean_dpd=0.2649

  [EO | f_frequency_of_see_adult_read | gaussian_copula | xgboost]  BA=0.5820  mean_DPD=0.2649

2026-07-25 04:46:55 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | gaussian_copula | mlp] BA=0.5263 | mean_dpd=0.1292

  [EO | f_frequency_of_see_adult_read | gaussian_copula | mlp]  BA=0.5263  mean_DPD=0.1292

2026-07-25 04:47:41 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_frequency_of_see_adult_read | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:47:43 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | smote_low_perf | logistic_regression] BA=0.6022 | mean_dpd=0.1821

  [EO | f_frequency_of_see_adult_read | smote_low_perf | logistic_regression]  BA=0.6022  mean_DPD=0.1821

2026-07-25 04:47:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | smote_low_perf | xgboost] BA=0.5791 | mean_dpd=0.2604

  [EO | f_frequency_of_see_adult_read | smote_low_perf | xgboost]  BA=0.5791  mean_DPD=0.2604

2026-07-25 04:48:28 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_frequency_of_see_adult_read | smote_low_perf | mlp] BA=0.5801 | mean_dpd=0.1329

  [EO | f_frequency_of_see_adult_read | smote_low_perf | mlp]  BA=0.5801  mean_DPD=0.1329

2026-07-25 04:49:50 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_frequency_of_see_adult_read | smote_low_perf | prejudice_remover] BA=0.5492 | mean_dpd=0.0970

  [PR | f_frequency_of_see_adult_read | smote_low_perf]  BA=0.5492  mean_DPD=0.0970

2026-07-25 04:49:51 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | real | logistic_regression] BA=0.6065 | mean_dpd=0.2304

  [EO | p_public_or_private | real | logistic_regression]  BA=0.6065  mean_DPD=0.2304

2026-07-25 04:49:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | real | xgboost] BA=0.6337 | mean_dpd=0.2550

  [EO | p_public_or_private | real | xgboost]  BA=0.6337  mean_DPD=0.2550

2026-07-25 04:50:06 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | real | mlp] BA=0.6196 | mean_dpd=0.1930

  [EO | p_public_or_private | real | mlp]  BA=0.6196  mean_DPD=0.1930

2026-07-25 04:50:51 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | real | prejudice_remover] BA=0.5379 | mean_dpd=0.0315

  [PR | p_public_or_private | real]  BA=0.5379  mean_DPD=0.0315

2026-07-25 04:50:52 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | ctgan | logistic_regression] BA=0.5829 | mean_dpd=0.3000

  [EO | p_public_or_private | ctgan | logistic_regression]  BA=0.5829  mean_DPD=0.3000

2026-07-25 04:50:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | ctgan | xgboost] BA=0.5802 | mean_dpd=0.3022

  [EO | p_public_or_private | ctgan | xgboost]  BA=0.5802  mean_DPD=0.3022

2026-07-25 04:51:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | ctgan | mlp] BA=0.5408 | mean_dpd=0.2131

  [EO | p_public_or_private | ctgan | mlp]  BA=0.5408  mean_DPD=0.2131

2026-07-25 04:52:07 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | ctgan | prejudice_remover] BA=0.5004 | mean_dpd=0.0007

  [PR | p_public_or_private | ctgan]  BA=0.5004  mean_DPD=0.0007

2026-07-25 04:52:08 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | tvae | logistic_regression] BA=0.6132 | mean_dpd=0.3506

  [EO | p_public_or_private | tvae | logistic_regression]  BA=0.6132  mean_DPD=0.3506

2026-07-25 04:52:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | tvae | xgboost] BA=0.6134 | mean_dpd=0.3330

  [EO | p_public_or_private | tvae | xgboost]  BA=0.6134  mean_DPD=0.3330

2026-07-25 04:52:30 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | tvae | mlp] BA=0.6037 | mean_dpd=0.3165

  [EO | p_public_or_private | tvae | mlp]  BA=0.6037  mean_DPD=0.3165

2026-07-25 04:53:40 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | tvae | prejudice_remover] BA=0.6099 | mean_dpd=0.2662

  [PR | p_public_or_private | tvae]  BA=0.6099  mean_DPD=0.2662

2026-07-25 04:53:41 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | gaussian_copula | logistic_regression] BA=0.5779 | mean_dpd=0.2161

  [EO | p_public_or_private | gaussian_copula | logistic_regression]  BA=0.5779  mean_DPD=0.2161

2026-07-25 04:53:43 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | gaussian_copula | xgboost] BA=0.5778 | mean_dpd=0.2476

  [EO | p_public_or_private | gaussian_copula | xgboost]  BA=0.5778  mean_DPD=0.2476

2026-07-25 04:53:57 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | gaussian_copula | mlp] BA=0.5183 | mean_dpd=0.0942

  [EO | p_public_or_private | gaussian_copula | mlp]  BA=0.5183  mean_DPD=0.0942

2026-07-25 04:55:06 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_public_or_private | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 04:55:08 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | smote_low_perf | logistic_regression] BA=0.6002 | mean_dpd=0.2246

  [EO | p_public_or_private | smote_low_perf | logistic_regression]  BA=0.6002  mean_DPD=0.2246

2026-07-25 04:55:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | smote_low_perf | xgboost] BA=0.5771 | mean_dpd=0.2595

  [EO | p_public_or_private | smote_low_perf | xgboost]  BA=0.5771  mean_DPD=0.2595

2026-07-25 04:55:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_public_or_private | smote_low_perf | mlp] BA=0.5823 | mean_dpd=0.1495

  [EO | p_public_or_private | smote_low_perf | mlp]  BA=0.5823  mean_DPD=0.1495

2026-07-25 04:57:01 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_public_or_private | smote_low_perf | prejudice_remover] BA=0.6121 | mean_dpd=0.2437

  [PR | p_public_or_private | smote_low_perf]  BA=0.6121  mean_DPD=0.2437

2026-07-25 04:57:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | real | logistic_regression] BA=0.6180 | mean_dpd=0.2685

  [EO | p_island | real | logistic_regression]  BA=0.6180  mean_DPD=0.2685

2026-07-25 04:57:05 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | real | xgboost] BA=0.6442 | mean_dpd=0.2939

  [EO | p_island | real | xgboost]  BA=0.6442  mean_DPD=0.2939

2026-07-25 04:57:18 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | real | mlp] BA=0.6246 | mean_dpd=0.2767

  [EO | p_island | real | mlp]  BA=0.6246  mean_DPD=0.2767

2026-07-25 04:57:59 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | real | prejudice_remover] BA=0.5386 | mean_dpd=0.0338

  [PR | p_island | real]  BA=0.5386  mean_DPD=0.0338

2026-07-25 04:58:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | ctgan | logistic_regression] BA=0.5924 | mean_dpd=0.3229

  [EO | p_island | ctgan | logistic_regression]  BA=0.5924  mean_DPD=0.3229

2026-07-25 04:58:02 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | ctgan | xgboost] BA=0.5879 | mean_dpd=0.3128

  [EO | p_island | ctgan | xgboost]  BA=0.5879  mean_DPD=0.3128

2026-07-25 04:58:13 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | ctgan | mlp] BA=0.5477 | mean_dpd=0.2271

  [EO | p_island | ctgan | mlp]  BA=0.5477  mean_DPD=0.2271

2026-07-25 04:59:03 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | ctgan | prejudice_remover] BA=0.5004 | mean_dpd=0.0008

  [PR | p_island | ctgan]  BA=0.5004  mean_DPD=0.0008

2026-07-25 04:59:04 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | tvae | logistic_regression] BA=0.6172 | mean_dpd=0.3722

  [EO | p_island | tvae | logistic_regression]  BA=0.6172  mean_DPD=0.3722

2026-07-25 04:59:07 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | tvae | xgboost] BA=0.6182 | mean_dpd=0.3418

  [EO | p_island | tvae | xgboost]  BA=0.6182  mean_DPD=0.3418

2026-07-25 04:59:26 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | tvae | mlp] BA=0.6092 | mean_dpd=0.3380

  [EO | p_island | tvae | mlp]  BA=0.6092  mean_DPD=0.3380

2026-07-25 05:00:11 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | tvae | prejudice_remover] BA=0.6076 | mean_dpd=0.3012

  [PR | p_island | tvae]  BA=0.6076  mean_DPD=0.3012

2026-07-25 05:00:12 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | gaussian_copula | logistic_regression] BA=0.5789 | mean_dpd=0.2232

  [EO | p_island | gaussian_copula | logistic_regression]  BA=0.5789  mean_DPD=0.2232

2026-07-25 05:00:14 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | gaussian_copula | xgboost] BA=0.5819 | mean_dpd=0.2704

  [EO | p_island | gaussian_copula | xgboost]  BA=0.5819  mean_DPD=0.2704

2026-07-25 05:00:27 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | gaussian_copula | mlp] BA=0.5268 | mean_dpd=0.1222

  [EO | p_island | gaussian_copula | mlp]  BA=0.5268  mean_DPD=0.1222

2026-07-25 05:01:51 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_island | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 05:01:53 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | smote_low_perf | logistic_regression] BA=0.6116 | mean_dpd=0.2254

  [EO | p_island | smote_low_perf | logistic_regression]  BA=0.6116  mean_DPD=0.2254

2026-07-25 05:01:56 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | smote_low_perf | xgboost] BA=0.5808 | mean_dpd=0.2665

  [EO | p_island | smote_low_perf | xgboost]  BA=0.5808  mean_DPD=0.2665

2026-07-25 05:02:38 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_island | smote_low_perf | mlp] BA=0.5848 | mean_dpd=0.1553

  [EO | p_island | smote_low_perf | mlp]  BA=0.5848  mean_DPD=0.1553

2026-07-25 05:03:50 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_island | smote_low_perf | prejudice_remover] BA=0.6200 | mean_dpd=0.2525

  [PR | p_island | smote_low_perf]  BA=0.6200  mean_DPD=0.2525

2026-07-25 05:03:51 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | real | logistic_regression] BA=0.6086 | mean_dpd=0.2471

  [EO | p_percentage_of_teachers_changed_school_last_year | real | logistic_regression]  BA=0.6086  mean_DPD=0.2471

2026-07-25 05:03:54 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | real | xgboost] BA=0.6423 | mean_dpd=0.2980

  [EO | p_percentage_of_teachers_changed_school_last_year | real | xgboost]  BA=0.6423  mean_DPD=0.2980

2026-07-25 05:04:06 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | real | mlp] BA=0.6161 | mean_dpd=0.2238

  [EO | p_percentage_of_teachers_changed_school_last_year | real | mlp]  BA=0.6161  mean_DPD=0.2238

2026-07-25 05:04:57 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | real | prejudice_remover] BA=0.5345 | mean_dpd=0.0284

  [PR | p_percentage_of_teachers_changed_school_last_year | real]  BA=0.5345  mean_DPD=0.0284

2026-07-25 05:04:58 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | ctgan | logistic_regression] BA=0.5849 | mean_dpd=0.2989

  [EO | p_percentage_of_teachers_changed_school_last_year | ctgan | logistic_regression]  BA=0.5849  mean_DPD=0.2989

2026-07-25 05:05:00 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | ctgan | xgboost] BA=0.5892 | mean_dpd=0.3170

  [EO | p_percentage_of_teachers_changed_school_last_year | ctgan | xgboost]  BA=0.5892  mean_DPD=0.3170

2026-07-25 05:05:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | ctgan | mlp] BA=0.5420 | mean_dpd=0.2177

  [EO | p_percentage_of_teachers_changed_school_last_year | ctgan | mlp]  BA=0.5420  mean_DPD=0.2177

2026-07-25 05:06:10 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | ctgan | prejudice_remover] BA=0.5004 | mean_dpd=0.0004

  [PR | p_percentage_of_teachers_changed_school_last_year | ctgan]  BA=0.5004  mean_DPD=0.0004

2026-07-25 05:06:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | tvae | logistic_regression] BA=0.6149 | mean_dpd=0.3659

  [EO | p_percentage_of_teachers_changed_school_last_year | tvae | logistic_regression]  BA=0.6149  mean_DPD=0.3659

2026-07-25 05:06:14 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | tvae | xgboost] BA=0.6146 | mean_dpd=0.3348

  [EO | p_percentage_of_teachers_changed_school_last_year | tvae | xgboost]  BA=0.6146  mean_DPD=0.3348

2026-07-25 05:06:33 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | tvae | mlp] BA=0.6106 | mean_dpd=0.3211

  [EO | p_percentage_of_teachers_changed_school_last_year | tvae | mlp]  BA=0.6106  mean_DPD=0.3211

2026-07-25 05:07:34 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | tvae | prejudice_remover] BA=0.6068 | mean_dpd=0.2973

  [PR | p_percentage_of_teachers_changed_school_last_year | tvae]  BA=0.6068  mean_DPD=0.2973

2026-07-25 05:07:35 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | logistic_regression] BA=0.5781 | mean_dpd=0.2006

  [EO | p_percentage_of_teachers_changed_school_last_year | gaussian_copula | logistic_regression]  BA=0.5781  mean_DPD=0.2006

2026-07-25 05:07:37 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | xgboost] BA=0.5806 | mean_dpd=0.2645

  [EO | p_percentage_of_teachers_changed_school_last_year | gaussian_copula | xgboost]  BA=0.5806  mean_DPD=0.2645

2026-07-25 05:07:51 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | mlp] BA=0.5281 | mean_dpd=0.1323

  [EO | p_percentage_of_teachers_changed_school_last_year | gaussian_copula | mlp]  BA=0.5281  mean_DPD=0.1323

2026-07-25 05:08:56 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | p_percentage_of_teachers_changed_school_last_year | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 05:08:59 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | smote_low_perf | logistic_regression] BA=0.6030 | mean_dpd=0.2474

  [EO | p_percentage_of_teachers_changed_school_last_year | smote_low_perf | logistic_regression]  BA=0.6030  mean_DPD=0.2474

2026-07-25 05:09:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | smote_low_perf | xgboost] BA=0.5812 | mean_dpd=0.2683

  [EO | p_percentage_of_teachers_changed_school_last_year | smote_low_perf | xgboost]  BA=0.5812  mean_DPD=0.2683

2026-07-25 05:09:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=p_percentage_of_teachers_changed_school_last_year | smote_low_perf | mlp] BA=0.5889 | mean_dpd=0.1703

  [EO | p_percentage_of_teachers_changed_school_last_year | smote_low_perf | mlp]  BA=0.5889  mean_DPD=0.1703

2026-07-25 05:10:55 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=p_percentage_of_teachers_changed_school_last_year | smote_low_perf | prejudice_remover] BA=0.6194 | mean_dpd=0.2433

  [PR | p_percentage_of_teachers_changed_school_last_year | smote_low_perf]  BA=0.6194  mean_DPD=0.2433

2026-07-25 05:10:56 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | real | logistic_regression] BA=0.5979 | mean_dpd=0.1541

  [EO | f_ESCS | real | logistic_regression]  BA=0.5979  mean_DPD=0.1541

2026-07-25 05:10:58 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | real | xgboost] BA=0.6204 | mean_dpd=0.1695

  [EO | f_ESCS | real | xgboost]  BA=0.6204  mean_DPD=0.1695

2026-07-25 05:11:11 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | real | mlp] BA=0.6060 | mean_dpd=0.1355

  [EO | f_ESCS | real | mlp]  BA=0.6060  mean_DPD=0.1355

2026-07-25 05:12:01 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | real | prejudice_remover] BA=0.5349 | mean_dpd=0.0292

  [PR | f_ESCS | real]  BA=0.5349  mean_DPD=0.0292

2026-07-25 05:12:01 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | ctgan | logistic_regression] BA=0.5779 | mean_dpd=0.2367

  [EO | f_ESCS | ctgan | logistic_regression]  BA=0.5779  mean_DPD=0.2367

2026-07-25 05:12:04 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | ctgan | xgboost] BA=0.5672 | mean_dpd=0.2242

  [EO | f_ESCS | ctgan | xgboost]  BA=0.5672  mean_DPD=0.2242

2026-07-25 05:12:15 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | ctgan | mlp] BA=0.5311 | mean_dpd=0.1551

  [EO | f_ESCS | ctgan | mlp]  BA=0.5311  mean_DPD=0.1551

2026-07-25 05:13:21 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | ctgan | prejudice_remover] BA=0.5005 | mean_dpd=0.0007

  [PR | f_ESCS | ctgan]  BA=0.5005  mean_DPD=0.0007

2026-07-25 05:13:22 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | tvae | logistic_regression] BA=0.5964 | mean_dpd=0.2762

  [EO | f_ESCS | tvae | logistic_regression]  BA=0.5964  mean_DPD=0.2762

2026-07-25 05:13:25 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | tvae | xgboost] BA=0.6065 | mean_dpd=0.2844

  [EO | f_ESCS | tvae | xgboost]  BA=0.6065  mean_DPD=0.2844

2026-07-25 05:13:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | tvae | mlp] BA=0.5912 | mean_dpd=0.2609

  [EO | f_ESCS | tvae | mlp]  BA=0.5912  mean_DPD=0.2609

2026-07-25 05:14:28 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | tvae | prejudice_remover] BA=0.6079 | mean_dpd=0.3107

  [PR | f_ESCS | tvae]  BA=0.6079  mean_DPD=0.3107

2026-07-25 05:14:29 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | gaussian_copula | logistic_regression] BA=0.5719 | mean_dpd=0.1588

  [EO | f_ESCS | gaussian_copula | logistic_regression]  BA=0.5719  mean_DPD=0.1588

2026-07-25 05:14:31 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | gaussian_copula | xgboost] BA=0.5660 | mean_dpd=0.1645

  [EO | f_ESCS | gaussian_copula | xgboost]  BA=0.5660  mean_DPD=0.1645

2026-07-25 05:14:44 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | gaussian_copula | mlp] BA=0.5190 | mean_dpd=0.0895

  [EO | f_ESCS | gaussian_copula | mlp]  BA=0.5190  mean_DPD=0.0895

2026-07-25 05:15:44 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | gaussian_copula | prejudice_remover] BA=0.5000 | mean_dpd=0.0000

  [PR | f_ESCS | gaussian_copula]  BA=0.5000  mean_DPD=0.0000

2026-07-25 05:15:46 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | smote_low_perf | logistic_regression] BA=0.5755 | mean_dpd=0.1131

  [EO | f_ESCS | smote_low_perf | logistic_regression]  BA=0.5755  mean_DPD=0.1131

2026-07-25 05:15:49 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | smote_low_perf | xgboost] BA=0.5729 | mean_dpd=0.2398

  [EO | f_ESCS | smote_low_perf | xgboost]  BA=0.5729  mean_DPD=0.2398

2026-07-25 05:16:32 | INFO     | src.evaluation.evaluator |   [mitigated:equalized_odds | target=f_ESCS | smote_low_perf | mlp] BA=0.5676 | mean_dpd=0.0961

  [EO | f_ESCS | smote_low_perf | mlp]  BA=0.5676  mean_DPD=0.0961

2026-07-25 05:17:47 | INFO     | src.evaluation.evaluator |   [mitigated:prejudice_remover | target=f_ESCS | smote_low_perf | prejudice_remover] BA=0.6195 | mean_dpd=0.2835

  [PR | f_ESCS | smote_low_perf]  BA=0.6195  mean_DPD=0.2835

Mitigation results saved → C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\low_perf\goal3_mitigation_results.csv
Shape: (240, 61)  (0 degenerate/skipped fits, if any)

,technique,target_attr,method,classifier,balanced_accuracy,f1_macro,roc_auc,brier_score,degenerate_predictions,s_gender_dpd,...,p_percentage_of_teachers_changed_school_last_year_di,p_percentage_of_teachers_changed_school_last_year_odds_ratio,f_ESCS_dpd,f_ESCS_eod,f_ESCS_di,f_ESCS_odds_ratio,mean_dpd,mean_eod,mean_di,mean_odds_ratio
0,equalized_odds,s_gender,real,logistic_regression,0.629348,0.564546,0.629348,0.412578,False,0.004962,...,0.594964,0.755436,0.446815,0.425185,0.344779,1.981041,0.325124,0.323604,0.488994,1.495478
1,equalized_odds,s_gender,real,xgboost,0.647946,0.597614,0.647946,0.368747,False,0.004572,...,0.593014,0.759308,0.539943,0.576904,0.176658,3.449624,0.336816,0.364158,0.418875,2.043497
2,equalized_odds,s_gender,real,mlp,0.630140,0.577096,0.630140,0.392417,False,0.015990,...,0.642698,0.770301,0.411336,0.392558,0.346843,2.055319,0.288061,0.283738,0.504410,1.457754
3,prejudice_remover,s_gender,real,prejudice_remover,0.537449,0.512227,0.686381,0.171816,False,0.008353,...,0.424048,0.574481,0.052357,0.095847,0.126529,5.176932,0.032606,0.058817,0.387773,3.332874
4,equalized_odds,s_gender,ctgan,logistic_regression,0.594769,0.527338,0.594769,0.454139,False,0.049381,...,0.652862,0.803583,0.443767,0.434337,0.376788,2.033229,0.332990,0.339567,0.479467,1.958382
5,equalized_odds,s_gender,ctgan,xgboost,0.587005,0.547248,0.587005,0.415262,False,0.041351,...,0.722664,0.876111,0.546567,0.569956,0.171334,4.775387,0.316096,0.337042,0.437327,2.448968
6,equalized_odds,s_gender,ctgan,mlp,0.546361,0.512201,0.546361,0.449391,False,0.054149,...,0.686919,0.769208,0.333400,0.332298,0.434314,2.057716,0.227696,0.233809,0.572005,1.670406
7,prejudice_remover,s_gender,ctgan,prejudice_remover,0.500364,0.429533,0.631240,0.183425,False,0.000777,...,0.000000,NaN,0.000403,0.001773,0.585198,NaN,0.000699,0.001650,0.361290,0.390562
8,equalized_odds,s_gender,tvae,logistic_regression,0.612503,0.550154,0.612503,0.426891,False,0.121286,...,0.583750,0.732445,0.560331,0.552529,0.228650,3.089012,0.366908,0.375918,0.434103,1.888808
9,equalized_odds,s_gender,tvae,xgboost,0.616563,0.585004,0.616563,0.367027,False,0.057812,...,0.637964,0.777370,0.599709,0.675285,0.042967,11.963454,0.337679,0.378320,0.356913,3.889651

### Mitigation summary tables

For every mitigated row we look up the **matching unmitigated row** from
`results_df` (same `method`, and for equalized-odds the same `classifier`) and
compare the targeted attribute's own DPD/EOD/DI before vs. after mitigation —
this answers "did mitigating for attribute X actually reduce unfairness on
X?", as opposed to the mean-across-all-attributes numbers used elsewhere in
the notebook.

In [27]:
def _unmitigated_target_metrics(method: str, classifier: str | None, attr: str) -> dict[str, float]:
    """Mean dpd/eod/di for `attr` from the unmitigated results_df, matched on
    method (+ classifier when given -- prejudice_remover has no match, so we
    average across all classifiers for that method instead)."""
    sub = results_df[results_df["method"] == method]
    if classifier is not None:
        sub = sub[sub["classifier"] == classifier]
    out = {}
    for metric in ("dpd", "eod", "di"):
        col = f"{attr}_{metric}"
        out[metric] = sub[col].mean() if col in sub.columns and not sub.empty else float("nan")
    return out


comparison_rows = []
for _, r in mitigation_df.iterrows():
    attr = r["target_attr"]
    clf_lookup = r["classifier"] if r["technique"] == "equalized_odds" else None
    base = _unmitigated_target_metrics(r["method"], clf_lookup, attr)

    row = {
        "technique": r["technique"], "target_attr": attr,
        "method": r["method"], "classifier": r["classifier"],
        "balanced_accuracy": r["balanced_accuracy"],
    }
    for metric in ("dpd", "eod", "di"):
        mitigated_val = r.get(f"{attr}_{metric}", float("nan"))
        row[f"{metric}_unmitigated"] = base[metric]
        row[f"{metric}_mitigated"]   = mitigated_val
        # DPD/EOD: lower is fairer -> improvement = unmitigated - mitigated.
        # DI: closer to 1 is fairer -> improvement = mitigated - unmitigated.
        if metric == "di":
            row[f"{metric}_improvement"] = mitigated_val - base[metric]
        else:
            row[f"{metric}_improvement"] = base[metric] - mitigated_val
    comparison_rows.append(row)

mitigation_comparison_df = pd.DataFrame(comparison_rows)
if not mitigation_comparison_df.empty:
    comparison_path = cfg["paths"]["results_dir"] / "goal3_mitigation_comparison.csv"
    mitigation_comparison_df.to_csv(comparison_path, index=False)
    print(f"Mitigation comparison saved → {comparison_path}\n")
    print(mitigation_comparison_df.round(4).to_string(index=False))
else:
    print("No mitigation rows to compare (mitigation disabled or no protected attributes present).")

Mitigation comparison saved → C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\low_perf\goal3_mitigation_comparison.csv

        technique                                       target_attr          method          classifier  balanced_accuracy  dpd_unmitigated  dpd_mitigated  dpd_improvement  eod_unmitigated  eod_mitigated  eod_improvement  di_unmitigated  di_mitigated  di_improvement
   equalized_odds                                          s_gender            real logistic_regression             0.6293           0.0867         0.0050           0.0818           0.0872         0.0084           0.0789          0.8285        0.9905          0.1620
   equalized_odds                                          s_gender            real             xgboost             0.6479           0.0368         0.0046           0.0322           0.0327         0.0014           0.0313          0.9235        0.9901          0.0666
   equalized_odds                                          s_gender            real                 mlp             0.6301           0.0159         0.0160          -0.0000           0.0203         0.0144           0.0060          0.7871        0.9673          0.1802
prejudice_remover                                          s_gender            real   prejudice_remover             0.5374           0.0465         0.0084           0.0381           0.0467         0.0168           0.0299          0.8464        0.8154         -0.0310
   equalized_odds                                          s_gender           ctgan logistic_regression             0.5948           0.0303         0.0494          -0.0191           0.0342         0.0574          -0.0232          0.9464        0.9141         -0.0323
   equalized_odds                                          s_gender           ctgan             xgboost             0.5870           0.0113         0.0414          -0.0301           0.0198         0.0450          -0.0252          0.9727        0.9141         -0.0586
   equalized_odds                                          s_gender           ctgan                 mlp             0.5464           0.0007         0.0541          -0.0534           0.0043         0.0616          -0.0573          0.7629        0.8905          0.1276
prejudice_remover                                          s_gender           ctgan   prejudice_remover             0.5004           0.0141         0.0008           0.0133           0.0194         0.0009           0.0186          0.8940        0.3537         -0.5403
   equalized_odds                                          s_gender            tvae logistic_regression             0.6125           0.0630         0.1213          -0.0583           0.0684         0.1259          -0.0575          0.8898        0.7916         -0.0983
   equalized_odds                                          s_gender            tvae             xgboost             0.6166           0.0064         0.0578          -0.0514           0.0232         0.0827          -0.0595          0.9849        0.8677         -0.1172
   equalized_odds                                          s_gender            tvae                 mlp             0.6088           0.0622         0.0907          -0.0286           0.0723         0.1074          -0.0350          0.8643        0.8263         -0.0380
prejudice_remover                                          s_gender            tvae   prejudice_remover             0.6053           0.0439         0.1364          -0.0925           0.0546         0.1664          -0.1118          0.9130        0.6789         -0.2341
   equalized_odds                                          s_gender gaussian_copula logistic_regression             0.5896           0.0480         0.0110           0.0370           0.0668         0.0208           0.0460          0.9002        0.9780          0.0778
   equalized_odds                                          s_gender gaussian_copula             xgboost             0.5806           0.0029         0.0082          -0.0053           0.0189         0.0154           0.0034          0.9940        0.9831         -0.0110
   equalized_odds                                          s_gender gaussian_copula                 mlp             0.5280           0.0005         0.0229          -0.0224           0.0005         0.0219          -0.0214          0.7405        0.9481          0.2077
prejudice_remover                                          s_gender gaussian_copula   prejudice_remover             0.5000           0.0171         0.0000           0.0171           0.0287         0.0000           0.0287          0.8782           NaN             NaN
   equalized_odds                                          s_gender  smote_low_perf logistic_regression             0.6252           0.0944         0.0071           0.0873           0.0899         0.0142           0.0757          0.7667        0.9835          0.2169
   equalized_odds                                          s_gender  smote_low_perf             xgboost             0.5820           0.0079         0.0157          -0.0078           0.0140         0.0256          -0.0115          0.9785        0.9579         -0.0206
   equalized_odds                                          s_gender  smote_low_perf                 mlp             0.5916           0.0249         0.0077           0.0171           0.0276         0.0162           0.0114          0.9156        0.9762          0.0605
prejudice_remover                                          s_gender  smote_low_perf   prejudice_remover             0.6229           0.0424         0.0363           0.0061           0.0438         0.0342           0.0096          0.8869        0.9055          0.0185
   equalized_odds                                   s_birth_country            real logistic_regression             0.6305           0.1430         0.0109           0.1321           0.1737         0.1157           0.0581          0.7627        0.9786          0.2159
   equalized_odds                                   s_birth_country            real             xgboost             0.6506           0.0981         0.0022           0.0959           0.1540         0.1509           0.0030          0.8245        0.9950          0.1705
   equalized_odds                                   s_birth_country            real                 mlp             0.6085           0.0142         0.0289          -0.0147           0.0662         0.0639           0.0023          0.8238        0.9099          0.0861
prejudice_remover                                   s_birth_country            real   prejudice_remover             0.5364           0.0851         0.0285           0.0566           0.1313         0.0507           0.0806          0.8037        0.5825         -0.2211
   equalized_odds                                   s_birth_country           ctgan logistic_regression             0.6013           0.4748         0.0574           0.4174           0.5854         0.0622           0.5232          0.1453        0.9006          0.7553
   equalized_odds                                   s_birth_country           ctgan             xgboost             0.5878           0.1850         0.0503           0.1347           0.2350         0.0843           0.1507          0.5472        0.8987          0.3515
   equalized_odds                                   s_birth_country           ctgan                 mlp             0.5537           0.0026         0.0873          -0.0846           0.0039         0.0839          -0.0800          0.0000        0.8809          0.8809
prejudice_remover                                   s_birth_country           ctgan   prejudice_remover             0.5005           0.2208         0.0366           0.1842           0.2748         0.0386           0.2362          0.2308        0.0187         -0.2122
   equalized_odds                                   s_birth_country            tvae logistic_regression             0.6170           0.2500         0.1206           0.1294           0.2767         0.1427           0.1340          0.6831        0.8168          0.1337
   equalized_odds                                   s_birth_country            tvae             xgboost             0.6183           0.1266         0.1507          -0.0241           0.1531         0.1885          -0.0354          0.7684        0.7362         -0.0322
   equalized_odds                                   s_birth_country            tvae                 mlp             0.6039           0.0193         0.1536          -0.1343           0.1070         0.1722          -0.0652          0.9569        0.7940         -0.1629
prejudice_remover                                   s_birth_country            tvae   prejudice_remover             0.6076           0.1320         0.1258           0.0062           0.1789         0.1663           0.0127          0.8028        0.7530         -0.0498
   equalized_odds                                   s_birth_country gaussian_copula logistic_regression             0.5823           0.1479         0.0444           0.1035           0.2052         0.0639           0.1412          0.7545        0.8866          0.1321
   equalized_odds                                   s_birth_country gaussian_copula             xgboost             0.5839           0.0235         0.0155           0.0080           0.1678         0.1492           0.0186          0.9533        0.9687          0.0154
   equalized_odds                                   s_birth_country gaussian_copula                 mlp             0.5113           0.0017         0.1333          -0.1315           0.0019         0.1676          -0.1657          0.0000        0.7351          0.7351
prejudice_remover                                   s_birth_country gaussian_copula   prejudice_remover             0.4996           0.0577         0.0497           0.0080           0.1249         0.0721           0.0529          0.5693        0.0000         -0.5693
   equalized_odds                                   s_birth_country  smote_low_perf logistic_regression             0.6223           0.0648         0.0829          -0.0181           0.2595         0.2342           0.0253          0.8183        0.7751         -0.0433
   equalized_odds                                   s_birth_country  smote_low_perf             xgboost             0.5779           0.0327         0.0107           0.0220           0.0457         0.0330           0.0127          0.9177        0.9708          0.0531
   equalized_odds                                   s_birth_country  smote_low_perf                 mlp             0.5833           0.1532         0.1818          -0.0287           0.2547         0.2789          -0.0242          0.4599        0.4177         -0.0422
prejudice_remover                                   s_birth_country  smote_low_perf   prejudice_remover             0.6218           0.0836         0.2245          -0.1410           0.1866         0.3864          -0.1998          0.7320        0.3783         -0.3537
   equalized_odds                          f_mother_education_level            real logistic_regression             0.6060           0.4606         0.0206           0.4400           0.4808         0.0120           0.4688          0.2223        0.9532          0.7308
   equalized_odds                          f_mother_education_level            real             xgboost             0.6289           0.5348         0.0347           0.5001           0.6079         0.0210           0.5869          0.1294        0.9218          0.7924
   equalized_odds                          f_mother_education_level            real                 mlp             0.6133           0.0790         0.0358           0.0432           0.1430         0.0195           0.1235          0.1138        0.9125          0.7987
prejudice_remover                          f_mother_education_level            real   prejudice_remover             0.5276           0.3581         0.0376           0.3205           0.4106         0.0776           0.3330          0.1552        0.0932         -0.0619
   equalized_odds                          f_mother_education_level           ctgan logistic_regression             0.5865           0.4228         0.1958           0.2270           0.4074         0.1784           0.2290          0.3696        0.6548          0.2851
   equalized_odds                          f_mother_education_level           ctgan             xgboost             0.5702           0.4621         0.2148           0.2473           0.5143         0.2003           0.3140          0.1414        0.5194          0.3780
   equalized_odds                          f_mother_education_level           ctgan                 mlp             0.5418           0.0033         0.1338          -0.1305           0.0046         0.1350          -0.1304          0.0679        0.7629          0.6950
prejudice_remover                          f_mother_education_level           ctgan   prejudice_remover             0.5003           0.2961         0.0010           0.2951           0.3088         0.0013           0.3074          0.1930        0.0000         -0.1930
   equalized_odds                          f_mother_education_level            tvae logistic_regression             0.5973           0.4772         0.1749           0.3023           0.4904         0.1537           0.3367          0.2956        0.6606          0.3650
   equalized_odds                          f_mother_education_level            tvae             xgboost             0.5990           0.5385         0.2883           0.2502           0.6258         0.2898           0.3360          0.0631        0.3808          0.3178
   equalized_odds                          f_mother_education_level            tvae                 mlp             0.5827           0.4557         0.1534           0.3023           0.5082         0.1655           0.3427          0.1832        0.7061          0.5229
prejudice_remover                          f_mother_education_level            tvae   prejudice_remover             0.6074           0.4905         0.4839           0.0066           0.5415         0.5824          -0.0409          0.1806        0.0503         -0.1304
   equalized_odds                          f_mother_education_level gaussian_copula logistic_regression             0.5796           0.3450         0.2111           0.1339           0.3494         0.2109           0.1385          0.3778        0.4899          0.1121
   equalized_odds                          f_mother_education_level gaussian_copula             xgboost             0.5756           0.3690         0.2529           0.1161           0.3550         0.2410           0.1140          0.3693        0.5658          0.1965
   equalized_odds                          f_mother_education_level gaussian_copula                 mlp             0.5191           0.0011         0.0773          -0.0762           0.0017         0.0840          -0.0824          0.4783        0.8322          0.3539
prejudice_remover                          f_mother_education_level gaussian_copula   prejudice_remover             0.5000           0.2383         0.0000           0.2383           0.2353         0.0000           0.2353          0.4085           NaN             NaN
   equalized_odds                          f_mother_education_level  smote_low_perf logistic_regression             0.5844           0.4008         0.1143           0.2865           0.4598         0.1548           0.3050          0.1475        0.7403          0.5928
   equalized_odds                          f_mother_education_level  smote_low_perf             xgboost             0.5772           0.4738         0.3499           0.1238           0.5281         0.3382           0.1899          0.0527        0.2806          0.2280
   equalized_odds                          f_mother_education_level  smote_low_perf                 mlp             0.5713           0.2330         0.0500           0.1830           0.2495         0.0345           0.2150          0.3309        0.8381          0.5072
prejudice_remover                          f_mother_education_level  smote_low_perf   prejudice_remover             0.6085           0.3692         0.2418           0.1275           0.4124         0.2972           0.1153          0.1770        0.3729          0.1959
   equalized_odds                          f_father_education_level            real logistic_regression             0.6115           0.4263         0.0173           0.4091           0.4537         0.0141           0.4396          0.2260        0.9600          0.7340
   equalized_odds                          f_father_education_level            real             xgboost             0.6336           0.4912         0.0349           0.4563           0.5736         0.0322           0.5415          0.1312        0.9201          0.7889
   equalized_odds                          f_father_education_level            real                 mlp             0.6154           0.0671         0.0355           0.0316           0.1185         0.0223           0.0962          0.1699        0.9129          0.7430
prejudice_remover                          f_father_education_level            real   prejudice_remover             0.5289           0.3282         0.0355           0.2927           0.3820         0.0744           0.3076          0.1757        0.0843         -0.0914
   equalized_odds                          f_father_education_level           ctgan logistic_regression             0.5901           0.4217         0.2552           0.1665           0.4061         0.2361           0.1700          0.3401        0.5817          0.2416
   equalized_odds                          f_father_education_level           ctgan             xgboost             0.5811           0.4207         0.2734           0.1472           0.4777         0.2585           0.2192          0.1505        0.4730          0.3225
   equalized_odds                          f_father_education_level           ctgan                 mlp             0.5403           0.0025         0.1615          -0.1590           0.0024         0.1612          -0.1588          0.2083        0.6894          0.4811
prejudice_remover                          f_father_education_level           ctgan   prejudice_remover             0.5004           0.2816         0.0001           0.2815           0.2954         0.0010           0.2943          0.2329        0.8332          0.6002
   equalized_odds                          f_father_education_level            tvae logistic_regression             0.6150           0.4584         0.3519           0.1064           0.4575         0.3287           0.1289          0.2817        0.4253          0.1436
   equalized_odds                          f_father_education_level            tvae             xgboost             0.6136           0.4622         0.3707           0.0915           0.5123         0.4035           0.1087          0.1090        0.2337          0.1247
   equalized_odds                          f_father_education_level            tvae                 mlp             0.6044           0.4198         0.3464           0.0734           0.4455         0.3462           0.0993          0.1873        0.3894          0.2021
prejudice_remover                          f_father_education_level            tvae   prejudice_remover             0.6171           0.4468         0.5085          -0.0617           0.4718         0.5852          -0.1135          0.1926        0.0621         -0.1306
   equalized_odds                          f_father_education_level gaussian_copula logistic_regression             0.5752           0.3320         0.2103           0.1217           0.3609         0.2863           0.0747          0.3690        0.4829          0.1140

In [28]:
# Summary table 1: overall effectiveness per technique (mean across every
# attribute/method/classifier it was run on).
if not mitigation_comparison_df.empty:
    print("Mean fairness improvement by technique (positive = fairer than unmitigated):\n")
    by_technique = mitigation_comparison_df.groupby("technique")[
        ["balanced_accuracy", "dpd_improvement", "eod_improvement", "di_improvement"]
    ].mean()
    print(by_technique.round(4).to_string())
else:
    by_technique = pd.DataFrame()

Mean fairness improvement by technique (positive = fairer than unmitigated):

                   balanced_accuracy  dpd_improvement  eod_improvement  di_improvement
technique
equalized_odds                0.5889           0.1205           0.1322          0.3315
prejudice_remover             0.5512           0.1244           0.1181         -0.1036

In [29]:
# Summary table 2: best technique per protected attribute, by mean DPD improvement.
if not mitigation_comparison_df.empty:
    by_attr_technique = (
        mitigation_comparison_df
        .groupby(["target_attr", "technique"])[["balanced_accuracy", "dpd_improvement", "eod_improvement", "di_improvement"]]
        .mean()
        .round(4)
    )
    print("Mean fairness improvement by (attribute, technique):\n")
    print(by_attr_technique.to_string())

    print("\nBest technique per attribute (highest mean DPD improvement):\n")
    best_per_attr = (
        mitigation_comparison_df
        .groupby(["target_attr", "technique"])["dpd_improvement"]
        .mean()
        .reset_index()
        .sort_values("dpd_improvement", ascending=False)
        .drop_duplicates("target_attr")
        .sort_values("target_attr")
    )
    print(best_per_attr.round(4).to_string(index=False))
else:
    by_attr_technique = pd.DataFrame()
    best_per_attr = pd.DataFrame()

Mean fairness improvement by (attribute, technique):

                                                                     balanced_accuracy  dpd_improvement  eod_improvement  di_improvement
target_attr                                       technique
f_ESCS                                            equalized_odds                0.5778           0.2174           0.2394          0.5020
                                                  prejudice_remover             0.5525           0.2011           0.1919         -0.0616
f_extent_of_books_at_home                         equalized_odds                0.5815           0.1812           0.1926          0.4492
                                                  prejudice_remover             0.5507           0.1989           0.1822         -0.0203
f_father_education_level                          equalized_odds                0.5883           0.1296           0.1537          0.3460
                                                  prejudice_remover             0.5517           0.1669           0.1592          0.1412
f_father_occupation                               equalized_odds                0.5847           0.1536           0.1694          0.4403
                                                  prejudice_remover             0.5529           0.1453           0.1219         -0.0938
f_frequency_of_see_adult_read                     equalized_odds                0.5929           0.0878           0.0827          0.2305
                                                  prejudice_remover             0.5412           0.0970           0.0697         -0.1539
f_mother_education_level                          equalized_odds                0.5822           0.1966           0.2325          0.4584
                                                  prejudice_remover             0.5488           0.1976           0.1900         -0.0473
f_mother_occupation                               equalized_odds                0.5904           0.1250           0.1283          0.4058
                                                  prejudice_remover             0.5525           0.1467           0.1351         -0.0857
p_island                                          equalized_odds                0.5949           0.0450           0.0432          0.2006
                                                  prejudice_remover             0.5533           0.0546           0.0583         -0.1069
p_percentage_of_teachers_changed_school_last_year equalized_odds                0.5922           0.0941           0.0926          0.2118
                                                  prejudice_remover             0.5522           0.0899           0.0951         -0.1791
p_public_or_private                               equalized_odds                0.5885           0.1765           0.2085          0.4687
                                                  prejudice_remover             0.5521           0.1756           0.1821         -0.1128
s_birth_country                                   equalized_odds                0.5955           0.0405           0.0466          0.2166
                                                  prejudice_remover             0.5532           0.0228           0.0365         -0.2812
s_gender                                          equalized_odds                0.5980          -0.0014          -0.0025          0.0482
                                                  prejudice_remover             0.5532          -0.0036          -0.0050         -0.1967

Best technique per attribute (highest mean DPD improvement):

                                      target_attr         technique  dpd_improvement
                                           f_ESCS    equalized_odds           0.2174
                        f_extent_of_books_at_home prejudice_remover           0.1989
                         f_father_education_level prejudice_remover           0.1669
                              f_father_occupation    equalized_odds           0.1536
                    f_frequency_of_see_adult_read prejudice_remover           0.0970
                         f_mother_education_level prejudice_remover           0.1976
                              f_mother_occupation prejudice_remover           0.1467
                                         p_island prejudice_remover           0.0546
p_percentage_of_teachers_changed_school_last_year    equalized_odds           0.0941
                              p_public_or_private    equalized_odds           0.1765
                                  s_birth_country    equalized_odds           0.0405
                                         s_gender    equalized_odds          -0.0014

## 9 · Summary

In [30]:
print("=" * 70)
print("GOAL 3 SUMMARY")
print("=" * 70)

if not results_df.empty:
    synth = results_df[results_df["method"] != BASELINE]
    real  = results_df[results_df["method"] == BASELINE]

    mean_real_ba = real["balanced_accuracy"].mean()
    print(f"\nReal baseline (mean BA across classifiers): {mean_real_ba:.4f}")

    print("\nMean balanced accuracy per synthetic method (mean across classifiers):")
    tbl = synth.groupby("method")["balanced_accuracy"].mean().sort_values(ascending=False)
    for m, v in tbl.items():
        print(f"  {m:<20}  BA={v:.4f}  (Δ={v - mean_real_ba:+.4f})")

    if "mean_dpd" in synth.columns:
        print("\nMean DPD per synthetic method (mean across classifiers):")
        for m, v in synth.groupby("method")["mean_dpd"].mean().sort_values().items():
            print(f"  {m:<20}  mean_DPD={v:.4f}")

    if "mean_odds_ratio" in synth.columns:
        print("\nMean equalized-odds odds-ratio per synthetic method (mean across classifiers, ~1.0 = fair):")
        for m, v in synth.groupby("method")["mean_odds_ratio"].mean().items():
            print(f"  {m:<20}  mean_odds_ratio={v:.4f}")

if not mitigation_comparison_df.empty:
    print("\n" + "-" * 70)
    print("MITIGATION SUMMARY")
    print("-" * 70)
    for technique, row in by_technique.iterrows():
        print(f"  {technique:<20}  BA={row['balanced_accuracy']:.4f}  "
              f"ΔDPD={row['dpd_improvement']:+.4f}  ΔEOD={row['eod_improvement']:+.4f}  ΔDI={row['di_improvement']:+.4f}")
    print("\n  Best technique per attribute (by mean DPD improvement):")
    for _, row in best_per_attr.iterrows():
        print(f"    {row['target_attr']:<25}  {row['technique']:<20}  ΔDPD={row['dpd_improvement']:+.4f}")
    print(f"\n  Full comparison saved to: {cfg['paths']['results_dir'] / 'goal3_mitigation_comparison.csv'}")

print("\nAll figures saved to:", cfg["paths"]["figures_dir"])
print("Results CSV saved to:", cfg["paths"]["results_dir"] / "goal3_results.csv")

======================================================================
GOAL 3 SUMMARY
======================================================================

Real baseline (mean BA across classifiers): 0.6100

Mean balanced accuracy per synthetic method (mean across classifiers):
  tvae                  BA=0.6135  (Δ=+0.0035)
  smote_low_perf        BA=0.5961  (Δ=-0.0140)
  ctgan                 BA=0.5609  (Δ=-0.0491)
  gaussian_copula       BA=0.5589  (Δ=-0.0511)

Mean DPD per synthetic method (mean across classifiers):
  gaussian_copula       mean_DPD=0.1774
  ctgan                 mean_DPD=0.2137
  smote_low_perf        mean_DPD=0.2315
  tvae                  mean_DPD=0.3438

Mean equalized-odds odds-ratio per synthetic method (mean across classifiers, ~1.0 = fair):
  ctgan                 mean_odds_ratio=2.1939
  gaussian_copula       mean_odds_ratio=1.8608
  smote_low_perf        mean_odds_ratio=2.6724
  tvae                  mean_odds_ratio=2.7333

----------------------------------------------------------------------
MITIGATION SUMMARY
----------------------------------------------------------------------
  equalized_odds        BA=0.5889  ΔDPD=+0.1205  ΔEOD=+0.1322  ΔDI=+0.3315
  prejudice_remover     BA=0.5512  ΔDPD=+0.1244  ΔEOD=+0.1181  ΔDI=-0.1036

  Best technique per attribute (by mean DPD improvement):
    f_ESCS                     equalized_odds        ΔDPD=+0.2174
    f_extent_of_books_at_home  prejudice_remover     ΔDPD=+0.1989
    f_father_education_level   prejudice_remover     ΔDPD=+0.1669
    f_father_occupation        equalized_odds        ΔDPD=+0.1536
    f_frequency_of_see_adult_read  prejudice_remover     ΔDPD=+0.0970
    f_mother_education_level   prejudice_remover     ΔDPD=+0.1976
    f_mother_occupation        prejudice_remover     ΔDPD=+0.1467
    p_island                   prejudice_remover     ΔDPD=+0.0546
    p_percentage_of_teachers_changed_school_last_year  equalized_odds        ΔDPD=+0.0941
    p_public_or_private        equalized_odds        ΔDPD=+0.1765
    s_birth_country            equalized_odds        ΔDPD=+0.0405
    s_gender                   equalized_odds        ΔDPD=-0.0014

  Full comparison saved to: C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\low_perf\goal3_mitigation_comparison.csv

All figures saved to: C:\Users\tomma\Desktop\petrellirambaldi2526\results\figures\mitigation\low_perf
Results CSV saved to: C:\Users\tomma\Desktop\petrellirambaldi2526\results\mitigation\low_perf\goal3_results.csv

> **📝 Notebook takeaway (clean re-run, `target_low_perf`).**
> - **Utility vs. MMD:** the two rankings diverge here (see note above on the MMD cell) — TVAE gives the best downstream utility despite not having the best distributional fidelity, and even outperforms the real baseline for MLP.
> - **Utility vs. fairness trade-off, again inverted:** mean DPD ranking is **GaussianCopula (0.237, fairest) < SMOTE (0.260) < CTGAN (0.307) < TVAE (0.373, least fair)** — the *opposite* order from utility. TVAE (best utility) is the least fair generator here; GaussianCopula (worst utility) is the fairest. Same qualitative pattern as `G3.ipynb`'s excellence task: no generator wins on both utility and fairness simultaneously.
> - **⚠️ Odds-ratio, corrected**: a minimum-support guard (≥10 true positives per group) was added to `fairness.py` to suppress genuinely thin-subgroup noise, and it works as intended (unit-verified). But the standout `ctgan | mlp | f_mother_occupation_odds_ratio=50.99` outlier is **not** thin-sample noise — checked directly against the trained model: support is 310 (privileged) vs. 3338 (unprivileged) true positives, both large, with TPR 0.32% vs. 16.4%. That's a genuine, well-supported recall disparity, not a measurement artifact — ratio-based metrics are inherently volatile whenever one group's recall is legitimately close to zero, and no support threshold fixes that. Prefer EOD (bounded, additive — the real gap here is |ΔTPR|≈0.16) over `odds_ratio` for reading cases like this. `gaussian_copula | mlp`'s exact-zero/NaN row is a separate, correctly-flagged case (`degenerate_predictions=True`, majority-class collapse).
> - **Mitigation — a reversal from the excellence task:** here **Prejudice Remover gives larger DPD/EOD improvements** than Equalized Odds (ΔDPD +0.175 vs. +0.115, ΔEOD +0.159 vs. +0.124) and wins the "best technique per attribute" table for every single protected attribute — the opposite of `G3.ipynb`, where EO dominated. However PR still costs more balanced accuracy (0.548 vs. 0.590) and still **degrades** mean DI on average (−0.026 vs. EO's +0.340). So the "better" mitigation technique is task-dependent: EO is the safer, more balanced default, but PR is worth considering here specifically for attributes where DPD/EOD reduction matters more than DI or accuracy. The mitigation loop also completed cleanly this run (160/160 fits, no `IndexError`) — the earlier crash did not recur under the current code/data.